### ISSUE TITLE
Tag for v5.7.0 is not created

### ISSUE THREAD

**Issue by pakistancan** [facebook/facebook-ios-sdk#1068]
It looks like version has been bumped to v5.7.0 in all podspec files files but tag has not been created. pod update is failing for all clients with following error

**fatal: Remote branch v5.7.0 not found in upstream origin**

Please create tag for v5.7.0.

**Comment by joesus** [comment]
Apologies. Tag is pushed. Please try to reinstall.

**Comment by joesus** [comment]
Just verified that pod can be installed. Closing.
