### ISSUE TITLE
Is there any option for the IOS (Swift) to use FBinstant?

### ISSUE THREAD

**Issue by sheikpunia1** [facebook/facebook-ios-sdk#1071]
## Checklist

- [ ] I've updated to the latest released version of the SDK
- [ ] I've searched for existing feature requests on [GitHub issues](https://github.com/facebook/facebook-ios-sdk/issues)
- [ ] I've read the [Code of Conduct](CODE_OF_CONDUCT.md)
- [ ] I've given my issue the title: `Feature Request: [name of my feature request]`

## Goals

What do you want to achieve?

## Expected Results

What do you expect to happen?

## Code Samples & Details

Please provide a code sample, as well as any additional details, to help us track down the issue. If you can provide a link to a test project that allows us to reproduce the issue, this helps us immensely in both the speed and quality of the fix.

**Note:** Remember to format your code for readability:

```swift
// INSERT YOUR CODE HERE

var example = "Example code"
```

**Comment by tianqibt** [comment]
FB Instant is a separate SDK from our mobile iOS SDK. You can find more information on this website: https://developers.facebook.com/docs/games/instant-games/sdk/.
