### ISSUE TITLE
xCode 11, IOS 13 always return "Cancel"

### ISSUE THREAD

**Issue by vvusts** [facebook/facebook-ios-sdk#1074]
## Environment

Describe your dev environment here, giving as many details as possible. If you have them, make sure to include:

- Xcode Version: 11.1
- FBSDK 5.8.0
- React native 0.59.10
- react-native-fbsdk 1.0.4

## Goals

I want to login with behavior 'Native'.

## Expected Results

When user press login he get dialog to continue to FB app to login and after login go back to app.

## Actual Results

User press login and all I get is cancel immediately.
This was working fine until I update xCode to 11.
I tried on simulator and device.

## Code Samples & Details

```
FBLoginManager.setLoginBehavior(FBLoginManager.LoginBehaviors.Native);
FBLoginManager.loginWithPermissions(
          ["email", "public_profile", "user_birthday"],
          function(error, data) {
            console.log("TEST", error, data);
if (!error) { ...
```
And when I call this I immediately get 
TEST Cancel null

Please help

UPDATE
I now downloaded xCode 10 and try to build app with it and it work fine.
Any idea why xCode make this issue?

**Comment by rodionovich221** [comment]
Same issue here, Any solution with this issue?

**Comment by abdulajet** [comment]
Same issue here, downgraded to `5.4.1` as a temporary fix.

**Comment by vvusts** [comment]
Does anyone have idea how this can be fixed except downgrade?

**Comment by Cemoo** [comment]
My pods are 

 pod 'FBSDKCoreKit/Swift'
 pod 'FBSDKLoginKit/Swift'

let fbLoginManager = LoginManager() 
```
fbLoginManager.logIn(permissions: [.publicProfile, .email],
                             viewController: self,
                             completion: { loginResult in
                                switch loginResult {
                                case .failed(let error):
                                    print("failed")
                                case .cancelled:
                                    print("canceled")
                                case .success( _, _, let accessToken):
                                    self.fbToken = accessToken
                                    self.getUserParamsFromFB()
                                }
  })
```

then

```
fileprivate final func getUserParamsFromFB() {
        GraphRequest(graphPath: "me", parameters: ["fields": "first_name, last_name, email, gender, picture.type(large)"], tokenString: fbToken.tokenString, version: Settings.graphAPIVersion, httpMethod: .get).start { (response, values, error) in
            if let res = values {
                if let response = res as? [String: Any] {
                    self.parseFacebookParameters(fbData: response)
                }
            }
        }
    }
```



That is working for me now..

**Comment by rodionovich221** [comment]
I followed [this instruction](https://developers.facebook.com/docs/ios/getting-started/) for iOS setup and it's working properly now.
I believe you already went through the document but It worth to check it out and follow the instructions once more.
Hopefully, it will solve your problem.

**Comment by Return-1** [comment]
i am also experiencing this in production for iOS 13. Any clues?

**Comment by yamato-payforward** [comment]
pod 'FBSDKCoreKit', '~> 5.8.0'
  pod 'FBSDKLoginKit', '~> 5.8.0'
  pod 'FBSDKShareKit', '~> 5.8.0'

  react-naitve version 0.60.1
  react-native-fbsdk 1.1.1

I could resolved it!

**Comment by robtimp** [comment]
@vvusts This issue should no longer be present in the more recent SDK versions. Please open a new issue if it persists after updating.

**Comment by hemant-hiteshi** [comment]
Yes, the issue persists.
RN FBSDK v2.0.0 (latest)
RN v0.61.5
issue: in iOS, open app or authenticate, coming back to our app, isCancelled: true, always. This is working fine in Android and iOS simulator (which do not have FB app).

`-             (BOOL)application:(UIApplication *)application
  didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
  
    [[FBSDKApplicationDelegate sharedInstance] application:application
    didFinishLaunchingWithOptions:launchOptions];

   // other logics


return YES;



#pragma mark Linking delegate methods
- (BOOL)application:(UIApplication *)app
            openURL:(NSURL *)url
            sourceApplication:(NSString *)sourceApplication
            annotation:(id)annotation
            options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
  
    if ([[FBSDKApplicationDelegate sharedInstance] application:app openURL:url options:options]) {
      return YES;
    }
  
    BOOL handled = [[FBSDKApplicationDelegate sharedInstance]
        application:app
        openURL:url
        sourceApplication:sourceApplication
        annotation:annotation
    ];
  
    if (handled) {
      return handled;
    }

// other logics

`

**Comment by tushargoyalofficial** [comment]
Yes, the issue persists.
RN FBSDK v2.0.0 (latest)
RN v0.61.5
issue: in iOS, open app or authenticate, coming back to our app, isCancelled: true, always. This is working fine in Android and iOS simulator (which do not have FB app).

`- (BOOL)application:(UIApplication *)application
didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {

[[FBSDKApplicationDelegate sharedInstance] application:application
didFinishLaunchingWithOptions:launchOptions];
// other logics

return YES;

#pragma mark Linking delegate methods

(BOOL)application:(UIApplication *)app
openURL:(NSURL *)url
sourceApplication:(NSString *)sourceApplication
annotation:(id)annotation
options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {

if ([[FBSDKApplicationDelegate sharedInstance] application:app openURL:url options:options]) {
return YES;
}

BOOL handled = [[FBSDKApplicationDelegate sharedInstance]
application:app
openURL:url
sourceApplication:sourceApplication
annotation:annotation
];

if (handled) {
return handled;
}

// other logics

`
