### ISSUE TITLE
Xcode 11 / iOS 13 - Error importing FB SDK Swift Libraries

### ISSUE THREAD

**Issue by sanvean** [facebook/facebook-ios-sdk#1075]
## Environment

Describe your dev environment here, giving as many details as possible. If you have them, make sure to include:

- Xcode Version: `11.0`
- Swift Version: `5.1` (if issue is Swift related)
- Installation Platform & Version: `[Manual]` version ``

## Goals

What do you want to achieve?

Use Facebook SDK in iOS13 Swift App without using CocoaPods.

## Expected Results

What do you expect to happen?
Following instructions here for using Manual Dynamic or Static Framework as Carthage support is stated as not provided: 
https://github.com/facebook/facebook-swift-sdk/blob/master/MigrationGuide.md

## Actual Results
Error Produced on import line:
`import FBSDKCoreKit`

**Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler**

## Steps to Reproduce

What are the steps necessary to reproduce this issue?
Following instructions here for using Manual Dynamic or Static Framework:
https://github.com/facebook/facebook-swift-sdk/blob/master/MigrationGuide.md

and build Xcode Project

**Comment by joesus** [comment]
This is a good point. We need to distinguish between frameworks built for 5.0.1 and 5.1. Will upload those builds to the latest release as soon as possible.

**Comment by joesus** [comment]
@sanvean Question. Are you using the dynamic or the static libraries?

**Comment by joesus** [comment]
> This is a good point. We need to distinguish between frameworks built for 5.0.1 and 5.1. Will upload those builds to the latest release as soon as possible.

I lied, this does not make any sense. Can you replicate this in a sample project?

**Comment by joesus** [comment]
I see the issue here. We built using Xcode 10.3. We should be able to just upload those built with 11. Stay tuned.

**Comment by joesus** [comment]
@sanvean, the release and build scripts have been updated to use Xcode 11. Please reopen if you have any concerns.

**Comment by sanvean** [comment]
Thanks Joe 🤙

**Comment by aehlke** [comment]
Can you make a new release so we can download these builds?

**Comment by joesus** [comment]
The updated builds were uploaded to the current release since they are what should have been there originally. 

If what is there does not work then we may have a different issue to address.

You can also clone the project and build the targets you need manually, or use a dependency manager such as CocoaPods. (Using pod FBSDKCoreKit/Swift)
