### ISSUE TITLE
Privacy Violation

### ISSUE THREAD

**Issue by davasquezp** [facebook/facebook-ios-sdk#1077]
on FBSDKKeychainStore.m is reported by static security scans as "Privacy violation".

From security scan report: 

"The function setData:forKey:accessibility:() in FBSDKKeychainStore.m mishandles confidential information on line 94. The program could compromise user privacy.The identified function mishandles confidential information. This program could compromise user privacy. "

"Explanation
Privacy violations occur when:
1. Private user information enters the program.
In this case the data comes from  in FBSDKAccessTokenCache.m at line 49.
2. The data is written to an external location, such as the console, file system, or network.
In this case the data is passed to setObject:forKey:() in FBSDKKeychainStore.m at line 94."

Report is performed by Fortify.com

**Comment by tianqibt** [comment]
We believe this is false positive. We are using Apple keychain. If you believe this is a policy violation, please contact Apple.
