### ISSUE TITLE
A number of Xcode 11 Analyze issues with FBSDKCoreKit

### ISSUE THREAD

**Issue by ethanwa** [facebook/facebook-ios-sdk#1079]
Should probably fix these:

<img width="273" alt="Screen Shot 2019-10-11 at 2 32 26 PM" src="https://user-images.githubusercontent.com/1653780/66675763-005c1500-ec34-11e9-9449-c051cdb2c2d7.png">

**Comment by QuyAnh** [comment]
Duplicate of #

**Comment by joesus** [comment]
@ethanwa, thanks for bringing this to our attention. We do accept open source contributions if you'd like to take a crack at it. 😃

**Comment by username0x0a** [comment]
Well…from what I see, both `NSNumber*` to primitive and `nonnull` checking should be turned ON for the whole project to prevent nasty bugs (first case) and even crashes (second case). Just now, I've catched an issue with newly added `FBSDKAddressInferencer` which sometimes passes `nil` file within the `loadWeights` method, resulting in a crash. Our app only uses FB SDK for Sign in and basic analytics and I don't even have idea what is this piece of code for exactly (I guess even better not no know), but yet again, FB SDK lowers our crash-free sessions.

**Comment by username0x0a** [comment]
Bumping so some more advanced compilation/analysis flags are enabled for all builds. 🙏

**Comment by joesus** [comment]
@username0x0a, @ethanwa  - opened #1329 to fix existing static analysis issues in Xcode 11.4. Did not see the integer conversion issues you mentioned in the description, but there were nullability issues that are fixed on that branch. Are you seeing additional issues with these changes?
