### ISSUE TITLE
Swift SDK -> Obj-C SDK

### ISSUE THREAD

**Issue by andriansergheev** [facebook/facebook-ios-sdk#1081]
## Environment
- Xcode Version: Version 11.1 (11A1027)
- Swift Version: 5.1
## Goals
I am trying to migrate from the SDK made for Swift, to this repo's one.

## Expected Results
Migrate.

## Actual Results

<img width="1692" alt="image" src="https://user-images.githubusercontent.com/23578783/66812589-7d88d200-ef33-11e9-9786-426260cea2e7.png">

Where should I start looking at least? It doesn't tell any useful information.
Besides support for Swift, (I suppose now the main language for development on iOS) is so poor (almost no docs). How is this possible?

**Comment by andriansergheev** [comment]
rm rf on pods solved the issue. Still no docs for Swift usage though...

**Comment by joesus** [comment]
@andriansergheev, I've updated the reference docs to include both the Objective-C and the Swift declarations. https://developers.facebook.com/docs/ios/reference 

Docs are still a work in progress. Hopefully soon we will have a better interface for discovering Swift-only functionality.
