### ISSUE TITLE
Feature Request: Suppress advertiserIDCollectionEnabledFalseWarning

### ISSUE THREAD

**Issue by liamnichols** [facebook/facebook-ios-sdk#1082]
## Checklist

- [x] I've updated to the latest released version of the SDK
- [x] I've searched for existing feature requests on [GitHub issues](https://github.com/facebook/facebook-ios-sdk/issues)
- [x] I've read the [Code of Conduct](CODE_OF_CONDUCT.md)
- [x] I've given my issue the title: `Feature Request: [name of my feature request]`

## Goals

As a consumer of the Facebook SDKs purely for social login purposes, I don't want to be notified about unrelated configuration warnings in the console logs during development of my application.

Since we have no need for Facebook to track analytics, we've set the `FacebookAdvertiserIDCollectionEnabled` and `FacebookAutoLogAppEventsEnabled` info plist keys to `false` however we now get the following log message:

```
<Warning>: The value for FacebookAdvertiserIDCollectionEnabled is currently set to FALSE so you're sending app events without collecting Advertiser ID. This can affect the quality of your advertising and analytics results.
```

## Expected Results

The log message above is not printed in my console. I explicitly opted out of any kind of automatic tracking and I don't need to be reminded about it each time we build and run the application. 

If you're happy for me to, I'd be more than happy to submit a PR removing it but I'll wait for a response here first. Thanks

**Comment by liamnichols** [comment]
The log states the following:

> so you're sending app events

But the code in `FBSDKSettings` is only checking `isAdvertiserIDCollectionEnabled`... Its wrong to assume that I'm sending events when `isAdvertiserIDCollectionEnabled` is disabled so maybe this is a bug... Could it not just log in the event that the user tries to track an event with this disabled?

**Comment by tianqibt** [comment]
Thanks for submitting this request. We will add it to our feature request list.

The complete sentence is `so you're sending app events without collecting Advertiser ID`. The flag `isAdvertiserIDCollectionEnabled` only controls whether you will send app events WITH advertiser id to Facebook, rather than control whether you send app events.

**Comment by hasanalbukhari** [comment]
So now in iOS 14 setAdvertiserTrackingEnabled is there. how is that difference than isAdvertiserIDCollectionEnabled?

**Comment by AndyMeagher** [comment]
Any updates on this feature request? I would like this removed from my console as well.

**Comment by JacopoDaeli** [comment]
@tianqibt my understanding is no difference. It's the same thing.

**Comment by JacopoDaeli** [comment]
But I may be wrong :)

**Comment by nonpensavo** [comment]
> Thanks for submitting this request. We will add it to our feature request list.
> 
> The complete sentence is `so you're sending app events without collecting Advertiser ID`. The flag `isAdvertiserIDCollectionEnabled` only controls whether you will send app events WITH advertiser id to Facebook, rather than control whether you send app events.

It's been 2 years, feature request list definitely not effective enough to remove undesired warnings spamming the console of every app using the sdk.

**Comment by marshall86** [comment]
any news about this matter? I'm getting that warning too. Thanks

**Comment by Pigpocket** [comment]
Still getting this warning when set to TRUE.

**Comment by bekroz** [comment]
Anyone still coding in 2025?

This might solve your problem:

```
func application(_ application: UIApplication,
                     didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]? = nil) -> Bool {
   Settings.shared.isAdvertiserIDCollectionEnabled = true
}
```

**Comment by yanashenyang** [comment]
> Anyone still coding in 2025?
> 
> This might solve your problem:
> 
> ```
> func application(_ application: UIApplication,
>                      didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]? = nil) -> Bool {
>    Settings.shared.isAdvertiserIDCollectionEnabled = true
> .....
> }
> ```

wow, it works
