### ISSUE TITLE
LoginBehavior deprecation warnings leaking

### ISSUE THREAD

**Issue by idrougge** [facebook/facebook-ios-sdk#1086]
## Checklist

- [X] I've updated to the latest released version of the SDK
- [X] I've searched for existing [GitHub issues](https://github.com/facebook/facebook-ios-sdk/issues)
- [X] I've read the [Code of Conduct](CODE_OF_CONDUCT.md)
- [X] This issue is not security related and can safely be disclosed publicly on GitHub

## Environment

Describe your dev environment here, giving as many details as possible. If you have them, make sure to include:

- Xcode Version: `11.1`
- Swift Version: `5.0` (if issue is Swift related)
- Installation Platform & Verison: `Cocoapods` version `1.7.2`

## Goals

Compiling with latest version of FBSDKCoreKit and FacebookLogin results in warnings about "…/Pods/FacebookLogin/Sources/Login/LoginManager.swift:74:10: 'loginBehavior' is deprecated: All login flows utilize the browser. This will be removed in the next major release" 
or:
"…/Pods/FacebookLogin/Sources/Login/FBSDKLoginKit+Typealiases.swift:119:48: 'LoginBehavior' is deprecated: All login flows utilize the browser. This will be removed in the next major release"

## Expected Results

Any warnings in a project should come from own code and not from internal behaviour of Facebook code.

**Comment by ws745630** [comment]
What reason be iOS 13 facebbook authorization failure

**Comment by joesus** [comment]
Sorry for the delay. Deprecation warnings should be surfaced to developers using a library so that they have the opportunity to move away from the deprecated code. This is intentional. Closing.
