### ISSUE TITLE
Why the CocoaPods can not work [podfile error]

### ISSUE THREAD

**Issue by mxdy** [facebook/facebook-ios-sdk#1088]
this log is in unity console*****

"
iOS framework addition failed due to a CocoaPods installation failure. This will will likely result in an non-functional Xcode project.

After the failure, "pod repo update" was executed and failed. "pod install" was then attempted again, and still failed. This may be due to a broken CocoaPods installation. See: https://guides.cocoapods.org/using/troubleshooting.html for potential solutions.

pod install output:

Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "FBSDKCoreKit":
  In Podfile:
    FBSDKCoreKit (~> 5.2)

None of your spec sources contain a spec satisfying the dependency: `FBSDKCoreKit (~> 5.2)`.

"

the last new version facebook unity sdk 7.18.0

**Comment by KylinChang** [comment]
Hi @mxdy , can you go to the exported ios project and then run `pod install`?

**Comment by joesus** [comment]
This looks like a simple pod syntax issue. 

You wrote:

> In Podfile:
FBSDKCoreKit (~> 5.2)

**Comment by bbekec** [comment]
Hello, I am having the same issue. Any solution? Thanks
