### ISSUE TITLE
Migrate UIWebview to WKWebView 

### ISSUE THREAD

**Issue by wade0317** [facebook/facebook-ios-sdk#1092]
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

**Comment by AlexIzh** [comment]
Are you sure it happens because of this repository? Have you made a small research before creating the issue? 

https://github.com/facebook/facebook-ios-sdk/blob/0d676874b2f3247e0b8cf16278fe1ee1c475403c/CHANGELOG.md#550

**Comment by KylinChang** [comment]
We have already migrated UIWebview to WKWebView, close the issue.
