### ISSUE TITLE
Xcode 11.2 / Swift 5.1.2 - Warning 'FBSDKAutoAppLinkPresentationStyle' could not be mapped

### ISSUE THREAD

**Issue by sanvean** [facebook/facebook-ios-sdk#1096]
## Environment

Describe your dev environment here, giving as many details as possible. If you have them, make sure to include:

- Xcode Version: `11.2`
- Swift Version: `5.1.2` (if issue is Swift related)
- Installation Platform & Version: Xcode Swift Package Manager / Carthage

## Goals
Warning free compilation

## Expected Results
No errors or warning generated during compilation.

## Actual Results
A warning is generated in FacebookCore and multiple App Target files:

imported declaration 'FBSDKAutoAppLinkPresentationStyle' could not be mapped to 'AutoAppLink.PresentationStyle'

## Steps to Reproduce
Add Facebook SDK using Xcode Package Manager or build using Carthage against Swift 5.1.2

Warning was first generated after first rebuilding Facebook SDK v5.9.0 using Carthage + Swift 5.1.2 following Xcode 11.2 Update. Having just migrated over to SPM from Carthage using v5.10.0 same warning messages also appears using Xcode SPM.

I have tried SPM Refresh, clearing of all Xcode Derived Data etc. warning always reappears during compilation.

**Comment by joesus** [comment]
#1099 
Assuming this is merged it will be in the next patch release. There is more detail about the cause in that linked PR.

**Comment by sanvean** [comment]
Confirmed as fixed in 5.10.1
