### ISSUE TITLE
x86_64 slice missing on Swift frameworks

### ISSUE THREAD

**Issue by paulBuchanan** [facebook/facebook-ios-sdk#1107]
Per the migration guide here:  https://github.com/facebookarchive/facebook-swift-sdk/blob/master/MigrationGuide.md

I tried using the binary frameworks FBSDKCoreKit-Swift.zip and FBSDKLoginKit-Swift.zip or those in SwiftDynamic.zip.  None of these which have the Swift module in them have x86_64 slices in them, meaning I can't use them in the simulator.  Can you please add x86_64 slices to the frameworks intended for Swift consumption, or point me to frameworks that can be used from Swift, and have x86_64 and arm64 slices?

**Comment by joesus** [comment]
Yes, but I would recommended using something like SPM or CocoaPods. Is there a particular reason you would prefer to download the frameworks and integrate them manually?

**Comment by paulBuchanan** [comment]
In an effort to reduce our compile times, we have been using Carthage to pre-build as many third party dependencies as we can.  I was building the  facebook-swift-sdk project with Carthage, but that project has been retired.  Looks like there is no Carthage support in facebook-ios-sdk as of now, so I tried using your pre-built frameworks, which doesn't have x86 slices.  I'm falling back to CocoaPods for now, but Carthage support or pre-build frameworks with x86 slices are preferred.

**Comment by joesus** [comment]
This seems like a reasonable ask. Still think it is probably same amount of effort or easier to use SPM but will attempt to provide this with the next release.

**Comment by joesus** [comment]
@paulBuchanan I believe the slices you seek are attached to the latest release. Please reopen if this is not what you were looking for and we can try and find a better solution. :D
