### ISSUE TITLE
Version 5.9.0+ breaks c++ compilation

### ISSUE THREAD

**Issue by martinbonaciugome** [facebook/facebook-ios-sdk#1111]
## Environment

- Xcode Version: 11.2.1
- Installation Platform & Verison: Cocoapods version 1.8.4

## Goals

To compile it in c++

## Expected Results

To compile

## Actual Results

FBSDKLoginButton.h gives a modules error with the line "@import FBSDKCoreKit" 

## Steps to Reproduce

Use the sdk in c++

**Comment by joesus** [comment]
Is this still an issue with version 5.10.1 ? 
Also, are you able to provide any details on what you mean by "Use the sdk in c++" so that we can try and reproduce this?

**Comment by martinbonaciugome** [comment]
Yes.

**Comment by martinbonaciugome** [comment]
just
#import <FBSDKCoreKit/FBSDKCoreKit.h>
#import <FBSDKLoginKit/FBSDKLoginKit.h>

**Comment by martinbonaciugome** [comment]
@import isn't valid c++ code

**Comment by martinbonaciugome** [comment]
from https://clang.llvm.org/docs/Modules.html

"At present, there is no C or C++ syntax for import declarations. Clang will track the modules proposal in the C++ committee. See the section Includes as imports to see how modules get imported today."

**Comment by joesus** [comment]
Hi @martinbonaciugome are you able to provide a sample project and the tool (ex: gcc, something else?) that you're using to compile the project? This will enable to work with you to provide a fix.

We might be able to get away with gating on CPPFLAGS... 

Thanks!

**Comment by martinbonaciugome** [comment]
You need to escalate this a developer, as you are asking way too much. (hint, wrap it in #ifdef __cplusplus)

**Comment by joesus** [comment]
@martinbonaciugome feel free to check out latest master, should have fixes for importing SDK into .mm files. If you're using unity you might have to wait on #1122. 

If there are issues with those please let us know. In either event the plan is to get these fixes into the next patch release.
