### ISSUE TITLE
Feature Request: Need a way to set modalPresentationStyle for the browser showing Login screen. 

### ISSUE THREAD

**Issue by akciIIe** [facebook/facebook-ios-sdk#1126]
## Environment
OS version: iOS 13
Xcode version: Xcode 11

## Goals
In iOS13, the default behaviour of presenting a view controller has changed. It's better to add a property like modalPresentationStyle so that we can choose the full screen style for the browser that shows the login page.

## Expected Results
Login page needs an option to occupy the whole screen.

## Screenshots
![Screenshot 2019-11-19 at 12 21 44 PM](https://user-images.githubusercontent.com/57934966/69123520-9acb3600-0ac7-11ea-81ad-336433fcda40.png)

**Comment by joesus** [comment]
@akciIIe, this is a good idea but probably will not rise to level of priority anytime in the near future. Please feel free to open a pull request with the changes you'd like to see and we will be prompt about reviewing it. Thanks!

**Comment by robtimp** [comment]
@akcille This view is created by ASWebAuthenticationSession, which does not expose any public API to change its presentation style, so this is not currently possible. I'd suggest [filing a radar](https://developer.apple.com/bug-reporting/) with Apple.
