### ISSUE TITLE
Can't login with another account after logout 

### ISSUE THREAD

**Issue by bianfu** [facebook/facebook-ios-sdk#1127]
After having fire logout, authorize will open safari but only allows me to authorize or not but not to enter a different used/password.
my issue is the same to https://github.com/facebook/facebook-ios-sdk/issues/106.

I tried for 5.4.1 and 5.8.0.

**Comment by joesus** [comment]
Please edit this to have adequate information to reproduce the issue, or link to a sample project and we will reopen this.
