### ISSUE TITLE
[FBAdPersistentCacheImpl storeAssetInMemory:forKey:expiration:]

### ISSUE THREAD

**Issue by boaass** [facebook/facebook-ios-sdk#1148]
#904  Environment

Describe your dev environment here, giving as many details as possible. If you have them, make sure to include:

- Xcode Version: `11.1`
- Installation Platform & Verison: `[Manual]` version `5.6.0`

- Device: 93% iPhone, all device types
- SDK: iOS Audience Network SDK

crash description: 
com.apple.root.background-qos
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000c8b2ecd70

Crashed: com.apple.root.background-qos
0  libobjc.A.dylib                0x1ad498140 objc_release + 16
1  Foundation                     0x1ada17eac -[NSConcreteMapTable grow] + 312
2  Foundation                     0x1ada0a290 -[NSConcreteMapTable setObject:forKey:] + 176
3  demo                      	  0x105df2510 __64-[FBAdPersistentCacheImpl storeAssetInMemory:forKey:expiration:]_block_invoke + 276 (FBAdPersistentCacheImpl.m:276)
4  libdispatch.dylib              0x1ad422610 _dispatch_call_block_and_release + 24
5  libdispatch.dylib              0x1ad423184 _dispatch_client_callout + 16
6  libdispatch.dylib              0x1ad3d80d8 _dispatch_root_queue_drain + 684
7  libdispatch.dylib              0x1ad3d8770 _dispatch_worker_thread2 + 128
8  libsystem_pthread.dylib        0x1ad472f48 _pthread_wqthread + 212
9  libsystem_pthread.dylib        0x1ad475ad4 start_wqthread + 8

**Comment by tianqibt** [comment]
Hi @boaass , thanks for reporting! This issue is related to Audience Network SDK. We have verified with Audience Network team the issue has already been fixed, but a new release is required. Audience Network SDK has different release schedule from Facebook SDK. So the fix would be released to public around early January.
