### ISSUE TITLE
where is the swift examples

### ISSUE THREAD

**Issue by redimongo** [facebook/facebook-ios-sdk#1151]
I have used the swift package manager to import facebook SDK yet can't find any simple examples of how to add a login button.

Would be helpful as it does NOT use 
```
import FBSDKShareKit
import FBSDKLoginKit
import FBSDKCoreKit
```

**Comment by joesus** [comment]
Currently SPM integration uses the module names `FacebookCore`, `FacebookLogin`, `FacebookShare`

Assuming you've followed the instructions here: https://developers.facebook.com/docs/facebook-login/ios/

your view controller should look like:

```
import FacebookLogin
import UIKit

class ViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.

        let loginButton = FBLoginButton(permissions: [.publicProfile])
        loginButton.center = view.center

        view.addSubview(loginButton)
    }
}
```
