### ISSUE TITLE
Getting error 'No known class method for selector 'JSONStringForObject:error:invalidObjectHandler:''

### ISSUE THREAD

**Issue by sam123789** [facebook/facebook-ios-sdk#1158]
Getting the following error while compiling project with FBSDKCoreKit v5.13.1 and FBSDKLoginKit v5.13.1 
No known class method for selector 'JSONStringForObject:error:invalidObjectHandler:'
Getting error in FBSDKFilterAddressManager.m file in following code line number 55.
```
NSString *addressParamsJSONString = [FBSDKBasicUtility JSONStringForObject:addressParams
                                                                            error:NULL
                                                             invalidObjectHandler:NULL];
    [FBSDKBasicUtility dictionary:params setObject:addressParamsJSONString forKey:@"_onDeviceParams"];
```
Platform is iOS 9.0. Using Xcode 11.

**Comment by Diovlik** [comment]
same with FBSDKCoreKit v5.11.0
