### ISSUE TITLE
Login Not Working very first time in iOS 13

### ISSUE THREAD

**Issue by sandhun** [facebook/facebook-ios-sdk#1181]
when you try to login with Facebook for the very first time nothing happens if you press login button again  LoginResult return as canceled, when you restart the app,  it works fine there after, 
this issue only comes in iOS 13, its work fine in iOS 12 .

**Comment by andreycattalin** [comment]
@sandhun How did you solve it?

**Comment by sandhun** [comment]
It was a another 3rd party library, after removing it fb login start working fine, still issue only was in iOS 13
