### ISSUE TITLE
5.15.0 FBSDKLoginKit.podspec not pushed to Cocoapods

### ISSUE THREAD

**Issue by xiao99xiao** [facebook/facebook-ios-sdk#1194]
Hate to say this but it happened again. https://github.com/facebook/facebook-ios-sdk/issues/1152

**Comment by joesus** [comment]
Pushed! 😅  There is an issue with the release script delivering a false positive on the job that's supposed to push all the pods. Looking into it. Thanks for keeping us honest. 😄
