### ISSUE TITLE
FB SDK Target silently added to all UIButtons from 5.13.0 onwards

### ISSUE THREAD

**Issue by sanvean** [facebook/facebook-ios-sdk#1202]
Hi,

Following a recent upgrade from 5.12.0 to 5.15.0 we've noticed all the UIButtons in our iOS App now appear to have the following target assigned by default when using the FB SDK:

Targets: [AnyHashable(FBSDKSuggestedEventsIndexer)]

I assume this target is silently added through swizzling by the Facebook SDK? Is this behaviour intended or a bug? If intended please could you explain why this is necessary to use the FB SDK and shouldn't this behaviour be made opt-in rather than default? 

This behaviour change has caused a number of issues related to button target logic in our app.

Thanks

**Comment by sanvean** [comment]
Btw from some quick regression testing - this change in behaviour appears to have been introduced in 5.13.0.

**Comment by joesus** [comment]
Currently this feature is a convenience for app developers whose app ids are tied to ad or business accounts. There is currently no way to disable this behavior at the SDK level but we plan on disabling this behavior for all apps that do not have a linked ad or business account.

Here's some more information about the why's of this feature.
https://www.facebook.com/business/help/787101178386829
https://www.facebook.com/business/help/542463586317574

**Comment by sanvean** [comment]
Thanks for for the info - figured it was for something like that! Mmm guess we'll stick with version 5.12.0 to avoid this behaviour for then.

**Comment by joesus** [comment]
@sanvean please try to upgrade in the near future as this issue will likely be fixed.
