### ISSUE TITLE
No Facebook SDK support for WatchOS?

### ISSUE THREAD

**Issue by NickB23** [facebook/facebook-ios-sdk#1207]
Dear Facebook Developer Community,

I'm trying to create ads for my standalone WatchOS application. In order to benefit the ads I would like to track app installs that happened because of an ad that was shown. 

I therefore want to include Facebook Analytics within my Standalone WatchOS app. However I cannot get the Facebook iOS SDK to work. I've tried Swift package manager, Cocoapods and Carthage, but they all come with their own error message. Cocoapods states:

```The platform of the target 'app name' (watchOS 6.0) is not compatible with FBSDKCoreKit/Swift (5.15.0), which does not support watchOS.```

Is it true that there is no support for WatchOS? Is it coming? Does someone in the community has run into the same problem? Are there workarounds to this problem?

Let me know!

**Comment by joesus** [comment]
Currently do not support WatchOS but will look into what it would take to support it.  :)

**Comment by NickB23** [comment]
@joesus Thanks!
