### ISSUE TITLE
Error: "use of '@import' when C++ modules are disabled" on tvOS

### ISSUE THREAD

**Issue by georgii11** [facebook/facebook-ios-sdk#1212]
Hello,

I'm trying to use version 5.15.0 for tvOS and I'm getting the following error:
```
../../FBSDKShareKit.framework/Headers/FBSDKDeviceShareViewController.h:28:1: error: use of '@import' when C++ modules are disabled, consider using -fmodules and -fcxx-modules
1818 @import FBSDKCoreKit;
```
It seems to be similar to _[this one](https://github.com/facebook/facebook-ios-sdk/issues/1128)_ from iOS.

Thanks,
Georgiana

**Comment by joesus** [comment]
Hi  @georgii11, are you able to share your podfile? It would help to debug this. It's hard to see how this would be TVOS specific tbh so my theory is that this has to do with some pod configuration. Thanks!

**Comment by georgii11** [comment]
Hi,
I am not using a podfile, I have my projects generated to link with the Frameworks which I manually download from [here](https://github.com/facebook/facebook-ios-sdk/releases/tag).

The error is in _FBSDKDeviceShareViewController.h_ which I guess is only imported on the tvOS version.
`#import <FBSDKCoreKit/FBSDKCoreKit.h>` is made under the following define:
`#if defined BUCK || defined FBSDKCOCOAPODS`,  in _FBSDKDeviceShareViewController.h_,
while the imports in other places are made under defines like:
`#if defined BUCK || defined FBSDKCOCOAPODS || defined __cplusplus`.

Also I forgot to mention here, my main project is a c++ one.

Thanks,
Georgiana

**Comment by georgii11** [comment]
Also, I just manually modified the _FBSDKDeviceShareViewController.h_ 
to switch from just `#if defined BUCK || defined FBSDKCOCOAPODS` 
into `#if defined BUCK || defined FBSDKCOCOAPODS || defined __cplusplus` 
and it compiled.

**Comment by joesus** [comment]
Excellent! Thanks for the extra eyes! If you open a pull request with that
change I’d be happy to approve it!

**Comment by georgii11** [comment]
Hi!
I'd gladly open one, but I don't have access to create a branch and push the change.
Thanks,
Georgiana

**Comment by joesus** [comment]
@georgii11 the way to do this would be to fork the repo, make the changes, push them to a branch and then make a pull request from the fork. A quick search found this repo with instructions. This is pretty standard for any open source contributions you'll make. https://github.com/firstcontributions/first-contributions :)

**Comment by georgii11** [comment]
Oh, great! I thought it would have to be on the same repo to work.
[Here](https://github.com/facebook/facebook-ios-sdk/pull/1218) it is then. :) 
Thanks!

**Comment by joesus** [comment]
These changes are in v6.0.0. Thanks for the contribution!
