### ISSUE TITLE
Facebook login not work for iOS 13 or plus devices

### ISSUE THREAD

**Issue by dpareekebiz** [facebook/facebook-ios-sdk#1252]
-canOpenURL: failed for URL: "fbauth2:/" - error: "The operation couldn’t be completed. (OSStatus error -10814.)"

when click on login button in iOS 13 app

Working fine in lower versions.

**Comment by joesus** [comment]
Have you added fbauth2 to your info.plist? Instructions here: https://developers.facebook.com/docs/ios/getting-started/

**Comment by joesus** [comment]
Also, if possible please provide a sample project that reproduces this error.

**Comment by robtimp** [comment]
@dpareekebiz Does you app include a SceneDelegate? If so, be sure to add the necessary code to that class as shown in Step 5 here: https://developers.facebook.com/docs/facebook-login/ios

**Comment by dpareekebiz** [comment]
> Have you added fbauth2 to your info.plist? Instructions here: https://developers.facebook.com/docs/ios/getting-started/

**Comment by dpareekebiz** [comment]
> @dpareekebiz Does you app include a SceneDelegate? If so, be sure to add the necessary code to that class as shown in Step 5 here: https://developers.facebook.com/docs/facebook-login/ios

I am using AppDelegate

**Comment by dpareekebiz** [comment]
> Have you added fbauth2 to your info.plist? Instructions here: https://developers.facebook.com/docs/ios/getting-started/

Already integrate fbauth2 in my info.plist but the issue is still facing

**Comment by joesus** [comment]
Please provide a sample project that reproduces the error. Otherwise it is nearly impossible to determine whether the bug is with SDK code or if it's with client code. Thanks!

**Comment by joesus** [comment]
Closing as there is no way to reproduce the bug. Please open a new issue if you are able to reproduce the issue in a simple sample project.
