### ISSUE TITLE
Getting this error on xcode 'FBSDKShareKit/FBSDKShareKit.h' file not found

### ISSUE THREAD

**Issue by kamalkam** [facebook/facebook-ios-sdk#1257]
## Checklist

i m using facebook sdk version 7.17.2
unity 2019 2.8
xcode 11.2.1

## Environment

- Xcode Version: `11.2.1`
unity 2019.2.8

- Installation Platform & Verison: `[Cocoapods|Carthage|Manual]` version `1.9.0`

## Goals

archiving the project and dustribute it to the app store

## Actual Results

getting FBSDKShareKit/FBSDKShareKit.h' file not found 
error on xcode 

what i did is i ve build my unity project for ios 
and then i tried to archive the project 
but this error shows on xcode 

----------------------------------------
on the pod file i have this >>>>>>

platform :ios, '9.0'

use_frameworks!

target 'Unity-iPhone'  do

  
  pod 'FBSDKCoreKit', '5.11.1'
  pod 'FBSDKLoginKit', '5.11.1'
  pod 'FBSDKShareKit', '5.11.1'

end

**Comment by KylinChang** [comment]
Hi @kamalkam , can you try 
`
pod 'FBSDKCoreKit', '~> 5.11'
pod 'FBSDKLoginKit', '~> 5.11'
pod 'FBSDKShareKit', '~> 5.11'
`
and run and run `pod install`

**Comment by kamalkam** [comment]
> Hi @kamalkam , can you try
> `pod 'FBSDKCoreKit', '~> 5.11' pod 'FBSDKLoginKit', '~> 5.11' pod 'FBSDKShareKit', '~> 5.11'`
> and run and run `pod install`

i ve changed the pod file to 5.11
and i run pod install but same error keeps showing

**Comment by joesus** [comment]
@kamalkam, what happens if you omit the 5.11.1 tags entirely and allow it to install the latest version? Is this an option for your project? If the bug does not exist on the latest version then there is no bug for us to fix. 

Please verify that this is an issue on the latest version.

**Comment by kamalkam** [comment]
This issue is on the latest versions of facebook sdk's , i ve tried to modifie the pod file mutiple of times but all the latest versions are having the same error when trying to build for xcode

**Comment by kamalkam** [comment]
I also tried to update the version to 5.13.1 bit same error

**Comment by joesus** [comment]
Please link to a sample project that reproduces this error.

**Comment by kamalkam** [comment]
Sometimes when i create a simple project on unity"new project" and when it has this facebook sdk it shows me the same error on xcode

**Comment by kamalkam** [comment]
I ve found a solution for this , you must use an old facebook sdk , i ve used "Facebook sdk 7.15.2" + follow this tutorial on youtube and your probleme will be solved 
https://youtu.be/nmeMHY5D4SI

**Comment by joesus** [comment]
Please open a new issue with a link to a sample project that can reproduce the issue.
