### ISSUE TITLE
Can you update the documentation?

### ISSUE THREAD

**Issue by Rickard80** [facebook/facebook-ios-sdk#1260]
The [whole documentation](https://developers.facebook.com/docs/app-events/getting-started-app-events-ios) is outdated. I'm mostly typing this for people that will google this issue, because I surely didn't find anything. Had to go through the Facebook code base to be able to send an event.

- Setup - Code
- Send Event

### SETUP - CODE

> FBSDKApplicationDelegate.sharedInstance().application(application, didFinishLaunchingWithOptions: launchOptions)

gives the error:
_'FBSDKApplicationDelegate' has been renamed to 'ApplicationDelegate'_

Should be:

`ApplicationDelegate.shared.application(application, didFinishLaunchingWithOptions: launchOptions)`

-------

> FBSDKApplicationDelegate.sharedInstance().application(app, open: url, options: options)

gives the error:

_'FBSDKApplicationDelegate' has been renamed to 'ApplicationDelegate'_

Should be:

`ApplicationDelegate.shared.application(app, open: url, options: options)`

### SEND EVENT

>    let params : AppEvent.ParametersDictionary = ["one_parameter" : "a value"] // (1)
>    let event = AppEvent(name: "test_event", parameters: params) // (2)
>    AppEventsLogger.log(event) // (3)

gives the following error messages:

1. Use of undeclared type 'AppEvent'
2. Use of unresolved identifier 'AppEvent'
3. Use of unresolved identifier 'AppEventsLogger'

Should be:

_let params : [String, Any] = ["one_parameter" : "a value"]_
_let eventName = AppEvents.Name("test_event")_
_AppEvents.logEvent(eventName, parameters: params)_

**Comment by joesus** [comment]
Closing issue but want to let you know that this is something that is being actively worked on. Thanks!
