### ISSUE TITLE
the FBAudienceNetwork (5.6.0) can't be installed from the cocoapods

### ISSUE THREAD

**Issue by 2energycell** [facebook/facebook-ios-sdk#1289]
the returned error is:

[!] Error installing FBAudienceNetwork
[!] /usr/bin/curl -f -L -o /var/folders/3k/57gdwsdd4yj6z0qzk8qqzhl80000gn/T/d20200321-12541-x8oz06/file.zip https://developers.facebook.com/resources/FBAudienceNetwork-5.6.0.zip --create-dirs --netrc-optional --retry 2

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 7729k    0 7729k    0     0   102k      0 --:--:--  0:01:15 --:--:-- 66956
curl: (92) HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)

Please fix your servers.

**Comment by joesus** [comment]
Unable to  reproduce. Likely a transient issue. Please comment if the issue persists and will reopen.

**Comment by twp520** [comment]
[!] Error installing FBAudienceNetwork
[!] /usr/bin/curl -f -L -o /var/folders/_m/f_8g_m1516d6t5zvvy9pwg180000gn/T/d20201215-14174-cei2gc/file.zip https://developers.facebook.com/resources/FBAudienceNetwork-5.5.1.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.10.0 cocoapods-downloader/1.4.0'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 4722k    0 4722k    0     0  84337      0 --:--:--  0:00:57 --:--:-- 44590
curl: (92) HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)
