### ISSUE TITLE
SDK cause Dead Lock in application

### ISSUE THREAD

**Issue by souzainf3** [facebook/facebook-ios-sdk#1306]
## Checklist
Don't call the dispach_async when the main thread already executing the task, this cause the Dead Lock.
Code in swift for fix it
```swift
 // Execute on main queue without deadlock
    static func performOnMainQueue(_ completion: @escaping () -> Void ) {
        if Thread.isMainThread {
            completion()
        } else {
            DispatchQueue.main.async(execute: {
                completion()
            })
        }
    }
```

File: FBSDKAppEvents.m
Line: 994

<img width="1322" alt="Captura de Tela 2020-03-31 às 10 23 47" src="https://user-images.githubusercontent.com/1516468/78033736-2938a980-733d-11ea-8962-7b8870ac7724.png">

**Comment by Oliverccccct** [comment]
Thanks for your scrutinizing the code!

But from the doc https://developer.apple.com/library/archive/documentation/General/Conceptual/ConcurrencyProgrammingGuide/OperationQueues/OperationQueues.html#//apple_ref/doc/uid/TP40008091-CH102-SW28,

It's okay to dispatch_async() to the current queue, but we could not dispatch_sync() to the current queue.
