### ISSUE TITLE
Fatal Exception: NSInvalidArgumentException The specified URL has an unsupported scheme. Only HTTP and HTTPS URLs are supported. +[FBAdSafariViewController presentSafariViewControllerWithURL:withRootViewController:withInlineClientToken:withHandlerTime:withDelegate:]

### ISSUE THREAD

**Issue by zhouweidong** [facebook/facebook-ios-sdk#1350]
Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x203f74ec4 __exceptionPreprocess
1  libobjc.A.dylib                0x203145a40 objc_exception_throw
2  CoreFoundation                 0x203e7b594 -[NSCache init]
3  SafariServices                 0x2196dc5cc -[SFSafariViewController initWithURL:configuration:]
4  SafariServices                 0x2196dcbb8 -[SFSafariViewController initWithURL:]
5  iReaderInt                     0x1051d4c00 +[FBAdSafariViewController presentSafariViewControllerWithURL:withRootViewController:withInlineClientToken:withHandlerTime:withDelegate:] + 54 (FBAdSafariViewController.m:54)
6  iReaderInt                     0x1051b9b40 -[FBAdOptionsView handleTap:] + 102 (FBAdOptionsView.m:102)
7  UIKitCore                      0x230d22f10 -[UIGestureRecognizerTarget _sendActionWithGestureRecognizer:]
8  UIKitCore                      0x230d2b52c _UIGestureRecognizerSendTargetActions
9  UIKitCore                      0x230d28db0 _UIGestureRecognizerSendActions
10 UIKitCore                      0x230d28298 -[UIGestureRecognizer _updateGestureWithEvent:buttonEvent:]
11 UIKitCore                      0x230d1b5a0 _UIGestureEnvironmentUpdate
12 UIKitCore                      0x230d1b10c -[UIGestureEnvironment _deliverEvent:toGestureRecognizers:usingBlock:]
13 UIKitCore                      0x230d1aedc -[UIGestureEnvironment _updateForEvent:window:]
14 UIKitCore                      0x231146c74 -[UIWindow sendEvent:]
15 UIKitCore                      0x231125f8c -[UIApplication sendEvent:]
16 iReaderInt                     0x10423e2a0 -[UIApplication(Event) swizzleSendEvent:] + 32 (ZYIdleTimeDelayManager.m:32)
17 UIKitCore                      0x2311f4df8 __dispatchPreprocessedEventFromEventQueue
18 UIKitCore                      0x2311f77f0 __handleEventQueueInternal
19 UIKitCore                      0x2311f02e0 __handleHIDEventFetcherDrain
20 CoreFoundation                 0x203f051f0 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
21 CoreFoundation                 0x203f05170 __CFRunLoopDoSource0
22 CoreFoundation                 0x203f04a54 __CFRunLoopDoSources0
23 CoreFoundation                 0x203eff920 __CFRunLoopRun
24 CoreFoundation                 0x203eff1f0 CFRunLoopRunSpecific
25 GraphicsServices               0x206178584 GSEventRunModal
26 UIKitCore                      0x23110abc0 UIApplicationMain
27 iReaderInt                     0x10417a9e8 main + 16 (main.m:16)
28 libdyld.dylib                  0x2039bebb4 start

**Comment by zhouweidong** [comment]
Help!!!

**Comment by phynet** [comment]
Can you provide more information? adding a simple crash log doesn't help people to understand your problem. Fill this information please.

## Expected Behavior


## Actual Behavior


## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version:

**Comment by joesus** [comment]
This appears related to Facebook Audience Network. This is different from the SDK. Please report Audience Network related bugs or issues to our designated developer support team -- https://developers.facebook.com/support/bugs/
