### ISSUE TITLE
Postmortem on issue #1374?

### ISSUE THREAD

**Issue by AustinConlon** [facebook/facebook-ios-sdk#1385]
Any chance a [postmortem](https://en.wikipedia.org/wiki/Postmortem_documentation) could be written reflecting on issue #1374?

**Comment by JCBird1012** [comment]
Time to make another one of these issues for #1427 as well (which will probably _also_ be ignored).

**Comment by xiao-maven** [comment]
It would be very useful to have a central document that includes:
- whether an SDK update to prevent this class of issue has been released or if a fix is planned -> this will help me prioritize upgrading the SDK.
- notes on mitigations for older versions. e.g. Is the advice to disable automatic events logging an effective mitigation?

Currently the best documentation on this seems to be the github issues themselves, but they are very noisy to sort through.

**Comment by Jumhyn** [comment]
This is especially important given that the [Facebook Developer Policy](https://developers.facebook.com/policy/) for Login (8.2) *requires* that developers use the official SDK if they support login. It's against policy to drop the SDK altogether and implement the API oneself:

> - Native iOS and Android apps that implement Facebook Login must use our official SDKs for login.

**Comment by booleanbetrayal** [comment]
@joesus - As a chief maintainer, can you provide a post-mortem?

**Comment by CyberMew** [comment]
Was there ever a post mortem on this issue?

**Comment by AustinConlon** [comment]
No, they decided to ignore it.

**Comment by booleanbetrayal** [comment]
=[
