### ISSUE TITLE
Is the 7.0.0 version available on cocoa pods? 

### ISSUE THREAD

**Issue by valmir-massoni-ifood** [facebook/facebook-ios-sdk#1404]
[!] CocoaPods could not find compatible versions for pod "FBSDKCoreKit":
  In Podfile:
    FBSDKCoreKit (= 7.0.0)

None of your spec sources contain a spec satisfying the dependency: `FBSDKCoreKit (= 7.0.0)`.

**Comment by joesus** [comment]
Yes. You can run: `pod trunk info FBSDKCoreKit`

**Comment by joesus** [comment]
fwiw it seems like this is likely related to how you're specifying the dependency in your podspec file.
