### ISSUE TITLE
Sharing works incorrectly after first Cancel

### ISSUE THREAD

**Issue by ata-may** [facebook/facebook-ios-sdk#1410]
Environment: iOS 13.5
Language: Swift

I use these methods to post photo content to Facebook timeline (native application):

func share(image: UIImage, completion: ShareRequestCompletionHandler?) {
        guard isInstalled(completion: completion) else {
            return
        }
        let photo = SharePhoto(image: image, userGenerated: true)
        let photoContent = SharePhotoContent()
        photoContent.photos = [photo]
        showShareDialog(with: photoContent, completion: completion)
 }

private func showShareDialog(with content: SharingContent, completion: ShareRequestCompletionHandler?) {
        self.completion = completion
        let dialog = ShareDialog()
        dialog.mode = .native
        dialog.shareContent = content
        dialog.shouldFailOnDataError = true
        dialog.delegate = self
        dialog.show()
    }

And also realise extension for SharingDelegate's callbacks:

extension FacebookApplication: SharingDelegate {
    
    internal func sharer(_ sharer: Sharing, didFailWithError error: Error?) {
        print("Facebook sharing: failed")
        completion?(false)
    }
    
    internal func sharer(_ sharer: Sharing, didCompleteWithResults results: [String : Any]) {
        if sharer.shareContent.shareUUID != nil {
            print("Facebook sharing: completed")
            completion?(true)
        } else {
            completion?(false)
        }
    }
    
    internal func sharerDidCancel(_ sharer: Sharing) {
        print("Facebook sharing: cancelled")
        completion?(true)
    }
}

Everything works well till user performs Cancel from Facebook application (comes back to my app) and then tries to post this photo again. SharerDidCancel(_ sharer: Sharing) is called properly but then when user presses Share button again Facebook application is stuck and users redirects to my application without any callbacks and with next error in logs:

Deep Link does not contain valid required params. URL params: {
    "bridge_args" = "{\"action_id\":\"0E731E66-27AC-4CED-BCBC-56A903885E7B\",\"app_name\":\"MyAppName\",\"sdk_version\":\"6.5.0\"}";
    "method_args" = "{\"video\":{\"assetURL\":\"assets-library://asset/asset.MOV?id=F31FC48B-4339-47D4-B6F4-D753DB110648&ext=MOV\"},\"shareUUID\":\"A1326A55-FF72-42F2-A544-9851E3C296C1\",\"dataFailuresFatal\":true}";
    "method_results" = "{\"didComplete\":true,\"completionGesture\":\"cancel\"}";
    version = 20130214;
}

This issue will not appear if user cancels previous sharing manually (inside Facebook application) before press Share second time.

How can I handle Cancel correctly (reset previous post)?

**Comment by pidogc** [comment]
@ata-may Hi, have you found a solution? I also encountered a similar problem, there is no callback after sharing
