### ISSUE TITLE
How can I check that the SDK correctly collects my advertising id?

### ISSUE THREAD

**Issue by georgii11** [facebook/facebook-ios-sdk#1422]
As, the title says, I would like to know a way to check that my advertising id is collected correctly. 
Related doc: [App events](https://developers.facebook.com/docs/app-events/getting-started-app-events-ios#step-7--add-app-events) .

A while ago, the idfa could be checked in the App events and you could even filter by it. However since [Events Manager](https://www.facebook.com/events_manager2) appeared, that's no longer possible.

I am asking this because I want to check that the advertising id actually matches and, also, I want to delay the automatic collection, and to see if when I re-enable it, it actually works.

**Comment by Oliverccccct** [comment]
Hi,

Test Events page in Events Manager could help you check if the SDK correctly collects your advertising id correctly. After you enable Advertising in your phone, Test Events will try to match your idfa with the idfa sent with the events from your phone. If the idfa is matched, the events sent back from your phone will appear in Test Events page. To do this, you should log in your facebook on your phone to make sure we have your idfa.

Thanks.

**Comment by joesus** [comment]
Seems resolved. Please comment if there are further questions.
