### ISSUE TITLE
 restrictive_data_filter_params Null Value  ---- App Crash

### ISSUE THREAD

**Issue by SathishRonal** [facebook/facebook-ios-sdk#1434]
-[NSNull count]: unrecognized selector sent to instance 0x111ec8ff0'
 "restrictive_data_filter_params" = null;
    "supports_implicit_sdk_logging" = 1;

+ (void)updateFilters:(nullable NSDictionary<NSString *, id> *)restrictiveParams
{
  if (restrictiveParams.count > 0) {
    [_params removeAllObjects];
    [_deprecatedEvents removeAllObjects];
    NSMutableArray<FBSDKRestrictiveEventFilter *> *eventFilterArray = [NSMutableArray array];
    NSMutableSet<NSString *> *deprecatedEventSet = [NSMutableSet set];
    for (NSString *eventName in restrictiveParams.allKeys) {
      if (restrictiveParams[eventName][@"is_deprecated_event"]) {
        [deprecatedEventSet addObject:eventName];
      }
      if (restrictiveParams[eventName][@"restrictive_param"]) {
        FBSDKRestrictiveEventFilter *restrictiveEventFilter = [[FBSDKRestrictiveEventFilter alloc] initWithEventName:eventName
                                                                                                         eventParams:restrictiveParams[eventName][@"restrictive_param"]];
        [eventFilterArray addObject:restrictiveEventFilter];
      }
    }
    _params = eventFilterArray;
    _deprecatedEvents = deprecatedEventSet;
  }
}

**Comment by FanYouXin** [comment]
Me too

**Comment by MauriceArikoglu** [comment]
Happens for us as well. This is crashing a production application on launch. Not cool.

**Comment by peterpaulis** [comment]
**I can confirm, 10 000+ installations keep crashing suddenly, this is an urgent issue, please escalate**

**Comment by peterpaulis** [comment]
started to work... i guess they fixed it...  but o boy, what a fail in Facebook

**Comment by FanYouXin** [comment]
> started to work... i guess they fixed it... but o boy, what a fail in Facebook, i guess someone will loose his dream job =D

Is it really fixed?

**Comment by joesus** [comment]
duplicate #1427
