### ISSUE TITLE
Allowing devs not to use the official SDKs

### ISSUE THREAD

**Issue by michaeleisel** [facebook/facebook-ios-sdk#1438]
Currently, developers are restricted to only using the official SDKs, at least in certain situations. From https://developers.facebook.com/policy/: `Native iOS and Android apps that implement Facebook Login must use our official SDKs for login`. Given the last two major issues with Facebook SDK, it would be nice to allow developers not to do this. If Facebook is concerned about variations in UI/UX, perhaps they could enforce simply that it must be identical to the SDK, and then the UIView subclasses could be extracted out for consumers to use directly.

**Comment by Jumhyn** [comment]
Great 🧠s... #1437 😄
