### ISSUE TITLE
Facebook login swift, stuck with “Open this page in Facebook” dialog

### ISSUE THREAD

**Issue by bermanapps** [facebook/facebook-ios-sdk#1442]
I using Facebook Log In, and Firebase, with swift. Latest xcode and pods.

My ViewController uses LoginButtonDelegate.

Here is some of the code in the ViewController:

   func loginButton(_ loginButton: FBLoginButton, didCompleteWith result: LoginManagerLoginResult?, error: Error?) {
    
    print("2124: didCompleteWith. result \(result.debugDescription)")
    
    if let error = error {
        print("2124: didCompleteWith. Error \(error.localizedDescription)")
        return
    }
    print("2124: Successful Facebook login: result: \(result.debugDescription)")
        
    
    if result?.isCancelled ?? false {
              print("2124: Cancelled")
          } else if error != nil {
              print("2124: ERROR: Trying to get login results")
          } else {
              print("2124: Logged in")
                let credential = FacebookAuthProvider.credential(withAccessToken: AccessToken.current!.tokenString)
                        firebaseFaceBookLogin(credential: credential)
          }
        
}
The problem this, when I click on the facebook log in icon, I get the message that the app wants to use facebook.com to sign in. I press continue. It opens up a new page, (like brouser) and asks, "Open this page in "Facebook", but then its stuck. I cannot click cancel or open in the dialog. I have to click cancel in the top left, and then I'm never able to log in.

Here is a screenshot of where things go wrong...

![image](https://user-images.githubusercontent.com/28511238/87455118-a0a0f900-c60d-11ea-9e23-52aef645c98a.png)

NOTE: When I uninstalled the facebook app it works.

Thanks!

**Comment by usamabinattique** [comment]
I have the same exact issue, it doesn't go anywhere. only the cancel button works at the top left. when you click open in the dialog attached in the screenshot, it directs you back to the basic page where it says that you've previously logged in, then the same dialog prompts again and the cycle continues

**Comment by ppansy** [comment]
Hi @bermanapps, thank you for reporting this issue! Could you please provide the app name?

**Comment by bermanapps** [comment]
Hi, the app is called Tap & Learn, however the currently published version has no issue, since I didn't use any login. I'm designing a new version of the app with log in for Firebase with Facebook, and its happening on my debugging. Does this help you?

**Comment by ppansy** [comment]
@bermanapps Thank for the reply. We are working on getting this issue resolved. In the mean time, I've disabled app switching for you app (which means that you will not get the “Open this page in Facebook” dialog) so that you would be able to complete the login process.

**Comment by bermanapps** [comment]
Thanks. So in the meantime users cannot log in with Facebook till you fix it? Thanks

**Comment by ppansy** [comment]
@bermanapps They would be able to login in the web view, but they would not be able to login using the facebook app.

**Comment by Wilsonilo** [comment]
Same issue here. Only top left cancel button seems to answer.
I solved the issue going to the Settings on my phone > Safari > Clean history and cache data

**Comment by arayinfree** [comment]
Same issue with pod install newest SDK 7.1.1

**Comment by lis186** [comment]
This issue is the same as #1067 
I think it is related to URL handling.

If you are using SceneDelegate, you can check this post. https://github.com/facebook/facebook-ios-sdk/issues/1067#issuecomment-559629930

New SwiftUI project with SwiftUI App life cycle from Xcode 12 handle URL callbacks in onOpenURL(perform:) view modifier.
https://developer.apple.com/forums/thread/651234?login=true

And I don't know how to handle the URL callback to make Facebook native app login work.

**Comment by lis186** [comment]
I found a solution to handle the URL in SwiftUI App life cycle.

`ContentView().onOpenURL { (url) in
            guard let urlScheme = url.scheme else { return }
            if urlScheme.hasPrefix("fb") {
              ApplicationDelegate.shared.application(UIApplication.shared, open: url, sourceApplication: nil, annotation: UIApplication.OpenURLOptionsKey.annotation)
            }
          }
`

reference: https://youtu.be/l9hY7vyw1bw?t=152

**Comment by gzh1265321614** [comment]
> @bermanapps感谢您的回复。我们正在努力解决此问题。同时，我为您禁用了应用程序切换应用程序（这意味着您将不会获得“在Facebook上打开此页面”对话框），这样您就可以完成登录过程。



> disabled app switching for you app

How do I disable app switching because I have the same problem

**Comment by gzh1265321614** [comment]
> @bermanapps Thank for the reply. We are working on getting this issue resolved. In the mean time, I've disabled app switching for you app (which means that you will not get the “Open this page in Facebook” dialog) so that you would be able to complete the login process.

How do I disable app switching because I have the same problem

**Comment by ppansy** [comment]
If you have similar problem, please report a bug at https://developers.facebook.com/support/bugs/, an engineer will be able to help you. @beginner-lang

**Comment by JankoDedicSwift** [comment]
have the same issue. Works on simulatos , doesn't work on testflight

**Comment by Dianaqqq** [comment]
@ppansy Hello, I'm having the same situation here after I implemented the facebook login (feature which is not available in the live app due to this issue), the user enters in a never ending loop. Could you please help me with this by disabling that popup that keeps appearing? The app's name is Readability

**Comment by ppansy** [comment]
@Dianaqqq Please create a bug report, it would be easier for us to provide assistance at per app level
