### ISSUE TITLE
Documentation and guidance for the upcoming required App Store questionnaire on what data this SDK collects

### ISSUE THREAD

**Issue by AustinConlon** [facebook/facebook-ios-sdk#1450]
From [Build trust through better privacy - WWDC 2020](https://developer.apple.com/videos/play/wwdc2020/10676/?time=906):

> Starting in fall 2020 when you submit your app to the App Store, you will need to fill out a questionnaire to describe how your app uses user data. The information you provide will be shown to users directly on your store page. This gives users the ability to see what an app does before they download it. They will be able to see if you collect a little data, or a lot of data, and if any of that data is used to track them. You should make sure to still provide further details to your users to explain your data usage, such as in your privacy policy or on your website. This information will be readily available on your App Store product page. It will also be shown for apps in the app stores on all platforms. If you have installed any third party code, such as an analytics or advertising SDK, you will also need to declare what data they collect and how it is used. Remember that SDKs run in-process of your app so they have access to the same permissions that your app does.

> And as a developer, you're responsible for the trust and handling of user data in your app, including any code that you include. And SDK developers, this would be a great time to update your documentation to make sure that developers understand what your SDK does. The developer documentation and questionnaire will be available later. In the meantime, reach out to your SDKs developers to make sure you understand how they may collect and use data.

**Comment by AustinConlon** [comment]
[Details for app privacy questions now available](https://developer.apple.com/news/?id=hx9s63c5)

**Comment by AustinConlon** [comment]
iOS 14 ships tomorrow.

**Comment by trzecieu** [comment]
It's already out.

**Comment by joesus** [comment]
Looks like the form will be required starting on Dec 8, 2020 - https://developer.apple.com/app-store/app-privacy-details/

Please see our guidance here:
https://developers.facebook.com/blog/post/2020/10/22/preparing-for-apple-app-store-data-disclosure-requirements
