### ISSUE TITLE
Feature Request: iOS14 support

### ISSUE THREAD

**Issue by chuganzy** [facebook/facebook-ios-sdk#1453]
## Checklist

- [x] I've updated to the latest released version of the SDK
- [x] I've searched for existing feature requests on [GitHub issues](https://github.com/facebook/facebook-ios-sdk/issues)
- [x] I've read the [Code of Conduct](CODE_OF_CONDUCT.md)
- [x] I've given my issue the title: `Feature Request: [name of my feature request]`

## Goals

Support iOS14 updates especially around privacy

## Expected Results

Seamless transition to iOS 14

## Code Samples & Details

N/A

### Timeline for iOS14 support 

At least FBSDK has to integrate `ATTrackingManager`.

### What can happen if we disable IDFA using `FacebookAdvertiserIDCollectionEnabled`?

Especially wondering if deferred deep link still works..

**Comment by joesus** [comment]
This is a known issue and is being addressed. Please 'watch' this repo to be notified about upcoming releases. Thanks!

**Comment by danwey** [comment]
About what time?

**Comment by erisvaldojunior** [comment]
News on this?
