### ISSUE TITLE
why Deferred Deep Linking is nil?

### ISSUE THREAD

**Issue by hyqsfaf** [facebook/facebook-ios-sdk#1457]
I use the tool to send a delayed deep link to the mobile app, click it to jump to the App Store. Do not download, install with Xcode, then
  [FBSDKAppLinkUtility fetchDeferredAppLink:^(NSURL *url, NSError *error) {
             if (error) {
                 NSLog(@"Received error while fetching deferred app link %@", error);
             }
             if (url) {
             }
    }];

url is nil. It is never possible to obtain delayed deep links.

  If my test method is wrong. How do I test delayed deep links

**Comment by joesus** [comment]
You can use the https://developers.facebook.com/tools/app-ads-helper/ to verify your deeplinking setup. I'd advise using a 'live' facebook app, and testing on a device that's logged in with the same credentials you're logged into the browser with. Please open if there's an actual bug that you can reliably reproduce.
