### ISSUE TITLE
iOS 14 is displaying a prompt asking for permission to "find and connect to devices on your local network"

### ISSUE THREAD

**Issue by Russel1** [facebook/facebook-ios-sdk#1469]
Our app on iOS 14 is displaying a prompt asking for permission to "find and connect to devices on your local network". Can we disable this behaviour?

The Facebook SDK for iOS is looking at devices on our user's network and we would like to disable this behaviour immediately as quite the privacy concern which will certainly lead to churn.

**Comment by joesus** [comment]
Hi @Russel1, can you point to where this is happening? I'm almost 100% positive there is no device discovery code in the SDK.

**Comment by joesus** [comment]
https://developer.apple.com/forums/thread/654243

**Comment by troy-lamerton** [comment]
@joesus The permission prompt is a bit misleading, it can be triggered by simply opening a socket.

Here is an example of another SDK accidently triggering it with their hot reloading feature: https://github.com/flutter/flutter/issues/60634

A blank iOS app with the Facebook SDK added will trigger the prompt, according to this reddit comment from one month ago:
https://www.reddit.com/r/iOSProgramming/comments/hqtov0/has_anybody_else_noticed_the_facebook_sdk/fy0lsva

**Comment by Russel1** [comment]
Why was this issue closed?
