### ISSUE TITLE
Facebook SDK v6.5.2 needs Accelerate.framework

### ISSUE THREAD

**Issue by masteage** [facebook/facebook-ios-sdk#1470]
## Environment

- Xcode Version: v11.6
- Installation Platform & Verison: Facebook SDK v6.5.2

## Goals

- make README.md plz, add contents **_"Accelerate.framework"_**

## Build Error Message

```
Showing All Messages
Undefined symbol: _vDSP_vclip

Undefined symbol: _vDSP_vsadd

Undefined symbol: _vvexpf

Undefined symbol: _vDSP_sve

Undefined symbol: _vDSP_mmul

Undefined symbol: _vDSP_maxv

Undefined symbol: _vDSP_dotpr

Undefined symbol: _vDSP_vsdiv
```

**Comment by joesus** [comment]
This is not necessary on newer version.

**Comment by faraz-maqsad** [comment]
> This is not necessary on newer version.

I am currently on v13.0.0 downloaded with SPM and it's showing this error message.
