### ISSUE TITLE
Facebook Sign out Swift

### ISSUE THREAD

**Issue by KOSURUUDAYSAIKUMAR** [facebook/facebook-ios-sdk#1472]
When I sign in through my app and later I click sign out button with code 

let loginManager = LoginManager()
loginManager.logOut()

After login it is showing previous user account details, I need to sign out completely and sign in a new different account. 

Can you please help me?

**Comment by joesus** [comment]
This is a known limitation. Please file a bug with https://developers.facebook.com/support/bugs/ and let them know how this is affecting you.
