### ISSUE TITLE
Feature Request for iOS 14: can the IDFA be externalized or put behind a macro?

### ISSUE THREAD

**Issue by cruzach** [facebook/facebook-ios-sdk#1475]
I know this was brought up in https://github.com/facebook/facebook-ios-sdk/issues/1453 and we were asked to wait and watch the repo for updates, but I just wanted to see if we could get some clarity on what the options regarding IDFA usage will be, and maybe suggest a good alternative

## Checklist

- [x] I've searched for existing feature requests on [GitHub issues](https://github.com/facebook/facebook-ios-sdk/issues)
- [x] I've read the [Code of Conduct](CODE_OF_CONDUCT.md)
- [x] I've given my issue the title: `Feature Request: [name of my feature request]`

## Feature

To avoid any trouble with the App Submission process, it would be nice to completely eliminate any IDFA-related code if we're not planning on collecting the IDFA anyways. This has the added benefit that developers wouldn't need to check the "My app uses the IDFA" box upon app submission

This was done in some other libraries that relied on IDFA:
- Segment externalized the code so that you have to provide the IDFA yourself- https://github.com/segmentio/analytics-ios/pull/892/files
- Amplitude put the IDFA code behind a macro - https://github.com/amplitude/Amplitude-iOS/commit/cbcf7d64b1e25301843f295ac3f000a2a22ba65e

This would be a huge help for people relying on the FB iOS SDK but not collecting the IDFA. There's also [a question about this on the FB developer forums](https://developers.facebook.com/community/threads/2386093478363765/)

**Comment by erisvaldojunior** [comment]
Also would like to know

**Comment by Legoless** [comment]
This is a major issue, as Apple started rejecting the app based on the included code. We are a kids app and we've disabled IDFA collection in Facebook SDK a long time ago, but we still use Facebook's login for parents to log into the app. However since SDK still includes IDFA code, we're now unable to pass the review.
