### ISSUE TITLE
FBAudienceNetwork -[AVPlayerLayer setDisplayEngineDelegate:]: unrecognized selector sent to instance 0x280cefd40

### ISSUE THREAD

**Issue by wolee** [facebook/facebook-ios-sdk#1532]
FBAudienceNetwork 5.6.1

Fatal Exception: NSInvalidArgumentException
-[AVPlayerLayer setDisplayEngineDelegate:]: unrecognized selector sent to instance 0x280cefd40
-[FNFSynchronousPlayer initWithDisplayEngine:config:audioEngine:audioDecoder:clock:runningQueue:muted:asyncTimebase:]
keyboard_arrow_down

Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x199aad654 __exceptionPreprocess
1  libobjc.A.dylib                0x1997cfbcc objc_exception_throw
2  CoreFoundation                 0x1999b1dd8 -[NSOrderedSet initWithSet:copyItems:]
3  CoreFoundation                 0x199ab17f8 ___forwarding___
4  CoreFoundation                 0x199ab371c _CF_forwarding_prep_0
5  app                            0x1037fc238 -[FNFSynchronousPlayer initWithDisplayEngine:config:audioEngine:audioDecoder:clock:runningQueue:muted:asyncTimebase:] + 149 (FNFSynchronousPlayer.mm:149)
6  app                            0x1037f6db4 -[FNFPlayer initWithDisplayEngine:clock:config:asyncTimebase:enableOpus:] + 75 (FNFPlayer.mm:75)
7  app                            0x1037f6bf8 -[FNFPlayer initWithDisplayEngine:config:asyncTimebase:enableOpus:] + 48 (FNFPlayer.mm:48)
8  app                            0x1037f6b3c -[FNFPlayer initWithDisplayEngine:] + 41 (FNFPlayer.mm:41)
9  app                            0x1037c9cc0 __loadVideoAsset_block_invoke + 69 (FBAdFNFCompatibility.m:69)
10 app                            0x103808d24 -[FNFLocalMp4Asset _startWithAsset:completionHandler:] + 298 (FNFLocalMp4Asset.mm:298)
11 app                            0x10380aa20 __70-[FNFLocalMp4Asset loadValuesAsynchronouslyForKeys:completionHandler:]_block_invoke + 354 (FNFLocalMp4Asset.mm:354)
12 libdispatch.dylib              0x1997729a8 _dispatch_call_block_and_release
13 libdispatch.dylib              0x199773524 _dispatch_client_callout
14 libdispatch.dylib              0x199750b3c _dispatch_lane_serial_drain$VARIANT$armv81
15 libdispatch.dylib              0x19975154c _dispatch_lane_invoke$VARIANT$armv81
16 libdispatch.dylib              0x19975a84c _dispatch_workloop_worker_thread
17 libsystem_pthread.dylib        0x1997c4b74 _pthread_wqthread
18 libsystem_pthread.dylib        0x1997c7740 start_wqthread

update FBAudienceNetwork to 6.0.0, the issues is still exist.

**Comment by joesus** [comment]
This SDK is a separate project from FBAudience network. Please file a bug at: https://developers.facebook.com/support/bugs/

**Comment by DSNNET** [comment]
FBAudienceNetwork  5.8.0
Starting from October 21st, we have the same problem. This problem caused many users to crash.
