### ISSUE TITLE
GameRequestDialog calls from iOS and Android have issues

### ISSUE THREAD

**Issue by andyvene** [facebook/facebook-ios-sdk#1541]
**'GameRequestDialog'** calls using **Action.Type=turn** , the dialog window appears but it says the below allert.

Error dialog:
'Sorry something went wrong.
We are working on it and we'll get it fixed as soon as we can'

_USING:
FB SDKs Android and iOS versions 8 and 7 and 5 tested. Also using the latest FB API 8.0 version.
Also using the FB UNITY SDK.
Was working fine 6 days ago w/o changing the code._

**Comment by Mxiim** [comment]
Hello, could you give a standalone example how to reproduce this issue?

**Comment by andyvene** [comment]
Hello,
actually i don't know about a stand alone example what you mean. I want to say that i am using the classic syntax of making this type of call which is described also in this link:
https://developers.facebook.com/docs/games/services/gamerequests/

Nothing special. If you can make this type of call work ...??!!!
Tested with all 3 codes in the above link. Android, iOS, Unity.
Was working fine 1 week ago and for 6 years now.

**Comment by andyvene** [comment]
Today is working !!
Consider closed this issue. It was for sure a facebook server issue.
Tested with the same code today using Android, iOS and Unity SDK and all working again.

**Comment by joesus** [comment]
Glad it's resolved!
