### ISSUE TITLE
Tun off crash collection in sdk

### ISSUE THREAD

**Issue by jaderYang** [facebook/facebook-ios-sdk#1547]
For some reasons, I need to turn off Facebook’s crash collection, but keep the tracking feature.
I tried sending an email to tianqibt@fb.com, but no reply.
Is there any other way?

**Comment by tianqibt** [comment]
Sorry, didn't receive the email. @jaderYang would you please send it again? Thanks!

**Comment by jaderYang** [comment]
> Sorry, didn't receive the email. @jaderYang would you please send it again? Thanks!

Ok.

**Comment by tianqibt** [comment]
We have turned off crash collection for your app.

**Comment by jaderYang** [comment]
Thanks a lot. @tianqibt
