### ISSUE TITLE
Banner Ads not displaying properly 

### ISSUE THREAD

**Issue by sohilmultani** [facebook/facebook-ios-sdk#1548]
Banner Ads not displaying properly it display half i can't find out what is the problem. if anybody know please help me.

i am using POD and Manually add Facebook audience network. but the result are same.

is this SDK Bug?  

![BannerAds](https://user-images.githubusercontent.com/11556558/97108553-64913000-16f4-11eb-9bf3-ae513dab9761.png)

I am using this code

@property (weak, nonatomic) IBOutlet UIView *adContainer;
@property (nonatomic, strong) FBAdView *adView;

- (void)viewDidLoad
{
  [super viewDidLoad];
  self.adView = [[FBAdView alloc] initWithPlacementID:@"YOUR_PLACEMENT_ID"
                                               adSize:kFBAdSizeHeight50Banner
                                   rootViewController:self];
  self.adView.frame = CGRectMake(0, 0, 320, 50);
  self.adView.delegate = self;
  [self.adView loadAd];
}

- (void)adViewDidLoad:(FBAdView *)adView
{
  NSLog(@"Ad was loaded and ready to be displayed");
  [self showBanner];
}

- (void)showBanner
{
  if (self.adView && self.adView.isAdValid) {
    [self.adContainer addSubview:self.adView];
  }
}

I am use pod 'FBAudienceNetwork'
And
Manual Download
iOS Audience Network SDK 6.0.0
iOS Audience Network SDK 5.10.1
and Add FBSDKCoreKit

I am check every thing one by one but not work properly. same issue in all this.
Please help :)

**Comment by jawwad** [comment]
Hi @sohilmultani - Sorry for the late follow up. Are you still encountering an issue with this?

**Comment by jawwad** [comment]
Hi @sohilmultani - Since this issue is a few months old and I haven't heard back on if you are still encountering the issue, I'm going to go ahead and close it out. If you are still encountering the issue on the latest version of the SDK please feel free to open another issue. Thanks!
