### ISSUE TITLE
I have encount an curious problem

### ISSUE THREAD

**Issue by iningwei** [facebook/facebook-ios-sdk#1549]
I use unity3d 2019.4.0f1+FB SDK For Unity 8.1.0
I have logined game with my fb account.After I have uninstalled my app and even Facebook app，but fb login still recorded my account message.It is annoy.

![image](https://user-images.githubusercontent.com/22534859/97161014-2d845280-17b8-11eb-888e-cdfd06719afa.png)

Why FB SDK can still get my fb account message?

**Comment by iningwei** [comment]
Need help!!!

**Comment by jawwad** [comment]
I'm not sure what the issue is here, but this issue is pretty stale so I'm going to close this out. Please re-open if you are still encountering an issue.
