### ISSUE TITLE
[FBSDKCrashHandler disable]; crash if called before handler installed

### ISSUE THREAD

**Issue by Tayphoon** [facebook/facebook-ios-sdk#1556]
## Environment

- FBSDKCoreKit Version: `7.0.1`
- Xcode Version: `12.1`
- Swift Version: `5.0`
- Installation Platform & Verison: `Cocoapods` version `1.9.3`

## Goals

Disable crash handler?

## Expected Results

App crashed.

## Actual Results

uninstallSignalsHandler() does not check if previousSignalHandlers initilized

```objc
[FBSDKCrashHandler disable];
```

#Suggestion

```c
static void uninstallSignalsHandler()
{
  if (previousSignalHandlers != NULL) {
    for (int i = 0; i < fatalSignalsCount; i++) {
      sigaction(fatalSignals[i], &previousSignalHandlers[i], NULL);
    }
  }
}
```

**Comment by tianqibt** [comment]
Thanks for reporting this issue! Please do not use this function to disable sdk crash handler, it was supposed to use internally, and we will fix the issue as soon as possible. If you would like to disable crash handler, please send your fb app id to tianqibt@fb.com. We will disable it for your app on our side.
