### ISSUE TITLE
为什么从5.15.1版本后默认会把swift文件带进去呢？

### ISSUE THREAD

**Issue by MolierQueen** [facebook/facebook-ios-sdk#1571]
看了你们的podspec文件，从5.15.1版本的SDK后会自动把swift相关的文件带进去，但是实际并没有使用到这些文件，导致我们项目中不得不使用混编，增大了整个包的大小，请问是否可以像5.15.0版本那样设置下exclude_files呢？将Swift/*排除出去。

**Comment by aTyrant** [comment]
这样显得他们开发牛逼，居然会写 Swift ！虽然文件没有用到，但是你不得不写桥接文件以适配混编，这样你的包就会增大近一倍，这样用户就会产生抵触情绪，并且这样对设备内存大小就更严格，用户不得不购买大内存手机。综上所述，fb 的开发就是在帮苹果卖手机的傻逼。我说的

**Comment by joesus** [comment]
Duplicate of https://github.com/facebook/facebook-ios-sdk/issues/1390

With app thinning the size your customers will gain is fairly minimal. It looks like a large increase before app thinning.
