### ISSUE TITLE
FBSDKCrashHandler

### ISSUE THREAD

**Issue by Tayphoon** [facebook/facebook-ios-sdk#1576]
## Environment

- FBSDKCoreKit Version: `7.0.1`
- Xcode Version: `12.1`
- Swift Version: `5.0`
- Installation Platform & Verison: `Cocoapods` version `1.9.3`

## Crash
Incident Identifier: ***
CrashReporter Key:   ***
Hardware Model:      iPhone11,6
Process:         ***
Path:            ***
Identifier:      ***
Version:         ***
Code Type:       arm64
Parent Process:   [1]

Date/Time:       2020-11-12T22:08:02.999Z
Launch Time:     2020-11-12T16:55:45Z
OS Version:      iPhone OS 14.2 (18B92)
Report Version:  104

Exception Type:  SIGABRT
Exception Codes: #0 at 0x1cd25f414
Crashed Thread:  9

Application Specific Information:
*** Terminating app due to uncaught exception 'NSMallocException', reason: '*** -[NSFileManager fileSystemRepresentationWithPath:]: unable to allocate memory for length (937)'

Last Exception Backtrace:
0   CoreFoundation                       0x00000001a0360878 0x00000001a023b000 + 1202296
1   libobjc.A.dylib                      0x00000001b48b6c50 0x00000001b48b0000 + 27728
2   Foundation                           0x00000001a1593300 0x00000001a1579000 + 107264
3   Foundation                           0x00000001a16b4c74 0x00000001a1579000 + 1293428
4   Foundation                           0x00000001a16b5cc0 0x00000001a1579000 + 1297600
5   Foundation                           0x00000001a16b62f0 0x00000001a1579000 + 1299184
6   ***                                  0x00000001045f96dc +[FBSDKCrashHandler saveCrashLog:] (FBSDKCrashHandler.m:373)
7   ***                                  0x00000001045f8a28 +[FBSDKCrashHandler saveSignal:withCallStack:] (FBSDKCrashHandler.m:263)
8   ***                                  0x00000001045f9cf8 FBSDKSignalHandler (FBSDKCrashHandler.m:223)
9   libsystem_platform.dylib             0x00000001e9772290 0x00000001e976d000 + 21136
10  AGXMetalA12                          0x00000001ea8c4608 0x00000001ea6fc000 + 1869320
11  AGXMetalA12                          0x00000001ea8c426c 0x00000001ea6fc000 + 1868396
12  AppleMetalGLRenderer                 0x00000001e9c98a18 0x00000001e9c84000 + 84504
13  GLEngine                             0x00000001d2ebe70c 0x00000001d2e99000 + 153356

Thread 9 Crashed:
0   libsystem_kernel.dylib               0x00000001cd25f414 0x1cd237000 + 164884
1   libsystem_c.dylib                    0x00000001a9684b74 0x1a960e000 + 486260
2   ***                                  0x0000000109d9ca10 uncaught_exception_handler.cold.1 + 24
3   ***                                  0x0000000109d7b578 uncaught_exception_handler (PLCrashReporter.m:370)
4   ***                                  0x00000001045f874c FBSDKExceptionHandler (FBSDKCrashHandler.m:184)
5   CoreFoundation                       0x00000001a0360b80 0x1a023b000 + 1203072
6   libobjc.A.dylib                      0x00000001b48b6f58 0x1b48b0000 + 28504
8   libc++abi.dylib                      0x00000001b49bc0e0 0x1b49a9000 + 78048
9   libc++abi.dylib                      0x00000001b49bf150 0x1b49a9000 + 90448
10  libobjc.A.dylib                      0x00000001b48b6e1c 0x1b48b0000 + 28188
11  CoreFoundation                       0x00000001a02d5308 0x1a023b000 + 631560
12  Foundation                           0x00000001a1581df0 0x1a1579000 + 36336
14  Foundation                           0x00000001a16f3a34 0x1a1579000 + 1550900
15  libsystem_pthread.dylib              0x00000001e9776b40 0x1e9775000 + 6976
16  libsystem_pthread.dylib              0x00000001e977f768 0x1e9775000 + 42856

Thread 0:
0   libsystem_kernel.dylib               0x00000001cd23b2d0 0x1cd237000 + 17104
1   CoreFoundation                       0x00000001a02dbc30 0x1a023b000 + 658480
2   CoreFoundation                       0x00000001a02d5c14 0x1a023b000 + 633876
3   CoreFoundation                       0x00000001a02d521c 0x1a023b000 + 631324
4   GraphicsServices                     0x00000001b7354784 0x1b7351000 + 14212
5   UIKitCore                            0x00000001a2d0e200 0x1a2147000 + 12349952
6   UIKitCore                            0x00000001a2d13a74 0x1a2147000 + 12372596
7   ***                                  0x0000000106aced5c main (main.m:16)
8   libdyld.dylib                        0x000000019ff956c0 0x19ff94000 + 5824

**Comment by jawwad** [comment]
Hi @Tayphoon - It looks like this is an older issue so I'm going to close this out. If you still encounter the issue on the most recent version of the SDK (v11.1.0) please let us know.
