### ISSUE TITLE
Xcode12 issue: FBSDKApplicationDelegate' has different definitions in different modules

### ISSUE THREAD

**Issue by ajdeacon** [facebook/facebook-ios-sdk#1581]
Hi

I have updated my version of Xcode from 11 to 12.2 
The project in question compiles successfully in Xcode 11. However, in Xcode 12.2  the build fails with the following error.

'FBSDKApplicationDelegate' has different definitions in different modules; first difference is definition in module 'FBSDKCoreKit' found return type is 'instancetype _Nonnull' (aka 'id')

Can a fix or workaround be suggested by the iOS-sdk team? 

Regards
AD

**Comment by joesus** [comment]
Thanks for reporting an issue! I'd like to help out but there is not enough information here to help debug the issue. Please open a new issue that follows the template or report this to our designated developer support team -- https://developers.facebook.com/support/bugs/ -- as this will help us get more information and resolve it more quickly.
