### ISSUE TITLE
Unsupported post request

### ISSUE THREAD

**Issue by Tayphoon** [facebook/facebook-ios-sdk#1583]
## Environment

- FBSDKCoreKit Version: `7.0.1`
- Xcode Version: `12.1`
- Swift Version: `5.0`
- Installation Platform & Verison: `Cocoapods` version `1.9.3`

OKFacebookAdService log:Error Domain=com.facebook.ads.sdk Code=2000 "Server Error" UserInfo={NSLocalizedDescription=Server Error, FBAdErrorDetailKey={
    code = 100;
    message = "Unsupported post request.";
    type = GraphMethodException;
    url = "https://graph.facebook.com/network_ads_common/";
}}

**Comment by jawwad** [comment]
Hi @Tayphoon - Are you still encountering this issue? If so could you provide more details on when you encounter this?

**Comment by jawwad** [comment]
Hi @Tayphoon - Since I haven't heard back from you on this I'm going to close the issue out. Feel free to re-open if you are still encountering the issue. Thanks!
