### ISSUE TITLE
Replaced old FBSDKLoginKit and FBSDKCoreKit framework with new v8.2.0 case build error

### ISSUE THREAD

**Issue by KillWilde** [facebook/facebook-ios-sdk#1592]
such like this:
Undefined symbols for architecture armv7:
  "__swiftEmptyDictionarySingleton", referenced from:
      function signature specialization <Arg[0] = Owned To Guaranteed, Arg[1] = Dead> of generic specialization <serialized, Swift.String, Any> of Swift.Dictionary.init(dictionaryLiteral: (A, B)...) -> [A : B] in FBSDKLoginKit(LoginManager.o)
  "protocol conformance descriptor for Swift.Int : Swift.FixedWidthInteger in Swift", referenced from:
      lazy protocol witness table accessor for type Swift.Int and conformance Swift.Int : Swift.FixedWidthInteger in Swift in FBSDKLoginKit(LoginManager.o)
  "type metadata for Swift.Int", referenced from:
      lazy protocol witness table accessor for type Swift.Int and conformance Swift.Int : Swift.FixedWidthInteger in Swift in FBSDKLoginKit(LoginManager.o)
  "associated conformance descriptor for Foundation._ErrorCodeProtocol.Foundation._ErrorCodeProtocol._ErrorType: Foundation._BridgedStoredNSError", referenced from:
      _got.$s10Foundation18_ErrorCodeProtocolP01_B4TypeAC_AA21_BridgedStoredNSErrorTn in FBSDKLoginKit(LoginManager.o)
  "protocol descriptor for Foundation._ErrorCodeProtocol", referenced from:
      _got.$s10Foundation18_ErrorCodeProtocolMp in FBSDKLoginKit(LoginManager.o)
  "method descriptor for Foundation._BridgedStoredNSError.init(_nsError: __C.NSError) -> A", referenced from:
      _got.$s10Foundation21_BridgedStoredNSErrorP8_nsErrorxSo0D0C_tcfCTq in FBSDKLoginKit(LoginManager.o)
  "associated conformance descriptor for Foundation._BridgedStoredNSError.Foundation._BridgedStoredNSError.Code: Swift.RawRepresentable", referenced from:
      _got.$s10Foundation21_BridgedStoredNSErrorP4CodeAC_SYTn in FBSDKLoginKit(LoginManager.o)
  "base conformance descriptor for Foundation._ErrorCodeProtocol: Swift.Equatable", referenced from:

But  I'm sure this two framework contains armv7  ,I comfirm with lipo -info ;

**Comment by joesus** [comment]
Are you able to link a simple sample app that shows this? There are many ways to include the SDK in a project and it's very hard to replicate issues without knowing precisely how a project and the SDK are integrated. Also it would help to know what you mean by 'old'. Thanks!

**Comment by kobe1941** [comment]
just  new a empty swift file, and everything is ok.

**Comment by KillWilde** [comment]
I just follow kobe1941‘s  suggestion， create an empty swift file in my project , now it works fine. I think maybe my project was OC type, FBSDKFramework contains swift code need config swift code environment . Thank you for your answers！
