### ISSUE TITLE
How can I  import FBSDKCoreKit FBSDKLoginKit and FBSDKShareKit

### ISSUE THREAD

**Issue by lbfamous** [facebook/facebook-ios-sdk#1599]
HOW Can I  do this .I only  want to use the object-c packages with swift package manager，how can i do it

**Comment by joesus** [comment]
You can do this by importing `FBSDK...` but keep in mind that this is not a viable long term strategy. We are taking deliberate steps to move to Swift. IMHO it would be better to figure out how to use the kits that include Swift code.
