### ISSUE TITLE
How to import the only object-c package using swift package manager 

### ISSUE THREAD

**Issue by lbfamous** [facebook/facebook-ios-sdk#1600]
this is in readme files 

Swift Package Manager (available Xcode 11.2 and forward)
In Xcode, select File > Swift Packages > Add Package Dependency.
Follow the prompts using the URL for this repository and a minimum semantic version of v5.10.0
Check-out the tutorials available online at: https://developers.facebook.com/docs/ios/getting-started
Start coding! Visit https://developers.facebook.com/docs/ios for tutorials and reference documentation.
Note for Swift Package Manager Users:

If you explicitly DO NOT want to include Swift, import FBSDKCoreKit FBSDKLoginKit and FBSDKShareKit
For projects that include Swift, use FacebookCore, FacebookLogin, and FacebookShare

【DO NOT want to include Swift, import FBSDKCoreKit FBSDKLoginKit and FBSDKShareKit】

I see you write this in the readme file, but  this is no branch on only support object-c packages for swift package manager, do I Need fork this project and create a new branch for myself??

or is there another way to use object-c packages( like FBSDKCorekit ...) on using Swift package manager.

if there is no ,please change you readme files,this made me in trouble..

**Comment by joesus** [comment]
@lbfamous - if you look at Package.swift you'll see stuff like this:

```
.library(
            name: "FacebookCore",
            targets: ["FacebookCore"]
        ),

...

.target(
            name: "FacebookCore",
            dependencies: ["FBSDKCoreKit"],
            path: "FBSDKCoreKit/FBSDKCoreKit/Swift"
        ),
```

This means that we're defining the library as "FacebookCore" this is what you'll add to your project. Once you add that to your project you can import the dependency "FBSDKCoreKit" as normal. I can remove this from the README (or feel free to open a pull request to do it :D )  since it is causing confusion and there really is not a strong reason to offer this going forward. Thanks!

**Comment by baskhulukhia** [comment]
@joesus Hello
I added FacebookCore in my package.swift dependencies and still can't import FBSDKCoreKit... do you know what the issue might be?..

> @lbfamous - if you look at Package.swift you'll see stuff like this:
> 
> ```
> .library(
>             name: "FacebookCore",
>             targets: ["FacebookCore"]
>         ),
> 
> ...
> 
> .target(
>             name: "FacebookCore",
>             dependencies: ["FBSDKCoreKit"],
>             path: "FBSDKCoreKit/FBSDKCoreKit/Swift"
>         ),
> ```
> 
> This means that we're defining the library as "FacebookCore" this is what you'll add to your project. Once you add that to your project you can import the dependency "FBSDKCoreKit" as normal. I can remove this from the README (or feel free to open a pull request to do it :D ) since it is causing confusion and there really is not a strong reason to offer this going forward. Thanks!
