### ISSUE TITLE
[FBSDKAppEventsUtility attributionID] called takes a lot of time

### ISSUE THREAD

**Issue by poetryfar** [facebook/facebook-ios-sdk#1602]
when  [FBSDKAppEventsUtility attributionID]  is called, it's takes a lot of time, because  the this method  use UIPasteboard (https://github.com/moshe/facebook-objc-sdk/blob/master/FBSDKCoreKit/FBSDKCoreKit/AppEvents/Internal/FBSDKAppEventsUtility.m). 
This issue will be  fixed ?

**Comment by dreamolight** [comment]
Hi @poetryfar, please use latest SDK from official repo (this one) which has removed the function.
