### ISSUE TITLE
How to restrict data use on a per-event basis in iOS 14?

### ISSUE THREAD

**Issue by revolter** [facebook/facebook-ios-sdk#1604]
According to the information that Facebook sent us:

> The updated Facebook SDK will also enable apps to send a flag to Facebook to restrict data use on a per-event basis. If advertisers decide not to send Facebook a flag indicating an iOS 14 event is opted-in for tracking, Facebook will restrict their use of that event.

_([Source](https://help.branch.io/using-branch/page/facebook-ios-14))_

But I only found out this API method:

https://github.com/facebook/facebook-ios-sdk/blob/a8f91201dca16da7a1850f5004a91c7326f1d0ee/FBSDKCoreKit/FBSDKCoreKit/FBSDKSettings.h#L190-L196

which seems to enable or disable tracking globally, for all the events.

So, how can you "restrict data use on a per-event basis"?

**Comment by revolter** [comment]
Still valid

**Comment by KylinChang** [comment]
Hi @revolter , in iOS14+ SDK will drop events if ATE(AdvertiserTrackingEnabled) is false and send events if ATE is true: https://developers.facebook.com/docs/app-events/guides/advertising-tracking-enabled/ . The "per-event basis" here actually means that the ATE flag is event level but not user level or app level.
