### ISSUE TITLE
Incorrect example code in documentation

### ISSUE THREAD

**Issue by revolter** [facebook/facebook-ios-sdk#1605]
[This page](https://developers.facebook.com/docs/marketing-api/app-event-api/#tracking_enabled) presents usage of `FBDynamicFrameworkLoader`, while that class' documentation states that "it is an internal class and not to be used by 3rd party developers".

What gives?

**Comment by Nisa-Nasi** [comment]
Please help i don’t know how to download facebook sdk 🙏🏻🙏🏻

Neath

**Comment by revolter** [comment]
@Nisa-Nasi, And what does that have to do with my issue?

**Comment by revolter** [comment]
Still valid

**Comment by jawwad** [comment]
Hey @revolter - Thanks for commenting to keep this issue open. I'm not really sure why the original code snipped was using the `FBDynamicFrameworkLoader` when it didn't need to but I've gone ahead and updated it to indicate that the value can just be obtained from the `Settings.shared.isAdvertiserTrackingEnabled` property. Thanks!
