### ISSUE TITLE
ld: symbol(s) not found for architecture x86_64 and arm64

### ISSUE THREAD

**Issue by uavinas** [facebook/facebook-ios-sdk#1606]
- I've updated to the latest released version of the SDK 8.2.0
- When adding the static framework and running in Xcode 12.2 I'm getting some errors which are related to an undefined symbol, symbol(s) not found for architecture x86_64 and arm64 when running in device and simulator 

## Environment
- Xcode Version: 12.2
- Language - Objective C
- Installation Platform & Verison: SDK 8.2.0 (Static framework)

## Build Settings
- Built setting is defined with STANDARD_ARCH
- Valid Archs also STANDARD_ARCH

The following are some issues that I'm getting when running via device and simulator.

<img width="870" alt="Screenshot 2021-01-08 at 09 17 53" src="https://user-images.githubusercontent.com/28798237/103972220-8dbd4a80-5192-11eb-8ff2-f0b11441e05e.png">
<img width="870" alt="Screenshot 2021-01-08 at 09 18 26" src="https://user-images.githubusercontent.com/28798237/103972223-8f870e00-5192-11eb-9a3f-2f4599007cc2.png">
<img width="870" alt="Screenshot 2021-01-08 at 09 18 05" src="https://user-images.githubusercontent.com/28798237/103972227-9150d180-5192-11eb-9d7f-babcb8522960.png">

What is the solution for this issue?

**Comment by joesus** [comment]
One possible solution is to include an empty Swift file so that the system will include the Swift runtime. We provide the Statically linked libraries for advanced use cases but generally you will have a much easier time using something like Swift Package Manager. Please let me know if including the Swift runtime solves this. Thanks!

**Comment by normanpauladkins** [comment]
KOn Jan 7, 2021 10:50 PM, uavinas <notifications@github.com> wrote:
I've updated to the latest released version of the SDK 8.2.0When adding the static framework and running in Xcode 12.2 I'm getting some errors which are related to an undefined symbol, symbol(s) not found for architecture x86_64 and arm64 when running in device and simulator
Environment

Xcode Version: 12.2

Language - Objective C

Installation Platform & Verison: SDK 8.2.0 (Static framework)

Built setting is defined with STANDARD_ARCH

Valid Archs also STANDARD_ARCH

The following are some issues that I'm getting when running via device and simulator.



What is the solution for this issue?

**Comment by uavinas** [comment]
> One possible solution is to include an empty Swift file so that the system will include the Swift runtime. We provide the Statically linked libraries for advanced use cases but generally you will have a much easier time using something like Swift Package Manager. Please let me know if including the Swift runtime solves this. Thanks!

Yeah it works thanks!

**Comment by xzwgithub** [comment]
> > One possible solution is to include an empty Swift file so that the system will include the Swift runtime. We provide the Statically linked libraries for advanced use cases but generally you will have a much easier time using something like Swift Package Manager. Please let me know if including the Swift runtime solves this. Thanks!
> 
> Yeah it works thanks!
I'm in the same situation as you. How did you solve it? I didn't understand the above

**Comment by uavinas** [comment]
> > One possible solution is to include an empty Swift file so that the system will include the Swift runtime. We provide the Statically linked libraries for advanced use cases but generally you will have a much easier time using something like Swift Package Manager. Please let me know if including the Swift runtime solves this. Thanks!
> 
> Yeah it works thanks!
> I'm in the same situation as you. How did you solve it? I didn't understand the above

Yeah, you need to create an empty Swift file in your project. 

<img width="728" alt="Screenshot 2021-01-22 at 11 51 19" src="https://user-images.githubusercontent.com/28798237/105454646-3649cf00-5ca8-11eb-9f54-e07778f1fc0c.png">

Ex: FacebookSdk.swift 

* After that add targets to your created swift file 
* Make sure library search path added 
* In the build settings please define the SWIFT_LANGUAGE_VERSION - 5.0 (xcode 12)

**Comment by xzwgithub** [comment]
> > > One possible solution is to include an empty Swift file so that the system will include the Swift runtime. We provide the Statically linked libraries for advanced use cases but generally you will have a much easier time using something like Swift Package Manager. Please let me know if including the Swift runtime solves this. Thanks!
> > 
> > 
> > Yeah it works thanks!
> > I'm in the same situation as you. How did you solve it? I didn't understand the above
> 
> Yeah, you need to create an empty Swift file in your project.
> 
> <img alt="Screenshot 2021-01-22 at 11 51 19" width="728" src="https://user-images.githubusercontent.com/28798237/105454646-3649cf00-5ca8-11eb-9f54-e07778f1fc0c.png">
> 
> Ex: FacebookSdk.swift
> 
> * After that add targets to your created swift file
> * Make sure library search path added
> * In the build settings please define the SWIFT_LANGUAGE_VERSION - 5.0 (xcode 12)

thank you，The problem has been solved，I did two steps，The first step is to create an empty swift file，The second step is to add the system dependency library Accelerate.framework
