### ISSUE TITLE
Feature Request: Please document what is limited login and do we need to use it. What could happen if we just use only classic login

### ISSUE THREAD

**Issue by Thaina** [facebook/facebook-ios-sdk#1613]
## Checklist

- [x] I've updated to the latest released version of the SDK
- [x] I've searched for existing feature requests on [GitHub issues](https://github.com/facebook/facebook-ios-sdk/issues)
- [x] I've read the [Code of Conduct](CODE_OF_CONDUCT.md)
- [x] I've given my issue the title: `Feature Request: [name of my feature request]`

## Goals

Current information about limited login is somehow vague. It just state that it could be used to limit information of user and given tokenID instead of access token. But how important about it? Somehow it related to ios14 but then how it will affected? Do we still able to force user to login with only classic login? Will apple force us developer to support limited login in our app?

All of this we don't know about and I don't understand the complication. Also instead of email and profile picture, my app would like to not care about that but care about user friend instead. Shouldn't there would be limited login that could only get friend list without any information instead?

## Expected Results

At least detailed documentation about what interaction ios would do about limited login. Screenshot of it in action for any root the user will interact with each login UI. Also the practice guidance or sample of what you would like to have us implement this feature in real app

## Code Samples & Details

```C#
// what UI we should make for calling this line?
FB.Mobile.LoginWithTrackingPreference(LoginTracking.LIMITED, scopes, "nonce123", this.HandleResult);
```

**Comment by joesus** [comment]
Hi!

> But how important about it?

This depends on your app's policies around accessing user data. 

> Somehow it related to ios14 but then how it will affected?

Can you elaborate?

> Do we still able to force user to login with only classic login? 

Yes. It is not a requirement to implement limited login. 

> Will apple force us developer to support limited login in our app?

I am not qualified to predict the future.

> Shouldn't there would be limited login that could only get friend list without any information instead?

It is not possible to get user friends using limited login. This is by design. 

> Screenshot of it in action for any root the user will interact with each login UI.

As far as UI is concerned. This is entirely up to you, assuming it adheres to the Facebook login terms of service, of course. Please play around with the feature in a sample app to get an idea of what possible experiences will look and feel like. 

Overall:
To read more about the limited login feature please read the documentation linked from the CHANGELOG. There is a lot more information there!

**Comment by Thaina** [comment]
@joesus I have read and actually try to look around as much as I can but overall is somehow vague. All of those answer you have response should be information somewhere in your official document but I can't find it

> As far as UI is concerned. This is entirely up to you

At least normally most of feature facebook ever had will have UI screenshot as sample. Surely we would implement our own but facebook still had sample anyway. I expect we should have the same for this feature

> > Somehow it related to ios14 but then how it will affected?

> Can you elaborate?

I am not sure but it seem there was some relation that we need to update facebook SDK for ios 14. I don't actually understand it clearly but there are info and blog post. Such as this blog > https://developers.facebook.com/blog/post/2020/10/29/preparing-our-partners-ios-14-latest-guidance-on-skadnetwork/

Is the limited login related to privacy or GDPR or something? Why it need to have? What scenario we really need it? This is the question of `how important it is?` and what we need to prepare for it or we could just not care about it, I don't know but because it came together with annoucement on tracking and ios14 so I feel some relation

**Comment by joesus** [comment]
From https://developers.facebook.com/docs/facebook-login/limited-login

> Limited Login offers a login path that implements steps designed to prevent the fact that a person used Facebook to log in to your app from being used to target advertising or measure advertising effectiveness.

**Comment by joesus** [comment]
> > Shouldn't there would be limited login that could only get friend list without any information instead?
> 
> It is not possible to get user friends using limited login. This is by design.

Update. It is now possible to get a list of  user friend identifiers. Please follow the [official docs](https://developers.facebook.com/docs/facebook-login/limited-login/ios) for the latest features. :D
