### ISSUE TITLE
“FBSDKCoreKit.framework” cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by francdn** [facebook/facebook-ios-sdk#1614]
I get this error when I try to run my app with the latest version (9.0.0) of the SDK on Mac Catalyst. 

“FBSDKCoreKit.framework” cannot be opened because the developer cannot be verified.

I am using the **xcframework**.

**Comment by francdn** [comment]
This problem is still happening with SDK 11.

**Comment by jawwad** [comment]
Hi @francdn - I'm going to close this out since the latest release should fix this issue. Please let us know if you are still running into issues. Thanks!
