### ISSUE TITLE
"Incompatible library version" when run App crash after Launch. version 9.0

### ISSUE THREAD

**Issue by hardik38737** [facebook/facebook-ios-sdk#1617]
- Xcode Version: `12.3`

Log :
dyld: Library not loaded: @rpath/FBSDKCoreKit.framework/FBSDKCoreKit
  Referenced from: ~/Library/Developer/CoreSimulator/Devices/28372F6B-6956-46B1-9493-28DE38A88F56/data/Containers/Bundle/Application/4F4A240B-4243-489E-BBCD-B40F40D7E72E/XXX.app/app Name
  Reason: Incompatible library version: App name requires version 1.0.0 or later, but FBSDKCoreKit provides version 0.0.0
  
Below is my pod file :

  platform :ios, '9.0'
target 'App name' do
use_frameworks!
pod 'SDWebImage', '~>3.8'
pod 'AFNetworking'
pod 'GoogleSignIn'
pod 'DXPopover', '~> 0.1.0'
pod 'Firebase/Performance'
pod 'Firebase/Auth'
pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'Firebase/DynamicLinks'
pod 'Firebase/RemoteConfig'
pod 'Firebase/Crashlytics'
pod 'Firebase/Analytics'
pod 'Google-Mobile-Ads-SDK'
pod 'IronSourceSDK'
pod 'FacebookSDK'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'GoogleMobileAdsMediationMoPub'
pod 'GoogleMobileAdsMediationFacebook'
pod 'IronSourceFacebookAdapter'
pod 'IronSourceTapjoyAdapter'
end

**Comment by iDevPro** [comment]
I have the same issue..
pod 'FacebookSDK'
pod 'FBSDKLoginKit'

**Comment by joesus** [comment]
Currently the pod 'FacebookSDK' is used for vending pre-built XCFrameworks. Your options are to either 

a) use the individual pods like:
```
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
```

b) use the aggregate pod:
```
pod 'FacebookSDK'
```

Trying to use both is not supported.

**Comment by hardik38737** [comment]
I  tried to use 
pod 'FacebookSDK'

is also crash the app.

**Comment by joesus** [comment]
> I  tried to use 
> 
> pod 'FacebookSDK'
> 
> 
> 
> is also crash the app.

Please open a new task with a detailed description and repro instructions. This comment does not provide me with enough information to help you.
