### ISSUE TITLE
Feature Request: Setting AdvertiserTrackingEnabled to false shouldn't block all events from being tracked

### ISSUE THREAD

**Issue by pawziu** [facebook/facebook-ios-sdk#1619]
## Checklist

- [x] I've updated to the latest released version of the SDK
- [x] I've searched for existing feature requests on [GitHub issues](https://github.com/facebook/facebook-ios-sdk/issues)
- [x] I've read the [Code of Conduct](CODE_OF_CONDUCT.md)
- [x] I've given my issue the title: `Feature Request: [name of my feature request]`

## Goals

I want to be able to receive all events (automatic and custom) from the application just for analytics purposes, without sharing it with advertisers (as the name `AdvertiserTrackingEnabled` suggests).

## Expected Results

After setting `setAdvertiserTrackingEnabled` to `false` all events should still be sent from iOS SDK to Facebook, but they shouldn't be used for advertising. 

## Actual Results

Using Facebook iOS SDK v.`9.0.0`, after setting `setAdvertiserTrackingEnabled` to `false`, events are not being tracked at all.

**Comment by joesus** [comment]
Are you positive that events are firing? v9 make changes to auto-initialization so it's possible the events are not firing due to this. You should see logging in your developer console related to this.

**Comment by pawziu** [comment]
I initialize SDK manually (using `ApplicationDelegate.initializeSDK(nil)`, according to new documentation) and log the events. With `setAdvertiserTrackingEnabled` set to `true` events are being sent (I can see it in logs and in the web console), whereas when set to `false` no events are neither logged nor visible on FB console.

**Comment by jawwad** [comment]
Hi @pawziu - Are you still encountering this issue or were you able to figure it out?

**Comment by jawwad** [comment]
Hi @pawziu - Since we haven't heard back from you on this I'm going to close the issue out. Feel free to re-open if you are still encountering the issue. Thanks!
