### ISSUE TITLE
Feature Request: FBSDKCoreKit without ASIdentifierManager

### ISSUE THREAD

**Issue by ghost** [facebook/facebook-ios-sdk#1637]
## Checklist

- [x] I've updated to the latest released version of the SDK
- [x] I've searched for existing feature requests on [GitHub issues](https://github.com/facebook/facebook-ios-sdk/issues)
- [x] I've read the [Code of Conduct](CODE_OF_CONDUCT.md)
- [x] I've given my issue the title: `Feature Request: FBSDKCoreKit without ASIdentifierManager`

## Goals

We have a kids category application on AppStore. Recently we have added **just FBSDK** for some statics to app, but Apple rejects the new build of out application

## Expected Results

Approvement by Apple

## Rejection Details

```
Guideline 1.3 - Safety - Kids Category

We noticed that your Kids Category app includes analytics, advertising and collects, transmits, or has the ability to share personal information or device information with third parties. 

Your app includes the following feature(s), contrary to guideline 1.3 of the App Store Review Guidelines:

Third-party analytics or third-party advertising with the ability to collect, transmit or share identifiable information, including, for example, IDFA. Specifically, we found that your app references the ASIdentifierManager API, which provides access to a user's IDFA, in the following location(s) in your binary:

• Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit

To resolve this issue, it would be appropriate to remove all instances of “ASIdentifierManager” from your app, even if they are not utilized in your app's functionality.

Next Steps

To resolve this issue, please remove this functionality or revise your app so that no personally identifiable information or device information is sent to third parties.
```

**Comment by korober** [comment]
exactly same problem :(

**Comment by scott-thrillist** [comment]
Our iOS kids app keeps rejected with this same message. We will have to strip the FB SDK until further notice.

**Comment by snorrsi** [comment]
Can you please wrap all AdSupport.h and ASIdentifierManager usage in conditional code, it can be on by default as to not to break current behaviour but this really needs to be done.

**Comment by RomualdPercereau** [comment]
This issue is still active, it could be implemented like firebase did with **RNFirebaseAnalyticsWithoutAdIdSupport**  https://rnfirebase.io/analytics/usage#disable-ad-id-usage-on-ios ?

**Comment by LugonjaAleksandar** [comment]
How come that no one is assigned or that anyone from Facebook team responsible for this repo haven't recognised a big SDK flaw since Feb 5th? This is going to be a 1 year old problem for the entire App Store category of the apps, and people are unable to unitise tools for marketing due to this issue, resulting in wasted campaign money with 0 metrics for app instals for example.

**Comment by LugonjaAleksandar** [comment]
@jawwad  @joesus @tianqibt @KylinChang @dreamolight  Please if you can assign someone to this task and let's unblock it after 0 activity on it from FB team. This task is literally now blocking developers of one major app category on App Store, from using your own company's marketing tools and understanding how metrics are doing after promoting on your own platform and paying you handsome money for the promotion.

**Comment by LugonjaAleksandar** [comment]
It's a feature request that hasn't been progressing. So no time to delete it, time to push and develop it since the community needs it. ;)

**Comment by ivensdenner** [comment]
Any news on this yet? I need to add the SDK to my kids app to track conversion but Apple won't approved as it is right now.

**Comment by snorrsi** [comment]
@ivensdenner sadly FB hasn’t done anything regarding this. I use my own version, you can check it out at https://github.com/snorrsi/facebook-ios-sdk/blob/v14.1-noidfa/

You need to download the podspec for FBSDKCoreKit, and rather than using version number in Xcode Podfile .. use podspec: “FBSDKCoreKit.podspec”

**Comment by ivensdenner** [comment]
What a bummer ☹️. Thanks for the reply @snorrsi , but it looks like your fork is private.

**Comment by snorrsi** [comment]
@ivensdenner yeah, forgot to remove the blob part .. anyhow, the zip file the podspec file is referring to is created by compiling with Xcode. Sadly Facebook has no idea how, but if I remember correctly I just opened Xcode, maybe after running some setup script and then making sure to open the workspace one and build the FBSDKCoreKit target
The podfile then has to include line such as
  pod 'FBSDKCoreKit', :podspec => 'FBSDKCoreKit.podspec'

**Comment by oferbXR** [comment]
@snorrsi 
can you plz post a more detailed guide on how to build the FBSDKCoreKit.podspec and more importantly how to use it in a unity project ?
