### ISSUE TITLE
Question about IOS APP install reports 14.5

### ISSUE THREAD

**Issue by berseck** [facebook/facebook-ios-sdk#1652]
I got the APP with everything updated with the latest API for IOS and Android, also have all plist enabled and i'm requesting all the permissions with the following code:

IOS SDK: 9.0.1
ANDROID: 8.2.0 

```
- (void)setAutoLogAppEventsEnabled:(CDVInvokedUrlCommand *)command {
    [ATTrackingManager requestTrackingAuthorizationWithCompletionHandler:^(ATTrackingManagerAuthorizationStatus status) {
        if(status == ATTrackingManagerAuthorizationStatusAuthorized) {
            NSString *UUIDads = [[[ASIdentifierManager sharedManager] advertisingIdentifier] UUIDString];
            [FBSDKSettings setAutoLogAppEventsEnabled:YES];
            [FBSDKSettings setAdvertiserTrackingEnabled:YES];
            [FBSDKSettings setAdvertiserIDCollectionEnabled:YES];
        } else {
            [FBSDKSettings setAutoLogAppEventsEnabled:NO];
            [FBSDKSettings setAdvertiserTrackingEnabled:NO];
            [FBSDKSettings setAdvertiserIDCollectionEnabled:NO];
        }
        CDVPluginResult *res = [CDVPluginResult resultWithStatus:CDVCommandStatus_OK];
        [self.commandDelegate sendPluginResult:res callbackId:command.callbackId];
    }];
}
```

Here is my plist:
```
	<key>FacebookAdvertiserIDCollectionEnabled</key>
	<true/>
	<key>FacebookAppID</key>
	<string>XXXX</string>
	<key>FacebookAutoLogAppEventsEnabled</key>
	<true/>
	<key>FacebookDisplayName</key>
	<string>My Test APP</string>
	<key>FacebookHybridAppEvents</key>
	<string>false</string>
	<key>FacebookUrlSchemeSuffix</key>
	<string></string>
	<key>SKAdNetworkItems</key>
	<array>
		<dict>
			<key>SKAdNetworkIdentifier</key>
			<string>v9wttpbfk9.skadnetwork</string>
		</dict>
		<dict>
			<key>SKAdNetworkIdentifier</key>
			<string>n38lu8286q.skadnetwork</string>
		</dict>
	</array>
```

I know this might be an overkill but it works for 14.4 and lower.
But on 14.5 profile even using xcode 12.5 I get 0 reports for new installations.

If I just install exact same app in a phone with 14.4 it will report the install right away.

Am I missing anything?

As far as I could get that's all I need to set from the system and that's what is on the documentation.
It doesn't change anything if I set FacebookAutoLogAppEventsEnabled to false then enable when user agrees with it.

I would appreciate help doing this update if possible.

**Comment by joesus** [comment]
Are you initializing the SDK before sending events? Is there any console output? Can you attach a sample project?

Also, our designated developer support team -- https://developers.facebook.com/support/bugs/ -- might be able to help resolve this more quickly. Thanks!

**Comment by berseck** [comment]
I'm actually updating my code based on this plugin from Cordova:
[https://github.com/cordova-plugin-facebook-connect/cordova-plugin-facebook-connect](https://github.com/cordova-plugin-facebook-connect/cordova-plugin-facebook-connect)

All as far as I know that need to be done was change the SDKs + add all the proper plists and the code I have mention on previous comment.

Following all the documentation of FB they don't say anything about changing initialization or anything, I might be wrong, but that is what I got so far.

Thanks!

**Comment by berseck** [comment]
So indeed @joesus was correct despite fact that in this documentation here: [https://developers.facebook.com/docs/app-events/guides/advertising-tracking-enabled](https://developers.facebook.com/docs/app-events/guides/advertising-tracking-enabled) has 0 reference to the initialization process.

In the GDPR [https://developers.facebook.com/docs/app-events/gdpr-compliance](https://developers.facebook.com/docs/app-events/gdpr-compliance) one that has a method that doesn't exist anymore `setAutoInitEnabled` has actually a hint that you need to after change the configurations initialize the SDK with the following command:

```
[FBSDKApplicationDelegate initializeSDK:nil];
```

So after many trials here and there, I finally found out this part of the code by reading the entire documentation (even things that weren't related to what I was doing) to update that in my code and make it work.

So if you come here... by any means with same issue.
This here:
```
- (void)setAutoLogAppEventsEnabled:(CDVInvokedUrlCommand *)command {
    [ATTrackingManager requestTrackingAuthorizationWithCompletionHandler:^(ATTrackingManagerAuthorizationStatus status) {
        if(status == ATTrackingManagerAuthorizationStatusAuthorized) {
            NSString *UUIDads = [[[ASIdentifierManager sharedManager] advertisingIdentifier] UUIDString];
            [FBSDKSettings setAutoLogAppEventsEnabled:YES];
            [FBSDKSettings setAdvertiserTrackingEnabled:YES];
            [FBSDKSettings setAdvertiserIDCollectionEnabled:YES];
            [FBSDKApplicationDelegate initializeSDK:nil];
        } else {
            [FBSDKSettings setAutoLogAppEventsEnabled:NO];
            [FBSDKSettings setAdvertiserTrackingEnabled:NO];
            [FBSDKSettings setAdvertiserIDCollectionEnabled:NO];
        }
    }];
}
```

Is how you ask for the permissions and initialize the SDK after you requested it, only if the user had actually agreed with you enabling that.

Hope this help someone in the future looking clueless like I did why his code wasn't working.

Thanks,

**Comment by joesus** [comment]
Sounds like this is resolved. Thanks!

**Comment by xiepaul888** [comment]
I ran into the same problem,also i have do like this,but it did not work, what should i do else？

[ATTrackingManager requestTrackingAuthorizationWithCompletionHandler:^(ATTrackingManagerAuthorizationStatus status) {
        if(status == ATTrackingManagerAuthorizationStatusAuthorized) {
            NSString *UUIDads = [[[ASIdentifierManager sharedManager] advertisingIdentifier] UUIDString];
            [FBSDKSettings setAutoLogAppEventsEnabled:YES];
            [FBSDKSettings setAdvertiserTrackingEnabled:YES];
            [FBSDKSettings setAdvertiserIDCollectionEnabled:YES];
            //Initialize here after turning all tracks on.
            [FBSDKApplicationDelegate initializeSDK:nil];
        } else {
            [FBSDKSettings setAutoLogAppEventsEnabled:NO];
            [FBSDKSettings setAdvertiserTrackingEnabled:NO];
            [FBSDKSettings setAdvertiserIDCollectionEnabled:NO];
        }
    }];

**Comment by berseck** [comment]
Yeah same code not even a comma changed and after a week it's not working anymore after the release of xcode 12.5.2

**Comment by joesus** [comment]
> Yeah same code not even a comma changed and after a week it's not working anymore after the release of xcode 12.5 beta 2

It sounds like it was working and then stopped working with 12.5 Beta 2. I would recommend either uploading a reproducible sample or bringing this to our designated developer support team -- https://developers.facebook.com/support/bugs/ . The snippets in the descriptions are not enough to debug this.

**Comment by joesus** [comment]
> //Initialize here after turning all tracks on.
> [FBSDKApplicationDelegate initializeSDK:nil];

You need to do this first. See our getting started docs https://developers.facebook.com/docs/app-events/getting-started-app-events-ios for how / when to initialize the SDK.
