### ISSUE TITLE
FBSDK 9.0.1 Crash

### ISSUE THREAD

**Issue by cs571393** [facebook/facebook-ios-sdk#1656]
- Xcode Version: `11.2`
- Swift Version: Swift 5
- Installation Platform & Verison: Cocoapods version `1.10.0`
![QQ20210218-104327](https://user-images.githubusercontent.com/19399512/108297412-2a352c80-71d6-11eb-8e63-3624d1e89b60.png)

**Comment by joesus** [comment]
Are there console logs? A sample project? Please provide steps to reproduce the crash. Thanks!

**Comment by nitinKareer** [comment]
Facing same issue in my app too after upgrading to 9.0 from 8.2.0. It crashes on first launch, remove the app from task manager, initialize the app and it crashes.

Please provide the solution asap.

**Comment by cs571393** [comment]
@joesus To reproduce the step, just initialize the FBSDK method in the AppDelegate and it crashes

    [[FBSDKApplicationDelegate sharedInstance] application:application didFinishLaunchingWithOptions:launchOptions];

**Comment by pawlowskim** [comment]
Same here. We are using flutter wrapper, but under the hood there is FBSDK. We were using 8.0.0, which works fine. After updating to 9.0.0 or 9.0.1 app crashes on first app start. Easily to trigger by installing the app (when it's not yet installed) or upgrading previous version of the app.

**Comment by joesus** [comment]
My first guess is that this has to do with potentially calling something from the SDK before it is initialized. We removed autoinitialization in v9.0 and fixed a minor bug related to that in v9.1. Please check the release notes for details. 

Also, this is not reproducible for me so please either provide a sample app to reproduce the issue or file a ticket with our designated developer support team -- https://developers.facebook.com/support/bugs/ - and we can get this appropriate triaged and addressed. Thanks!

**Comment by cs571393** [comment]
[fbtest.zip](https://github.com/facebook/facebook-ios-sdk/files/6014269/fbtest.zip)
@joesus This is a demo of Crash

**Comment by seanLee** [comment]
Crash in this method ```[FBSDKLogger registerStringToReplace:replaceWith]``` and this line  ```[g_stringsToReplace setValue:replaceWith forKey:replace]``` while update  Facebook SDK to 9.0.0.It seems that every time update the Facebook SDK,some user would get crashed randomly.

**Comment by freesuraj** [comment]
For me the interim solution was not to set the `AppEvents.userID` in the first pass.

**Comment by nitinKareer** [comment]
Any solution or update in fbsdk to get rid of this crash ? I don't want to change the code or flow as @freesuraj suggested. Everything working correctly with 8.2.0 version.

**Comment by joesus** [comment]
You should not call anything in the SDK without it being initialized. In the sample project you should fetch the deferred deep link after implicitly initializing the SDK with `ApplicationDelegate application:didFinishLaunchingWithOptions:`.

Please see the release notes for 9.0.0 for more details on why this is the case. Thanks!

**Comment by nitinKareer** [comment]
@joesus didnt get you. Can you show the example please ?

**Comment by GWesley** [comment]
![image](https://user-images.githubusercontent.com/2985638/108762743-78bc3100-751e-11eb-9c74-100097983dde.png)
![image](https://user-images.githubusercontent.com/2985638/108762832-91c4e200-751e-11eb-8665-29f588dcfcd8.png)

**Comment by joesus** [comment]
> @joesus didnt get you. Can you show the example please ?

In the OP's sample project. The two lines in AppDelegate should be reversed.

**Comment by nitinKareer** [comment]
@joesus I didn't use any thing in appdelegate file.

I have singleton class where I am using fbsdk like this only.

        **AppEvents.logEvent(.init(eventName),parameters: newBundle)**

_And it is working fine with 8.2.0 version_

Please let me know where am I doing wrong.

I didn't write single code in appdelegate file related to fbsdk

**Comment by nitinKareer** [comment]
@joesus I am not finding any method to initialize fbsdk in appdelegate in swift. Please help me

**Comment by nitinKareer** [comment]
@joesus I found the solution for swift. Please mention it in docs as well...

@GWesley @freesuraj @cs571393 
func application(_ application: UIApplication,
                     didFinishLaunchingWithOptions launchOptions:
        [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        
        //initializing fbsdk, because autoinitializing in newer version removed. Now, developers has to do it own.
        ApplicationDelegate.shared.application(application, didFinishLaunchingWithOptions: launchOptions)

//remaining code

return true
    }
    
    //objective c
    
    - (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
    
    [[FBSDKApplicationDelegate sharedInstance] application:application didFinishLaunchingWithOptions:launchOptions];
    //remaining code

    return YES;
}

**Comment by joesus** [comment]
Thanks for the feedback! This is mentioned in the getting started docs under step 3. https://developers.facebook.com/docs/ios/getting-started/

It is also mentioned in the changelog for 9.0.0 https://github.com/facebook/facebook-ios-sdk/blob/master/CHANGELOG.md#removed
