### ISSUE TITLE
dyld: Library not loaded: @rpath/FBSDKCoreKit.framework/FBSDKCoreKit

### ISSUE THREAD

**Issue by pomegra** [facebook/facebook-ios-sdk#1662]
dyld: Library not loaded: @rpath/FBSDKCoreKit.framework/FBSDKCoreKit
  Referenced from: /private/var/containers/Bundle/Application/3925F7B6-0757-4A50-9625-DB4DE0336DC4/ChargeBolt.app/ChargeBolt
  Reason: Incompatible library version: ChargeBolt requires version 1.0.0 or later, but FBSDKCoreKit provides version 0.0.0
dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/GPUTools.framework/libglInterpose.dylib:/usr/lib/libMTLCapture.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib

**Comment by joesus** [comment]
There is not enough information here to help debug the issue. Please open a new issue that follows the template or report this to our designated developer support team -- https://developers.facebook.com/support/bugs/ -- as this will help us get more information and resolve it more quickly.
