### ISSUE TITLE
Couldn't Receive Launch/Install Events on iOS 14.5 beta2

### ISSUE THREAD

**Issue by xiepaul888** [facebook/facebook-ios-sdk#1668]
On iOS 14.5 , i have set this API for true(Tracking authorization has been obtained):

```
 [FBSDKSettings setAutoLogAppEventsEnabled:YES];
 [FBSDKSettings setAdvertiserTrackingEnabled:YES];
 [FBSDKSettings setAdvertiserIDCollectionEnabled:YES];
 [FBSDKApplicationDelegate initializeSDK:nil];

```
 but i didn't receive Launch/Install Events at the test-event panel, and i can receive it at ios 14.4 or lower,

**Comment by joesus** [comment]
Thanks for reaching out to us with this issue! Unfortunately, there is not enough information included here to help debug the issue further. As a result, we are closing this issue at this time. 

Please open a new issue using the Github issue template and be sure to include the requested information to help us debug the issue further OR report this to our designated developer support team here:  https://developers.facebook.com/support/bugs/
