### ISSUE TITLE
Guidance on App Tracking Transparency changes coming in iOS 14.5

### ISSUE THREAD

**Issue by CorbinMontague** [facebook/facebook-ios-sdk#1671]
Hello! I'm looking for some guidance around [the App Tracking Transparency (ATT) changes coming in iOS 14.5](https://developer.apple.com/app-store/user-privacy-and-data-use/) and how they affect developers who leverage the FB SDK. I've read FB's blogs on preparing for these changes along with documentation on the new Limited Facebook Login, but still have some outstanding questions:
- Do all developers using the FB SDK for login purposes need to support the new Limited Facebook Login in some capacity (in situations where they either don't show the ATT prompt at all, or the user declines to share their data when the ATT prompt is displayed)? The docs make it sound like the Classic Facebook Login uses user data for the purposes of targeted ads (which would violate the new ATT policies from Apple afaik). Does that mean that Classic Facebook Login is only usable if the developer has shown the user the ATT prompt and they have accepted?
- I see three major settings in the docs that look like they may have an impact on if a developer's usage of the FB SDK adheres to Apple's new ATT policies in iOS 14.5:
```
[FBSDKSettings setAutoLogAppEventsEnabled:NO];
[FBSDKSettings setAdvertiserTrackingEnabled:NO];
[FBSDKSettings setAdvertiserIDCollectionEnabled:NO];
```
Do all three of these need to be set to false in the case where a developer doesn't want to present the ATT prompt, or it has been presented and declined by the user? My guess would be that developers only need to disable advertiser tracking, but I wanted to confirm.

Thanks!

**Comment by sintylapse** [comment]
hey @CorbinMontague , did you find the answer on that matter?

**Comment by kenji21** [comment]
For reference, when using sdk at version 12.x (to be called in a viewDidLoad of a viewController):

```
    func _askForTrackingIfNeeded() {
        if #available(iOS 14, *) {
            let status = ATTrackingManager.trackingAuthorizationStatus
            if status == .notDetermined {
                DispatchQueue.main.asyncAfter(deadline: .now() + 0.1) {
                    ATTrackingManager.requestTrackingAuthorization { status in
                        switch status {
                        case .authorized:
                            // Optionally, log an event when the user accepts.
                            FBSDKCoreKit.Settings.shared.isAdvertiserIDCollectionEnabled = true
                            FBSDKCoreKit.Settings.shared.isAdvertiserTrackingEnabled = true
                            FBSDKCoreKit.Settings.shared.isAutoLogAppEventsEnabled = true
                        case _:
                            // Optionally, log an event here with the rejected value.
                            break
                        }
                    }
                }
            }
        }
    }
```

and in the AppDelegate `application:didFinishLaunchingWithOptions:` method:

```
        if #available(iOS 14, *) {
            if ATTrackingManager.trackingAuthorizationStatus != .authorized {
                FBSDKCoreKit.Settings.shared.isAdvertiserIDCollectionEnabled = false
                FBSDKCoreKit.Settings.shared.isAdvertiserTrackingEnabled = false
                FBSDKCoreKit.Settings.shared.isAutoLogAppEventsEnabled = false
            }
        }
        FBSDKCoreKit.ApplicationDelegate.shared.application(application, didFinishLaunchingWithOptions: launchOptions)
```
