### ISSUE TITLE
why Facebook SDK 9.0.1 Statistical inaccuracy?

### ISSUE THREAD

**Issue by SuyChen** [facebook/facebook-ios-sdk#1677]

**Comment by joesus** [comment]
Thanks for reaching out to us with this issue! Unfortunately, there is not enough information included here to help debug the issue further. As a result, we are closing this issue at this time. 

Please open a new issue using the Github issue template and be sure to include the requested information to help us debug the issue further OR report this to our designated developer support team here:  https://developers.facebook.com/support/bugs/
