### ISSUE TITLE
'FBSDKLoginKit/FBSDKLoginKit.h' file not found

### ISSUE THREAD

**Issue by premkumarsepuri** [facebook/facebook-ios-sdk#1685]
## Checklist
Actually im install Facebook pods in objective c. but im facing the error  'FBSDKLoginKit/FBSDKLoginKit.h' file not found. in the project while simulating 

im using below pods

pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'

with Xcode 11.2 and objective c 
![Screenshot 2021-03-11 at 9 03 38 PM](https://user-images.githubusercontent.com/44166456/110829065-bad6c800-82bd-11eb-81a4-4ed6ce36f991.png)

**Comment by joesus** [comment]
It's too hard to know if this is an issue with CocoaPods or the SDK or the App itself. Possibly try importing FBSDKCoreKit first? You can also try using `@import` syntax. Hope that helps. Please include a reproducible sample OR file a but with our developer support team at here:  https://developers.facebook.com/support/bugs/

Thanks!
