### ISSUE TITLE
framework not found FBSDKCoreKit

### ISSUE THREAD

**Issue by GaneshShetty951** [facebook/facebook-ios-sdk#1695]
i have added the framework through swift packages.

![Screenshot 2021-03-22 at 11 09 03 PM](https://user-images.githubusercontent.com/15211105/112033791-cea6e780-8b63-11eb-960e-d0922afde039.png)
![Screenshot 2021-03-22 at 11 09 27 PM](https://user-images.githubusercontent.com/15211105/112033816-d4043200-8b63-11eb-9082-5c94b199ea69.png)

- Xcode Version: `12.3`
- Swift Version: `5.3.2` (if issue is Swift related)

**Comment by GaneshShetty951** [comment]
Tried pod install now and I am getting the same error

![Screenshot 2021-03-23 at 5 54 46 PM](https://user-images.githubusercontent.com/15211105/112148945-7a077900-8c04-11eb-86d4-e9c9746aa59e.png)

**Comment by LuYu001** [comment]
I use cocoapods，after update 9.1.0,
get this issue, any update here？

**Comment by victorBaro** [comment]
Same error using SPM

**Comment by victorBaro** [comment]
I noticed that in `other Linker Flags` for both configurations (debug & release), FBSDKCoreKit, login and sharekit were still there (we used to have them when importing via Cocoapods).
Removing those values fixed the issue for me. I hope this helps.
![Screen Shot 2021-04-28 at 2 24 33 PM](https://user-images.githubusercontent.com/994334/116474959-058caf00-a82e-11eb-8552-e9feb3ca7715.png)

**Comment by joesus** [comment]
Thanks for reaching out to us with this issue! Unfortunately, there is not enough information included here to help debug the issue further. As a result, we are closing this issue at this time. 

Please open a new issue using the Github issue template and be sure to include the requested information to help us debug the issue further OR report this to our designated developer support team here:  https://developers.facebook.com/support/bugs/
