### ISSUE TITLE
App crashing in FBSDKCoreKit

### ISSUE THREAD

**Issue by hieunetacom** [facebook/facebook-ios-sdk#1699]
Hi admin,

I found the issue in my app when tracking event by FBSDKCoreKit,
Version: 9.1.0
Could you pls double-check it?

 Thanks!

<img width="808" alt="Screen Shot 2021-03-26 at 09 17 26" src="https://user-images.githubusercontent.com/74446123/112567997-5d419000-8e14-11eb-889e-5b19d5c27be0.png">

**Comment by jawwad** [comment]
Hi @hieunetacom - Could you update to v11.1.0 and see if you are still encountering the issue?

**Comment by jawwad** [comment]
Hi @hieunetacom - Since this issue is a few months old and I haven't heard back on if you are still encountering the issue, I'm going to go ahead and close it out. If you are still encountering the issue on the latest version of the SDK please feel free to open another issue. Thanks!

**Comment by buivanhieu2105** [comment]
Hi @jawwad, this issue seem fixed on the latest version of the SDK
Thanks for your support!
