### ISSUE TITLE
User keep getting connection error

### ISSUE THREAD

**Issue by cstromme** [facebook/facebook-ios-sdk#17]
One of my users keep getting connections errors when starting the app and doing a authorize:

Says he gets "error ref. #7.e1d434d.1282759386.0"

He can access touch.facebook.com, m.facebook.com and https://graph.facebook.com just fine from Mobile Safari. Any idea what might be causing this?

**Comment by MohammadAliKhan** [comment]
Did anybody got mutual friend list...?????
