### ISSUE TITLE
Feature Request: Get a better understanding how Limited Login works

### ISSUE THREAD

**Issue by johanthorell** [facebook/facebook-ios-sdk#1701]
## Checklist

- [x] I've updated to the latest released version of the SDK
- [x] I've searched for existing feature requests on [GitHub issues](https://github.com/facebook/facebook-ios-sdk/issues)
- [x] I've read the [Code of Conduct](CODE_OF_CONDUCT.md)
- [x] I've given my issue the title: `Feature Request: [name of my feature request]`

## Goals
Get a better understanding how Limited Login works.
## Expected Results
Get a better understanding how Limited Login works.
## Code Samples & Details
I’ve read through the [docs](https://developers.facebook.com/docs/facebook-login/limited-login/ios) and all that it states is that we can pass the OIDC token + a nonce to our backend to verify an authentication attempt, but there’s nothing in the documentation in regards to how long this token is valid, if it’s possible to refresh it (not sure if this is a valid use case?), or if we should check that it exists/validate it when the app starts.

**Comment by BrentMifsud** [comment]
the OIDC token is a base64 encoded string:

here's a decoded sample from one of the test users we generated:

```
{
 "iss": "https://facebook.com",
 "aud": "530053863835233",
 "sub": "104997728422575",
 "iat": 1620242973,
 "exp": 1620246573,
 "jti": "V4qN.f10c46d1b8eea12b795c64b4d65c293a6834d05656f0f8c8ea6ad1eb6f9902b9",
 "nonce": "889F0BCC-66AB-41F8-9BB7-DE9AA8B35F9A",
 "email": "ietgkdcrbx_1620235099@tfbnw.net",
 "user_birthday": "05/14/1984",
 "name": "Dick Alfgcgjddehaj Goldmanman",
 "picture": "https://scontent.fykz1-1.fna.fbcdn.net/v/t1.30497-1/cp0/e15/q65/c29.0.100.100a/p100x100/84628273_176159830277856_972693363922829312_n.jpg?_nc_cat=1&ccb=1-3&_nc_sid=12b3be&efg=eyJpIjoidCJ9&_nc_ohc=luNWA412uOgAX_bvtBs&_nc_ht=scontent.fykz1-1.fna&tp=5&oh=f89d9e2af5c503858ae31c63f4ed97a2&oe=60BA7483"
}
```

**Comment by SargeKhan** [comment]
Regarding the decrypted OIDC token: How can I get the facebook Id of the user?

**Comment by ppansy** [comment]
@johanthorell Thanks for your feedback. Please checkout our documentation on how to validate ID Token:
https://developers.facebook.com/docs/facebook-login/limited-login/token/validating
You should only use the ID token for authentication purposes within the expiration period. However, user's authentication status remains active even after the token is expired.

**Comment by ppansy** [comment]
> Regarding the decrypted OIDC token: How can I get the facebook Id of the user?

Hey, user ID will be available through `Profile.current.userID` or the "sub" claims from the decoded ID token.

**Comment by jawwad** [comment]
Hi @SargeKhan - I believe @ppansy has addressed your questions on this. If you still need assistance on this please feel free to comment or re-open this. Thanks!
