### ISSUE TITLE
error: could not build Objective-C module 'FBSDKLoginKit'

### ISSUE THREAD

**Issue by peterkuch** [facebook/facebook-ios-sdk#1702]
Integrate SPD not work for latest version.  How can fix it?
<img width="1127" alt="Screen Shot 2021-03-26 at 4 32 44 PM" src="https://user-images.githubusercontent.com/14107698/112616685-9d296700-8e56-11eb-896f-3a2c62b88bb5.png">
<img width="1119" alt="Screen Shot 2021-03-26 at 4 33 02 PM" src="https://user-images.githubusercontent.com/14107698/112616713-a3b7de80-8e56-11eb-8b1f-7022bd36d7ea.png">

**Comment by joesus** [comment]
There is not enough information to help debug. Please follow the template.
