### ISSUE TITLE
setAdvertiserTrackingEnabled method not found on class FBSDKSettings

### ISSUE THREAD

**Issue by meoz** [facebook/facebook-ios-sdk#1705]
As  the documentation states on Starting with iOS 14, you will need to set AdvertiserTrackingEnabled and log each time you give a device permission to share data with Facebook.
https://developers.facebook.com/docs/app-events/guides/advertising-tracking-enabled

Using Objective-C 
// Set AdvertiserTrackingEnabled to YES if a device provides consent
[FBSDKSettings setAdvertiserTrackingEnabled:YES];

Issue is that FBSDKSettings does not have a class method for selector 'setAdvertiserTrackingEnabled:' 

Imported libraries:
#import <Firebase/Firebase.h>
#import <FBSDKCoreKit/FBSDKCoreKit.h>
#import <FBSDKCoreKit/FBSDKSettings.h>
#import <FBAudienceNetwork/FBAdSettings.h>
#import <FBAudienceNetwork/FBAudienceNetwork.h>

Installed PODS

 FacebookSDK (5.15.1):
    - FacebookSDK/CoreKit (= 5.15.1)
    - FacebookSDK/MarketingKit (= 5.15.1)
  - FacebookSDK/CoreKit (5.15.1):
    - FBSDKCoreKit (~> 5.0)
  - FacebookSDK/LoginKit (5.15.1):
    - FacebookSDK/CoreKit
    - FBSDKLoginKit (~> 5.0)
  - FacebookSDK/MarketingKit (5.15.1):
    - FacebookSDK/CoreKit
    - FBSDKMarketingKit (~> 5.0)
  - FacebookSDK/PlacesKit (5.15.1):
    - FacebookSDK/CoreKit
    - FBSDKPlacesKit (~> 5.0)
  - FacebookSDK/ShareKit (5.15.1):
    - FacebookSDK/CoreKit
    - FBSDKShareKit (~> 5.0)
  - FBAudienceNetwork (5.10.1):
    - FBSDKCoreKit/Basics (>= 5.6.0)
  - FBSDKCoreKit (5.15.1):
    - FBSDKCoreKit/Basics (= 5.15.1)
    - FBSDKCoreKit/Core (= 5.15.1)
  - FBSDKCoreKit/Basics (5.15.1)
  - FBSDKCoreKit/Core (5.15.1):
    - FBSDKCoreKit/Basics
  - FBSDKLoginKit (5.15.1):
    - FBSDKLoginKit/Login (= 5.15.1)
  - FBSDKLoginKit/Login (5.15.1):
    - FBSDKCoreKit (~> 5.0)
  - FBSDKMarketingKit (5.14.0):
    - FBSDKCoreKit (~> 5.5)
  - FBSDKMessengerShareKit (1.3.2)
  - FBSDKPlacesKit (5.15.0):
    - FBSDKCoreKit (~> 5.0)
  - FBSDKShareKit (5.15.1):
    - FBSDKShareKit/Share (= 5.15.1)
  - FBSDKShareKit/Share (5.15.1):
    - FBSDKCoreKit (~> 5.0)

**Comment by linmx0130** [comment]
Hi @meoz, thanks for raising the issue. `setAdvertiserTrackingEnabled` is introduced in newer versions.
Would you mind upgrading FBSDK version to v9+, which is actively supported now?

**Comment by meoz** [comment]
@linmx0130 thanks for replying. Any pointers how I would install v9 with CocoaPods ?
I'm using 'pod 'FacebookSDK'  but that would only install version 5.15

**Comment by linmx0130** [comment]
@meoz Please follow the instructions on https://developers.facebook.com/docs/ios/use-cocoapods

**Comment by 8secz-johndpope** [comment]
this link is wrong as of 27th May 2021 
 -  https://developers.facebook.com/docs/ios/use-cocoapods 
it's saying to use 

pod 'FacebookCore'
pod 'FacebookLogin'
pod 'FacebookShare'

https://github.com/facebook/facebook-ios-sdk/issues/1756
should be 
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'

I had both - and it forced v5.
