### ISSUE TITLE
'FBSDKCoreKit+Internal.h' file not found. 

### ISSUE THREAD

**Issue by wangjunhua1** [facebook/facebook-ios-sdk#1707]
my podfile 

install! 'cocoapods',
  disable_input_output_paths: true,
  generate_multiple_pod_projects: true,
inhibit_all_warnings!

    pod "FBSDKCoreKit" ,'9.1.0'
    pod "FBSDKLoginKit" , '9.1.0'
    pod "FBSDKShareKit" , '9.1.0'

error:
![image](https://user-images.githubusercontent.com/11474284/113802078-a555a080-978c-11eb-8544-b93fc4b6f34f.png)

When I changed it to this, the error disappeared, please modify it

#ifdef FBSDKCOCOAPODS
 #import <FBSDKCoreKit/FBSDKCoreKit+Internal.h>
#else
 #import "FBSDKCoreKit+Internal.h"
#endif

**Comment by wangjunhua1** [comment]
I will be waiting online because we need to upgrade

**Comment by joesus** [comment]
Thanks for flagging this! https://github.com/facebook/facebook-ios-sdk/pull/1709 should fix. I plan to pick this into the 9.2 release candidate branch and expect to have it in the upcoming release.

**Comment by wangjunhua1** [comment]
> Thanks for flagging this! #1709 should fix. I plan to pick this into the 9.2 release candidate branch and expect to have it in the upcoming release.

When will the 9.2 release be? Thank you

**Comment by joesus** [comment]
I cannot make any promises but the goal is to release early next week.
