### ISSUE TITLE
FBSDKCoreKit Crash on [FBSDKSKAdNetworkReporter _loadConfigurationWithBlock:]_block_invoke_3

### ISSUE THREAD

**Issue by ChathuraP** [facebook/facebook-ios-sdk#1708]
## Environment

- Xcode Version: `12.4`
- Swift Version: `4.2` 
- Installation Platform & Verison: `Cocoapods` version `1.10.0`
- FBSDKCoreKit 9.0.1
- iOS 14.4.1 and 14.2
- Device iPhoneSE 13 devices and iPhone 7

## Issue
While trying to log in to the app using FB it is been crashed. We received the crash report via Xcode organiser. App crashed on below line
`Thread 21 name:`
`Thread 21 Crashed:`
`0   libsystem_kernel.dylib        	0x00000001bb91c414 __pthread_kill + 8`
`1   libsystem_pthread.dylib       	0x00000001d9478b50 pthread_kill + 272 (pthread.c:1392)`
`2   libsystem_c.dylib             	0x0000000196d7abf4 __abort + 116 (abort.c:147)`
`3   libsystem_c.dylib             	0x0000000196d7ab80 abort + 116 (abort.c:118)`
`4   libsystem_malloc.dylib        	0x000000019d75949c malloc_vreport + 560 (malloc_printf.c:183)`
`5   libsystem_malloc.dylib        	0x000000019d75967c malloc_report + 64 (malloc_printf.c:192)`
`6   libsystem_malloc.dylib        	0x000000019d74df68 free + 532 (malloc.c:1862)`
`7   CoreFoundation                	0x000000018d95bb54 __rehashs + 220 (NSSetM_Common.h:84)`
`8   CoreFoundation                	0x000000018d82e050 -[__NSSetM addObject:] + 492 (NSSetM.m:196)`
`9   libloader                     	0x0000000102a20690 0x1029e8000 + 231056`
`10  FBSDKCoreKit                  	0x0000000101c21278 __56+[FBSDKSKAdNetworkReporter _loadConfigurationWithBlock:]_block_invoke_3 + 414328 (FBSDKSKAdNetworkReporter.m:133)`
`11  libdispatch.dylib             	0x000000018d53f24c _dispatch_call_block_and_release + 32 (init.c:1454)`
`12  libdispatch.dylib             	0x000000018d540db0
[FBSDKCoreKit.crash.txt](https://github.com/facebook/facebook-ios-sdk/files/6269757/FBSDKCoreKit.crash.txt)
 _dispatch_client_callout + 20 (object.m:559)`
`13  libdispatch.dylib             	0x000000018d54810c _dispatch_lane_serial_drain + 580 (inline_internal.h:2548)`
`14  libdispatch.dylib             	0x000000018d548c5c _dispatch_lane_invoke + 408 (queue.c:3862)`
`15  libdispatch.dylib             	0x000000018d552d78 _dispatch_workloop_worker_thread + 708 (queue.c:6601)`
`16  libsystem_pthread.dylib       	0x00000001d9479814 _pthread_wqthread + 276 (pthread.c:2211)`
`17  libsystem_pthread.dylib       	0x00000001d948076c start_wqthread + 8`

please find the attached full crash report.
[FBSDKCoreKit.crash.txt](https://github.com/facebook/facebook-ios-sdk/files/6269791/FBSDKCoreKit.crash.txt)

## Replicate issue
On our testing devices we were not able to reproduce the crash yet but form user feedback we know that some users have constantly crashing the app at the login attempt.

Hope to hear a solution soon.
Thanks

**Comment by joesus** [comment]
Thanks for reaching out to us with this issue! Unfortunately, there is not enough information included here to help debug the issue further. As a result, we are closing this issue at this time. 

Please add additional information to help debug or report this to our designated developer support team here:  https://developers.facebook.com/support/bugs/
