### ISSUE TITLE
Sorting event mapping has an error in comparator. 

### ISSUE THREAD

**Issue by apkuhar** [facebook/facebook-ios-sdk#1724]
Compare line 106 and 103. 
They should not match. 

https://github.com/facebook/facebook-ios-sdk/blob/9aaaaf9fd334dc8c21eda9d3b7a227d2a0fda4e2/FBSDKCoreKit/FBSDKCoreKit/AppEvents/Internal/SKAdNetwork/FBSDKSKAdNetworkConversionConfiguration.m#L106

https://github.com/facebook/facebook-ios-sdk/blob/9aaaaf9fd334dc8c21eda9d3b7a227d2a0fda4e2/FBSDKCoreKit/FBSDKCoreKit/AppEvents/Internal/SKAdNetwork/FBSDKSKAdNetworkConversionConfiguration.m#L103

**Comment by jawwad** [comment]
Hi @apkuhar - Thanks for reporting this. This was fixed in 20d27fd391653ab47d549706bca8319d091cb1a6 and the fix should be available in the next release.
