### ISSUE TITLE
application:didFinishLaunchingWithOptions: calls itself always

### ISSUE THREAD

**Issue by martinbonaciugome** [facebook/facebook-ios-sdk#1732]
## Environment

Describe your dev environment here, giving as many details as possible. If you have them, make sure to include:

- Xcode Version: `12.5`
- Installation Platform & Verison: `Cocoapods` version `9.2.0`

## Goals

call application:didFinishLaunchingWithOptions: without the code running twice

## Expected Results

calling application:didFinishLaunchingWithOptions: will call itself

## Actual Results

application:didFinishLaunchingWithOptions: calls initializeSDKWithLaunchOptions: which in turn calls application:didFinishLaunchingWithOptions:, but _isAppLaunched has not been set to YES yet

## Steps to Reproduce

call application:didFinishLaunchingWithOptions: and put a breakpoint on FBSDKApplicationDelegate.m@275, where _isAppLaunched = YES; it will get hit twice

## Code Samples & Details
<img width="1370" alt="Screen Shot 2021-04-30 at 8 42 36 AM" src="https://user-images.githubusercontent.com/6127051/116719616-1e14da80-a990-11eb-8880-8ae6055f4bfa.png">

**Comment by jawwad** [comment]
Hi @martinbonaciugome - Could you update to v11.1.0 and see if you are still encountering this issue?

**Comment by jawwad** [comment]
Hi @martinbonaciugome - Since this issue is a few months old and I haven't heard back on if you are still encountering the issue, I'm going to go ahead and close it out. If you are still encountering the issue on the latest version of the SDK please feel free to open another issue. Thanks!
