### ISSUE TITLE
Feature Request: Getting friends' names and profile pictures in limited login

### ISSUE THREAD

**Issue by rampr** [facebook/facebook-ios-sdk#1736]
## Checklist

- [x] I've updated to the latest released version of the SDK
- [x] I've searched for existing feature requests on [GitHub issues](https://github.com/facebook/facebook-ios-sdk/issues)
- [x] I've read the [Code of Conduct](CODE_OF_CONDUCT.md)
- [x] I've given my issue the title: `Feature Request: Getting friends' names and profile pictures in limited login`

## Goals
I want to be able to retrieve and show friends' names and profile pictures in limited login mode

## Expected Results
Have an API that allows  me to get friends' names and profile pictures in limited login mode

## Code Samples & Details

Not Applicable

**Comment by ppansy** [comment]
Hi, please refer to our developer doc: https://developers.facebook.com/docs/facebook-login/limited-login/faq#faq_673110680084333
Unfortunately we can't provide such API at this point. You should be able to get the friends's names and profile pictures from their Limited Login session.
