### ISSUE TITLE
Feature Request: Add the ability to disable automatic ad network attribution register

### ISSUE THREAD

**Issue by revolter** [facebook/facebook-ios-sdk#1739]
## Checklist

- [x] I've updated to the latest released version of the SDK
- [x] I've searched for existing feature requests on [GitHub issues](https://github.com/facebook/facebook-ios-sdk/issues)
- [x] I've read the [Code of Conduct](CODE_OF_CONDUCT.md)
- [x] I've given my issue the title: `Feature Request: [name of my feature request]`

## Goals

I would want for the SDK **not** to automatically call the `+[SKAdNetwork registerAppForAdNetworkAttribution]` method.

## Expected Results

I expect to have a property or method which allows me to indirectly disable these calls.

## Code Samples & Details

This is called on app open:
https://github.com/facebook/facebook-ios-sdk/blob/97b639e00852c8a8eef41291a06057749d7176b9/FBSDKCoreKit/FBSDKCoreKit/AppEvents/FBSDKAppEvents.m#L1232

This _might_ be called automatically in other scenarios:
https://github.com/facebook/facebook-ios-sdk/blob/97b639e00852c8a8eef41291a06057749d7176b9/FBSDKCoreKit/FBSDKCoreKit/AppEvents/Internal/SKAdNetwork/FBSDKSKAdNetworkReporter.m#L81

**Comment by MaoDaAmargura** [comment]
I would also like this feature. I make the calls myself as I have two or three other ad network SDKs that rely on the data.
