### ISSUE TITLE
AppTrackingTransparency prompt iOS 14.5

### ISSUE THREAD

**Issue by LuckyDari** [facebook/facebook-ios-sdk#1740]
My project currently has the following facebook SDKs:

pod '**FBSDKCoreKit**', '**8.2.0**'
pod '**FBSDKShareKit**', '**8.2.0**'
pod '**FBSDKLoginKit**', '**8.2.0**'

My question is: 
in my project I don't want to show the new **AppTrackingTransparency** prompt at all, so do I need to do anything regarding these three SDKS or am I ready to go ? do these SDKs somehow use the **IDFA** or has a code related to it ?

Tried to find something that gives me a clear answer regarding this but I couldn't, thats why I posted this here.

**Comment by BrentMifsud** [comment]
I have the same question. We only use Facebook login, so we switched to the limited login and disabled sdk autostart.

Not sure if thats enough.

**Comment by shalinipk** [comment]
Hope this helps - https://www.facebook.com/business/news/preparing-our-partners-for-ios-14-launch

**Comment by joesus** [comment]
Please reach out to our designated developer support team https://developers.facebook.com/support if there are additional questions around policy. Thanks!
