### ISSUE TITLE
FBSDK version 9.2.0 and 9.3.0 crash if native Facebook app not installed

### ISSUE THREAD

**Issue by tiendaik** [facebook/facebook-ios-sdk#1742]
I'm using newest FBSDK version (9.3.0) in an Objective-C project, with XCode 12.1 (12A7403).
When I call [FBSDKShareDialog showFromViewController:] on a device with no native Facebook app installed, it crash instead of showing webview like older version. It's working normally when Facebook app is installed, or when I build with older FBSDK version (on same device iPhone 6s Plus, iOS 13.3.1).
Here is crash log:

App ID not found. Add a string value with your app ID for the key FacebookAppID to the Info.plist or call [FBSDKSettings setAppID:].
(
    "4   CoreFoundation                      0x00000001ad6aad50 7519E999-1053-3367-B9D5-8844F6D3BDC6 + 1228112",
    "5   libobjc.A.dylib                     0x00000001ad3d224c A697479D-4C5C-391E-B117-85B894AB94C6 + 25164",
    "6   libc++abi.dylib                     0x00000001ad477304 295D93E6-AC06-384A-A469-2DF327F697FC + 58116",
    "7   libc++abi.dylib                     0x00000001ad47729c _ZSt9terminatev + 44",
    "8   libdispatch.dylib                   0x000000010c566bec _dispatch_client_callout + 36"
)

Anyone facing same issue?

**Comment by joesus** [comment]
This is expected. The SDK requires an App ID to function correctly. Please follow the instructions at https://developers.facebook.com/docs/ios/getting-started (Step 2: Configure Your Project)

Thanks!

**Comment by tiendaik** [comment]
> This is expected. The SDK requires an App ID to function correctly. Please follow the instructions at https://developers.facebook.com/docs/ios/getting-started (Step 2: Configure Your Project)
> 
> Thanks!

Do you read my bug carefully? You miss some important info from it: my app is working normally with older FBSDK version, so the problem is not my project config

**Comment by joesus** [comment]
I did notice this but it seems besides the point. If the app id is present then I don't see any code path that could produce that error. Please correct me if I'm missing one. So my point is that if it was somehow working before without an app id then this is an issue. 

If the bug is with setting app ids then that's a huge bug but a different bug.

**Comment by joesus** [comment]
If you could open a new issue or include a reproducible sample and attach it to this issue it would help diagnose and debug. Thanks!

**Comment by hiralin** [comment]
@tiendaik Did this solve your issue?
I'm facing same issue.

- Xcode : 13.0 (13A233)
- Lang : Objective-C
- Device : iPhone 13 Pro (iOS 15.0.2)
- facebook-sdk : 11.2.1 - 12.0.2 (via cocoapods)
- Error :  
```
App ID not found. Add a string value with your app ID for the key FacebookAppID to the Info.plist or call [FBSDKSettings setAppID:].
```

NG : Set App ID in info.plist
NG : Set App ID in code
OK : Use facebook-sdk ver11.1.0 (App ID is set in info.plist as same as previous version of my app)

**Comment by tiendaik** [comment]
> @tiendaik Did this solve your issue? I'm facing same issue.
> 
> * Xcode : 13.0 (13A233)
> * Lang : Objective-C
> * Device : iPhone 13 Pro (iOS 15.0.2)
> * facebook-sdk : 11.2.1 - 12.0.2 (via cocoapods)
> * Error :
> 
> ```
> App ID not found. Add a string value with your app ID for the key FacebookAppID to the Info.plist or call [FBSDKSettings setAppID:].
> ```
> 
> NG : Set App ID in info.plist NG : Set App ID in code OK : Use facebook-sdk ver11.1.0 (App ID is set in info.plist as same as previous version of my app)

Unfortunately no, I have to check Facebook native app is installed or not manually, if not I show a notice message to user

**Comment by hiralin** [comment]
Thank you for responding.
In my case, crashes occur either if native Facebook app is installed or not🤔
