### ISSUE TITLE
How to initialise Facebook SDK in iOS 14 Widget Extension?

### ISSUE THREAD

**Issue by SagarUnagar** [facebook/facebook-ios-sdk#1748]
How do I initialisation Facebook SDK in iOS 14 widget extension?

My end goal is to call GraphRequest from my widget extension. And according to documentation, to call graph request we need to initialise Facebook SDK first.

Please help, Thanks in advance!

**Comment by xamiell** [comment]
Some update?

**Comment by jawwad** [comment]
Hi @SagarUnagar - Unfortunately we don't support using the SDK in extensions at this time.
