### ISSUE TITLE
The name in prompt dialog is wrong

### ISSUE THREAD

**Issue by shixueqian** [facebook/facebook-ios-sdk#1753]
When logging in for the first time, a prompt dialog will pop up, which says
`"xxx" Wants to Use "facebook.com" to Sign In`
`This allows the app and website to share information about you`
`Cancel`  `Continue`
But it’s strange that the "xxx" shown here is not the name of our App
E.g:
The name of our App is `Handsome`
After installing the App, I see the name is `Handsome` on the phone.
But here "xxx" shows `abcd`
I took a look,
We set the parameter of `CFBundleDisplayName` to `Handsome` in Info.plist,
Then `abcd` is only set in the `CFBundleName` and `CFBundleExecutable` of the Info.plist file.
So here is the value in `CFBundleName` or `CFBundleExecutable`?

Why not read `CFBundleDisplayName` first?

**Comment by ppansy** [comment]
The prompt you mentioned is an iOS system dialog that Facebook does not have control over. You should check with Apple on  how to change it.
