### ISSUE TITLE
descrepancy between readme and getting started guide

### ISSUE THREAD

**Issue by 8secz-johndpope** [facebook/facebook-ios-sdk#1756]
https://developers.facebook.com/docs/ios/use-cocoapods

the readme says
 pod 'FBSDKCoreKit'
 pod 'FBSDKLoginKit'
 pod 'FBSDKShareKit'

this page says

Allow your app to use the Facebook services | 
pod 'FacebookCore'
pod 'FacebookLogin'
pod 'FacebookShare'

my app includes both!
the sdk is stuck on v5. 
I just need latest sdk.

**Comment by joesus** [comment]
Updated! Thanks for the feedback!
