### ISSUE TITLE
swift and Facebook audience network

### ISSUE THREAD

**Issue by SodaSurfer** [facebook/facebook-ios-sdk#1760]
Hi

Im trying to use this sdk for the audience network by using this tutorial:
https://developers.facebook.com/docs/audience-network/setting-up/ad-setup/ios/interstitial

but it looks like it's out-dated and not working with swift.
any chance that the audience sdk is not working with swiftui?

**Comment by sharoni** [comment]
Documentation has been updated with Swift samples.

**Comment by jawwad** [comment]
Closing out as the documentation has been updated per @sharoni.
