### ISSUE TITLE
fetchDeferredAppLink method  can by custom appid

### ISSUE THREAD

**Issue by RenshawPeng** [facebook/facebook-ios-sdk#1762]
## Code Samples & Details
maybe Like Android SDK,
https://github.com/facebook/facebook-android-sdk/blob/master/facebook-applinks/src/main/java/com/facebook/applinks/AppLinkData.java#L125
```
public static void fetchDeferredAppLinkData(      Context context, String applicationId, final CompletionHandler completionHandler) 
```

thanks

**Comment by gyorgyilibor** [comment]
Thank's

**Comment by jawwad** [comment]
Hi @RenshawPeng - Since I haven't heard back from you on this I'm going to close this issue out. Feel free to reopen with the requested info. Thansk!
