### ISSUE TITLE
How to get callbacks when using Facebook analysis

### ISSUE THREAD

**Issue by chengxuyuanxiaoka** [facebook/facebook-ios-sdk#1764]
When using the analysis of Facebook, which method is called to receive the callback after sending the punctuation. For example, when the management fails for some reasons, I need to submit the management again or do other processing. At present, I call [fbsdkappevents loge] vent:key parameters : parameters] is there any block or delegate that supports me to determine whether the point is successful. We look forward to your reply

**Comment by joesus** [comment]
Thanks for reaching out to us with this issue! Unfortunately, there is not enough information included here to help debug the issue further. As a result, we are closing this issue at this time. 

Please open a new issue using the Github issue template and be sure to include the requested information to help us debug the issue further OR report this to our designated developer support team here:  https://developers.facebook.com/support/bugs/
