### ISSUE TITLE
What is it FBSDKKoreKit_Basics, why do i need to add it to solve some errors.

### ISSUE THREAD

**Issue by Kamui-IOS** [facebook/facebook-ios-sdk#1767]
![telegram-cloud-photo-size-5-6199434221605465535-x](https://user-images.githubusercontent.com/57245356/121496029-48809b80-ca04-11eb-8ad0-f2b137e9ffd8.jpg)

**Comment by joesus** [comment]
Thanks for reaching out to us with this issue! Unfortunately, there is not enough information included here to help debug the issue further. As a result, we are closing this issue at this time. 

Please open a new issue using the Github issue template and be sure to include the requested information to help us debug the issue further OR report this to our designated developer support team here:  https://developers.facebook.com/support/bugs/
