### ISSUE TITLE
logOut No effect

### ISSUE THREAD

**Issue by chengxuyuanxiaoka** [facebook/facebook-ios-sdk#1778]
xcode 12.2, sdk 9.3.0,All mobile phones。

In the app application, you can log in to Facebook through the web page, call logout, you can't exit the current login account, and you can't switch accounts:
FBSDKLoginManager *fbLogin = [[FBSDKLoginManager alloc] init];
[fbLogin logOut];

Our Android colleagues passed on 9.0LoginManager.getInstance().setLoginBehavior(LoginBehavior.WEB_VIEW_ONLY);After realizing this function, I found that LoginBehavior has only one option LoginBehaviorBrowse in FBSDKLoginManager. h. how can I realize the same function as Android.

Here is the code I call：
 FBSDKLoginManager *fbLogin = [[FBSDKLoginManager alloc] init];
[fbLogin logOut];
[fbLogin logInWithPermissions:@[@"public_profile"] fromViewController:[DPSUtils getTopViewController] handler:^(FBSDKLoginManagerLoginResult * _Nullable result, NSError * _Nullable error) {
 if (error) {

} else if (result.isCancelled){

} else {
       
}
}];

**Comment by chengxuyuanxiaoka** [comment]
There's another problem, the code above，You can jump to the Facebook client on 12. X system. Why can't you jump to the client above 13. X?

**Comment by ppansy** [comment]
Hey, unfortunately we don't provide the ability to customize login behavior in iOS. 

Can you describe what are you trying to achieve by performing log out? What's the expected behavior? What made you believe that logout isn't working? thanks

**Comment by ppansy** [comment]
I'll close since there are no updates. Feel free to reopen if the issue still exists
