### ISSUE TITLE
Mac catalyst Facebook authentication doesn't work Code=301

### ISSUE THREAD

**Issue by emoonadev** [facebook/facebook-ios-sdk#1781]
Hello, I created a project on swiftUI

When I do login user it works on iPhone, but not on Mac Catalyst,
I get `Error Domain=com.facebook.sdk.core Code=301 "(null)" UserInfo={com.facebook.sdk:FBSDKErrorDeveloperMessageKey=Please try to login again}`

My code:
```
class AppDelegate: UIResponder, UIApplicationDelegate {
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        ApplicationDelegate.shared.application(application, didFinishLaunchingWithOptions: launchOptions)
        return true
    }
}

@main
struct FBAutoPosterApp: App {
    @UIApplicationDelegateAdaptor(AppDelegate.self) var delegate
    @Environment(\.scenePhase) var scenePhase

    var body: some Scene {
        WindowGroup {
            MainView().onOpenURL { url in
                _ = ApplicationDelegate.shared.application(
                    UIApplication.shared,
                    open: url,
                    sourceApplication: nil,
                    annotation: [UIApplication.OpenURLOptionsKey.annotation])
            }
        }
    }
}
```

**Comment by samodom** [comment]
@emoonadev For a Catalyst app, you'll need to add the "Keychain Sharing" capability to your app to support login capabilities.  You can add this entitlement in the "Signing & Capabilities" tab for your target.  We'll make sure that our documentation reflects this requirement going forward.

**Comment by samodom** [comment]
Feel free to reopen this request if you still run into trouble with the provided solution.
