### ISSUE TITLE
Request to provide an example to replace deprecated "AppEvents.activateApp()"

### ISSUE THREAD

**Issue by murillotomas** [facebook/facebook-ios-sdk#1782]
Hello, I have to update FacebookSDK for this piece of code:
`AppEvents.activateApp()`

I came across this warning:
_"The class method `activateApp` is deprecated. It is replaced by an instance method of the same name."_

Would you be so kind as to provide an example of how we can register now when the app is being activated? I did not really find a way to do it.

Thank you!

**Comment by Dzyrus** [comment]
Hello. Same problem here. it could be use through singleton just like this: 
 `AppEvents.singleton.activateApp()`

But singleton marked as  
```
 Internal Type exposed to facilitate transition to Swift.
 API Subject to change or removal without warning. Do not use.

 @warning UNSAFE - DO NOT USE
 @property (class, nonatomic, readonly, strong) FBSDKAppEvents *singleton;
```
I did not really find a way to do it too.

Thank you!

**Comment by noahcooper** [comment]
I recently updated [cordova-plugin-facebook-connect](https://github.com/cordova-plugin-facebook-connect/cordova-plugin-facebook-connect/) to use the instance method like so:

```
[[FBSDKAppEvents alloc] activateApp]
```

**Comment by jamestouri** [comment]
We plan to deprecate singleton and replace it with the name shared in the next minor release. Until then you can get rid of the deprecation warning by using @Dzyrus' solution but be advised you will then face a different deprecation warning to resolve. It may be simpler to wait until then to make the change.

**Comment by tonyhunt** [comment]
Looks like this fix didn't make it in version `11.1.0`. Can we get an update on when this is likely to be resolved? Thanks

**Comment by technocraticOptimist** [comment]
Facing the same issue. An update would be great...

**Comment by Sunrise17** [comment]
There is no fix on 11.2.1.

**Comment by alexratcatcher** [comment]
@jamestouri , does someone care about this warning?

**Comment by salvatoreboemia** [comment]
Hi @jamestouri , any news on that? thanks
