### ISSUE TITLE
Problem with Facebook audience network integration with Mopub

### ISSUE THREAD

**Issue by SodaSurfer** [facebook/facebook-ios-sdk#1801]
I am trying to integrate FAN ads for bidding, using Mopub integration.
I have created my ad spaces and did all the setup that I needed to do in the FAN console and also in Mopub console as instructed in here: https://developers.mopub.com/publishers/ui/manage-advanced-bidding/
and in here: https://developers.facebook.com/docs/audience-network/bidding/partner-mediation/mopub

I think that there is something wrong in my code implementation.
I am using swiftui and I have initialized Facebook ads and Mopub ads like so when my app launches:

```
ATTrackingManager.requestTrackingAuthorization(completionHandler: { status in
    Analytics.logEvent(AppConsts.FBA_EVENT_TRACK_AUTH, parameters: [AppConsts.FBA_PARAM_TRACK_STATUS: String(status.rawValue)])
    
    // used for FBA
    FBAudienceNetworkAds.initialize(with: nil, completionHandler: nil)
    switch (status) {
    case .authorized:
        FBAdSettings.setAdvertiserTrackingEnabled(true)
        break
    case .denied, .notDetermined, .restricted:
        FBAdSettings.setAdvertiserTrackingEnabled(false)
        break
    @unknown default:
        FBAdSettings.setAdvertiserTrackingEnabled(false)
        break
    }
    
    // Tracking authorization completed. Start loading ads here.
    // Initialize Mopub
    let sdkConfig = MPMoPubConfiguration(adUnitIdForAppInitialization: AdsId.BANNER_ID.value)
    sdkConfig.loggingLevel = .info
    MoPub.sharedInstance().initializeSdk(with: sdkConfig)
})
```

Now, I do get ad requests from Mopub and I see the data in Mopub console, but I don't get any response from Facebook and I get this error showing on Facebook audience network console:
`"We haven't received a bid request"`

am I missing something in the code integration?
The examples here aren't updated to swiftui and for bidding, therefore I assume I am missing something.

thanks

**Comment by linmx0130** [comment]
Hi @SodaSurfer! It looks like that you're asking a problem about Audience Network, which is not part of the Facebook iOS SDK. You'd better raise the issue to [Facebook Developer Support](https://developers.facebook.com/support/) to get support.
