### ISSUE TITLE
Facebook sdk don't listen to updated app on Appstore

### ISSUE THREAD

**Issue by shareecoindev** [facebook/facebook-ios-sdk#1881]
### Checklist before submitting a feature request

- [X] I've updated to the latest released version of the SDK
- [X] I've searched for existing [Github issues](https://github.com/facebook/facebook-ios-sdk/issues)
- [X] I've read the [Code of Conduct](https://github.com/facebook/facebook-ios-sdk/blob/master/CODE_OF_CONDUCT.md)

### Goals

<img width="1031" alt="Screen Shot 2021-09-13 at 1 29 27 PM" src="https://user-images.githubusercontent.com/74548523/133076230-9aabf063-51da-48d0-b949-ba34c815bc4b.png">
i have updated the SDK as you see and published it about a month ago and facebook didn't seem to listen to the updated app on Appstore.

### Expected results

Facebook listen to the app with the updated SDK on Appstore

### Code samples & details

```swift
// INSERT YOUR CODE HERE
var example = "Example code"
```

**Comment by linmx0130** [comment]
Hi @shareecoindev, thanks for raising this issue! Could you ask this problem to the [Facebook Developer Support](https://developers.facebook.com/support/) for help since it's not a problem about the SDK itself.
