### ISSUE TITLE
Feature Request: FBSDK 12.x can be supported iOS 9?

### ISSUE THREAD

**Issue by loyalwind** [facebook/facebook-ios-sdk#1963]
### Checklist before submitting a feature request

- [X] I've updated to the latest released version of the SDK
- [X] I've searched for existing [Github issues](https://github.com/facebook/facebook-ios-sdk/issues)
- [X] I've read the [Code of Conduct](https://github.com/facebook/facebook-ios-sdk/blob/main/CODE_OF_CONDUCT.md)

### Goals

My Project deployed on iOS 9 and Now Using FBSDK 9.1.0!  But I want to upgrade FBSDK to 12.x version, i do not know the  FBSDK 12.x version is supported iOS 9? what do I do?

### Expected results

FBSDK 12.x can be supported iOS 9?

### Code samples & details

```swift
# Podfile

platform :'ios', '10.0'

target 'MyProject' do
  pod 'FBSDKLoginKit', '~> 9.1.0'
  pod 'FBSDKShareKit', '~> 9.1.0'
  pod 'FBSDKCoreKit', '~> 9.1.0'
end
```

**Comment by jawwad** [comment]
Hi @loyalwind - We no longer support iOS 9 in iOS SDK v12. The minimum supported version is iOS 10.
