### ISSUE TITLE
Feature Request: Expose in sdk an option to run ephemeral login session   

### ISSUE THREAD

**Issue by kolboch** [facebook/facebook-ios-sdk#2000]
### Checklist before submitting a feature request

- [X] I've updated to the latest released version of the SDK
- [X] I've searched for existing [Github issues](https://github.com/facebook/facebook-ios-sdk/issues)
- [X] I've read the [Code of Conduct](https://github.com/facebook/facebook-ios-sdk/blob/main/CODE_OF_CONDUCT.md)

### Goals

Primary goal is to enable user to authenticate the app with different Facebook account on login after the first consent, common scenario is a device shared between multiple people or (in this case not applying to terms and conditions) multi account.

### Expected results

For iOS 13+ make possible for sdk user to set `prefersEphemeralWebBrowserSession` to `true` for `ASWebAuthenticationSession` run by sdk on login. It would make reentering facebook login credentials possible (switching account, or basically allowing other user to use his facebook account aswell inside the app - in case of shared device) without caching initially provided credentials by ASWebAuthenticationSession.

### Code samples & details

```swift
For now when using Facebook login after initial credentials are provided inside `ASWebAuthenticationSession`, data will be cached there without any possibility to remove it. 
Even after calling `LoginManager().logOut()` only locally stored AccessToken will be nil, but cookies or other data will be still present in iOS `ASWebAuthenticationSession`. 
Since iOS 13+ there is a way to run session with `prefersEphemeralWebBrowserSession` set to `true`, which would enable users to reenter their credentials. 
If possible it would be great to expose that in Facebook ios sdk and propagate to session run on login.
This feature request is based on the discussion there: 
https://github.com/facebookarchive/react-native-fbsdk/issues/712 
and 
https://github.com/facebookarchive/facebook-swift-sdk/issues/215
```

**Comment by SultanOfDawn** [comment]
Facebook account login username.. #19842022day don't forget #anonymousGeneral ..

**Comment by KrisLau** [comment]
Is this on the table to be merged in eventually? I would love to have this feature available as it would be very useful for users to be able to change the facebook account

**Comment by KrisLau** [comment]
Still requires attention
