### ISSUE TITLE
Feature Request: Move didFinishLaunchingWithOptions calling from the main thread

### ISSUE THREAD

**Issue by MarinaZvyagina** [facebook/facebook-ios-sdk#2017]
### Checklist before submitting a feature request

- [X] I've updated to the latest released version of the SDK
- [X] I've searched for existing [Github issues](https://github.com/facebook/facebook-ios-sdk/issues)
- [X] I've read the [Code of Conduct](https://github.com/facebook/facebook-ios-sdk/blob/main/CODE_OF_CONDUCT.md)

### Goals

I want to improve app launch time. Now Facebook didFinishLaunchingWithOptions method call
`ApplicationDelegate.shared.application(application, didFinishLaunchingWithOptions: launchOptions)`
takes 35.5 ms on 90 percentile of my app users. If I could call it from background thread it would take only 0.01ms

### Expected results

0.01ms time Facebook takes for didFinishLaunchingWithOptions method call

**Comment by jawwad** [comment]
Hi @MarinaZvyagina - Thanks for raising this issue. I'll look into this to see what we have to do to support it running on a background thread, to see if we can support this use case.
