### ISSUE TITLE
Facebook-ios-sdk could not be resloved

### ISSUE THREAD

**Issue by elmysf** [facebook/facebook-ios-sdk#2023]
### Checklist before submitting a feature request

- [X] I've updated to the latest released version of the SDK
- [X] I've searched for existing [Github issues](https://github.com/facebook/facebook-ios-sdk/issues)
- [X] I've read the [Code of Conduct](https://github.com/facebook/facebook-ios-sdk/blob/main/CODE_OF_CONDUCT.md)

### Goals

When I want to add the facebook sdk, but it can't be done several times, the same message always appears, namely "Facebook-ios-sdk could not be resloved", even I try to create a new project, it's still the same
<img width="700" alt="Screen Shot 2022-02-10 at 16 35 29" src="https://user-images.githubusercontent.com/37185272/153380035-c3aa3ce3-71b1-4bed-901b-c4c585c1946a.png">

### Expected results

In the existing documentation the recommended version for SPM is version 5.10.0 for the ### next major version, but when I try both in the minor version I can't add the facebook sdk to my project

<img width="460" alt="Screen Shot 2022-02-10 at 16 35 41" src="https://user-images.githubusercontent.com/37185272/153380416-16e53ba3-d3de-4a2e-8be6-72931f2f597f.png">

### Code samples & details

```swift
// INSERT YOUR CODE HERE
var example = "Example code"
```

**Comment by jawwad** [comment]
@elmysf - For some reason, the latest tag isn't showing up in Xcode 13. As @Cookiezby mentioned you can manually set the version for now.

We are tracking this issue in https://github.com/facebook/facebook-ios-sdk/issues/2022 so I'm going to close this issue out.
