### ISSUE TITLE
Feature Request: 

### ISSUE THREAD

**Issue by kklt12399** [facebook/facebook-ios-sdk#2026]
### Checklist before submitting a feature request

- [X] I've updated to the latest released version of the SDK
- [X] I've searched for existing [Github issues](https://github.com/facebook/facebook-ios-sdk/issues)
- [X] I've read the [Code of Conduct](https://github.com/facebook/facebook-ios-sdk/blob/main/CODE_OF_CONDUCT.md)

### Goals

Pod can't find the latest version, only 11.2.1

### Expected results

Pod can find the latest version

### Code samples & details

```swift
// INSERT YOUR CODE HERE
var example = "Example code"
```

**Comment by kklt12399** [comment]
pod -v  1.11.2

**Comment by jawwad** [comment]
Hi @kklt12399 - Looks like this was accidentally opened. I will go ahead and close it out for you.

**Comment by kklt12399** [comment]
> Hi @kklt12399 - Looks like this was accidentally opened. I will go ahead and close it out for you.

When can you upload the latest version of pod SDK?

**Comment by kklt12399** [comment]
The recent project needs to be upgraded to 12.3.2. Please update it to pod as soon as possible

**Comment by jawwad** [comment]
@kklt12399 - Can you explain what you mean by "Pod can't find the latest version, only 11.2.1"?

**Comment by jawwad** [comment]
We've updated the SDK to v13 so I'm going to close this out. If you are having an issue please open an issue with the bug report template which will include some other information that we need as well. Thanks!
