### ISSUE TITLE
ios sdk facebook login

### ISSUE THREAD

**Issue by mohdhafizz8508** [facebook/facebook-ios-sdk#2105]
### Checklist before submitting a feature request

- [X] I've updated to the latest released version of the SDK
- [X] I've searched for existing [Github issues](https://github.com/facebook/facebook-ios-sdk/issues)
- [X] I've read the [Code of Conduct](https://github.com/facebook/facebook-ios-sdk/blob/main/CODE_OF_CONDUCT.md)

### Goals

thanks support

### Expected results

ios

### Code samples & details

```swift
ios sdk facebook
```

**Comment by uzunbe** [comment]
hello. I don't know what to say, but I don't know much about programming, and there are problems on my page that I don't know how it can be modified, there are notifications that do not appear, the feature is sometimes slow. I am trying to get it back to normal. thank you . تم الإرسال من Galaxy الخاص بي
-------- الرسالة الأصلية --------من: Mohamad Hafis Bin Mustapa ***@***.***> التاريخ: ٢٥‏/٨‏/٢٠٢٢  ١٠:٤٢ م  (GMT+03:00) إلى: facebook/facebook-ios-sdk ***@***.***> نسخة: Subscribed ***@***.***> الموضوع: [facebook/facebook-ios-sdk] ios sdk facebook login (Issue #2105) 
Checklist before submitting a feature request

 I've updated to the latest released version of the SDK
 I've searched for existing Github issues
 I've read the Code of Conduct

Goals
thanks support
Expected results
ios
Code samples & details
ios sdk facebook
