### ISSUE TITLE
To make maps a friend sone and I will make it wear all whu are friends know, infarct I would like to make it avatar wourld

### ISSUE THREAD

**Issue by stebbi36** [facebook/facebook-ios-sdk#2310]
To make maps a friend sone and I will make it wear all whu are friends know, infarct I would like to make it avatar wourld 

_Originally posted by @stefanajons in https://github.com/climate-strike/license/issues/26#issuecomment-1837965173_

**Comment by stefanajons** [comment]
<p xmlns:cc="http://creativecommons.org/ns#" >This work is licensed under <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC BY-NC-SA 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1"><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1"><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/nc.svg?ref=chooser-v1"><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/sa.svg?ref=chooser-v1"></a></p>
