### ISSUE TITLE
FBDialog Photo Sharing issue

### ISSUE THREAD

**Issue by ankurdiyora** [facebook/facebook-ios-sdk#681]
Hello,
I am sharing photo using FBDialogs presentShareDialogWithPhotoParams method. This method share photo successfully on my wall but always return error. That means post photo with NSError.
Error is like....
////////////////////////////////////////
Error Domain=com.facebook.Facebook.platform Code=103 "The operation couldn’t be completed. (com.facebook.Facebook.platform error 103.)" UserInfo=0x16d874f0 {error_code=103, error_description=An unknown error occurred., app_id=593434950703264, error_reason=(
{
result = 1;
}
)}
////////////////////////////////////////
Why this happen?

**Comment by aravindkumar** [comment]
rror Domain=com.facebook.Facebook.platform Code=103 "The operation couldn’t be completed. (com.facebook.Facebook.platform error 103.)" UserInfo=0x1609e430 {error_code=103, error_description=An unknown error occurred., app_id=903149613031577, error_reason=(
        {
        result = 1;
    }
)}

**Comment by Ankur** [comment]
wrong person bro haha

- Ankur
  818 602-3397
