### ISSUE TITLE
Carthage support?

### ISSUE THREAD

**Issue by justinmakaila** [facebook/facebook-ios-sdk#686]
See [carthage](https://github.com/Carthage/Carthage), a decentralized dependency manager for Xcode projects. It's very similar to Cocoapods, only you don't have to write a `.podspec` or any file that needs to be `lint`ed. It also manages your `git submodules` for you.

Example Cartfile for `facebook-ios-sdk`

```
# Require the latest version of Bolts
github "BoltsFramework/Bolts-iOS"
```

It would also be very nice if the SDK could build itself into a dynamic framework, but that's a separate issue in and of itself.

**Comment by AndrewSB** [comment]
whats the progress on this?

**Comment by justinmakaila** [comment]
https://github.com/justinmakaila/facebook-ios-sdk

**Comment by justinmakaila** [comment]
@AndrewSB ^

**Comment by AndrewSB** [comment]
Any chance of it being merged into master by @facebook-github-bot? or being kept upto date with the latest iOS SDK?

**Comment by justinmakaila** [comment]
Feel free to contribute ;)




I can take a peak at what updates need to be made tomorrow.



—Justin Makaila

**Comment by AndrewSB** [comment]
@justinmakaila we could do that, but I'd rather have @facebook-github-bot manage it... Does facebook ever look/respond to issues similar to this?
