### ISSUE TITLE
App references non-public selectors

### ISSUE THREAD

**Issue by dalexsoto** [facebook/facebook-ios-sdk#691]
Hello Guys

I am having issues submitting my app to the store whenever I try to use the wrapper protocols like FBGrapUser and friends

just to mention a few of them.

https://github.com/facebook/facebook-ios-sdk/blob/master/src/FBGraphUser.h#L59
https://github.com/facebook/facebook-ios-sdk/blob/master/src/FBGraphLocation.h#L64

![errors](https://cloud.githubusercontent.com/assets/204671/5550003/9a8f8300-8b5e-11e4-9510-e99126946cc3.png)

Some of the errors goes away if I remove the Facebook iOS SDK. This is really a pain if you can't use the convenience wrappers.

**Comment by chrisp-fb** [comment]
Sorry for the inconvenience, the convenience protocols unfortunately collided with some private Apple selectors. As a workaround, you should be able to treat the object as a dictionary and use indexers like `[@"birthday"]` instead of `.birthday`. We'll deprecate the helpers with comments to that effect in a future release.

**Comment by elandreusa** [comment]
Why do you send me this????

On Monday, January 5, 2015, Chris Pan <notifications@github.com> wrote:

> Sorry for the inconvenience, the convenience protocols unfortunately
> collided with some private Apple selectors. As a workaround, you should be
> able to treat the object as a dictionary and use indexers like
> [@"birthday"] instead of .birthday. We'll deprecate the helpers with
> comments to that effect in a future release.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/facebook-ios-sdk/issues/691#issuecomment-68747032>
> .
>


-- 
Elandre Du Toit
