### ISSUE TITLE
FBErrorUtility `errorCodeForError:` improper return value

### ISSUE THREAD

**Issue by gwdp** [facebook/facebook-ios-sdk#694]
`FBErrorUtility` methods:
 `+ (NSUInteger)errorCodeForError:(NSError *)error;`
`+ (NSUInteger)errorSubcodeForError:(NSError *)error;`
 should return `NSInteger` type since error codes like timeout (`-1001`) will not work with current return value.

**Comment by gwdp** [comment]
OK, I found that these methods only recognises errors coming from sever on `FBErrorParsedJSONResponseKey` dictionary. 
By saying `Retrieves the underlying error code from an FBError that is wrapped within an NSError.` on header doc, no one will ever notice this and will try to fetch all error codes from those methods..

I really do recommend to fallback to `FBErrorInnerErrorKey` dictionary error when server response dictionary is missing.. Or explicit say it will fetch only `FBErrorParsedJSONResponseKey` errors and document it.

So for me this is a closed issue because it's the expect behaviour but bad designed. 
Will let owner close this.

**Comment by gwdp** [comment]
OK, I found that these methods only recognises errors coming from server on `FBErrorParsedJSONResponseKey` dictionary. I'm right ?
By saying `Retrieves the underlying error code from an FBError that is wrapped within an NSError.` on header doc, no one will ever notice this and will try to fetch all error codes from those methods..

I really do recommend to fallback to `FBErrorInnerErrorKey` dictionary error when server response dictionary is missing.. Or explicitly say it will fetch only `FBErrorParsedJSONResponseKey` errors and document it.

So for me this is a closed issue because it's the expected behaviour but bad designed. 
I will let owner close this.

**Comment by chrisp-fb** [comment]
Hi @gwdp , 

 You're right the `errorCodeForError` is only intended for FB server side errors (where `FBErrorParsedJSONResponseKey` is parsed), sorry for the confusion and that's a good idea about being more explicit in the headerdoc.

Can you clarify a specific scenario where a "fallback to `FBErrorInnerErrorKey`" would be useful to you? The inner error keyed by `FBErrorInnerErrorKey` is typically used when the SDK is wrapping around some other kind of error (e.g., login) so typically fetching only the codes from the top level is sufficient (and avoids cases where it would be bad to get the nested error's codes - it's certainly safer for you to pass the nested error explicitly to the helpers to fetch codes).

**Comment by gwdp** [comment]
Hello @chrisp-fb,

I do understand your point of been safer to not have this nested error codes, and I do agree with that.
But I'm facing a specific scenario which I do need to identify a graph request timeout. Timeout error comes inside `FBErrorInnerErrorKey`, so fallback to it would fit perfect since there is no `FBErrorParsedJSONResponseKey` keyed object .

**Comment by chrisp-fb** [comment]
Hey, we just shipped v4.0 of the SDK which simplifies the error coding and handling information in the SDK. Check out the new guide at : https://developers.facebook.com/docs/ios/errors
