### ISSUE TITLE
Custom connection timeout

### ISSUE THREAD

**Issue by gwdp** [facebook/facebook-ios-sdk#695]
As well know, Facebook iOS SDK does not let's us change the connection timeout without compiling a custom version. Is there any reason for that ?

For my kind of application (game), waiting for `180` seconds to share something with user waiting and then give him a timeout error is not a good user experience. 
So I do suggest you guys to implement in-memory timeout value so we can change at runtime or something like that.

**Comment by chrisp-fb** [comment]
Good idea, we'll add a work item for it but it's unlikely to be high priority - feel free to submit a pull request if you have time. I could easily see this being a setting like `FBSettings setDefaultConnectionTimeout`

**Comment by kamaljitchakraborty** [comment]
the pan men C  also took the effectivity of the particular which I myself along with the nominee for last 4yrs.and never the less I never use to  take any benifits from that used pan.‎but the so called member of the pan are benficier from the effect which today the nominee is underway A.thanking with,kCCkamaljitchakraborty                                                                                                                                                                                                                                                                          Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                                         From: Chris PanSent: Tuesday 20 January 2015 23:00To: facebook/facebook-ios-sdkReply To: facebook/facebook-ios-sdkSubject: Re: [facebook-ios-sdk] Custom connection timeout (#695)Closed #695.

—Reply to this email directly or view it on GitHub.
