### ISSUE TITLE
FbLikeControl internationalization

### ISSUE THREAD

**Issue by h-code** [facebook/facebook-ios-sdk#697]
Hi 
The FbLikeControl button's social sentence is in english even if both my native app language and device language are not. I guess the locale param is missing in the og:like query.
Moreover when taping on the like button the Like dialog is also in english.

Regards
JM.

**Comment by marmar44** [comment]
That's tight end of this comment.

**Comment by chrisp-fb** [comment]
Hi, we just shipped v4 of the SDK which provides a localization strings file. Can you give that a try and if there's still a problem please file a report to http://developers.facebook.com/bugs . Thanks!
