### ISSUE TITLE
FBDialogs -presentMessageDialogWithParams: doesn't support FBLinkShareParams.friends

### ISSUE THREAD

**Issue by tijoinc** [facebook/facebook-ios-sdk#698]
There's no way to pre-fill the recipients of a message sent in Facebook Messenger via the `FBDialogs` class. You can however send a message to a specific person without using the SDK via the [`messenger://user-thread/{user-id}` URL format](http://stackoverflow.com/a/20320386/3943258), but you can't include an object in that case

Can we _please_ get the ability to send a specific entity to a specific recipient (or recipients)?

**Comment by mikeger** [comment]
This would be very helpful @chrisp-fb @bkelley-fb

**Comment by chrisp-fb** [comment]
Thanks for the feedback. We're evaluating this ability but it's currently not supported for the message dialog. We just released FBSDKMessengerSharerKit which offers a "reply flow" that might be helpful. Check out https://developers.facebook.com/docs/messenger/ios

**Comment by tijoinc** [comment]
I don't think that helps.

**Comment by mikeger** [comment]
@tijoinc +1, I investigated the thing today (both precompiled and open-source parts of SDK), but there is still no way to specify the recipient. I tried to fake it with setting userIDs on `FBSDKMessengerURLHandlerReplyContext`, but this did not help.
Offtopic: why there are no method to share text on `FBSDKMessengerSharer`?
