### ISSUE TITLE
FBPaymentObserver - Potential Memory Leak

### ISSUE THREAD

**Issue by benmarten** [facebook/facebook-ios-sdk#699]
When running Product/Analyze in Xcode 6.1.1 Xcode warns me about a potential Memory Leak!
![2](https://cloud.githubusercontent.com/assets/5960238/5992077/587e374a-aa17-11e4-863a-6a1fd55a00f4.png)

**Comment by chrisp-fb** [comment]
Thanks, we'll look into this.

**Comment by chrisp-fb** [comment]
This is fixed in 3.23, thanks!
