### ISSUE TITLE
[FBDialogs canPresentMessageDialogWithParams] returns NO on iPad

### ISSUE THREAD

**Issue by joshuafeldman** [facebook/facebook-ios-sdk#706]
It seems that on iPad the message dialog returns NO even when the latest version of Facebook Messenger is installed

**Comment by chrisp-fb** [comment]
That's by design: message dialog is not supported for iPad. We're working on it but there's no timeline to provide at this time.

**Comment by joshuafeldman** [comment]
@chrisp-fb oh. I couldn't find anything in the documentation around that. Thank you for clarifying
