### ISSUE TITLE
dialog pops up to portrait on io8

### ISSUE THREAD

**Issue by jminht** [facebook/facebook-ios-sdk#707]
hi, i'm using the latest sdk version(facebook-ios-sdk-3.23.1.pkg) and found a problem.
Facebook dialog cannot set orientation to landscape mode in iOS 8.0, but on iOS 7.1 it works fine. 
My app is forced to landscape mode but Facebook dialog always pops up to portrait mode.
Is there anyone could help me?

**Comment by chrisp-fb** [comment]
Hi. I wasn't able to reproduce the issue on v3 with an app that launches in landscape mode. We did just release v4.0 of the SDK which may resolve the issue; but if you continue to see a problem please file a report at http://developers.facebook.com/bugs .  Thanks!
