### ISSUE TITLE
[FBRequestConnection startForPostOpenGraphObject] returns error with HTTPStatusCode 500

### ISSUE THREAD

**Issue by LisaKonysheva** [facebook/facebook-ios-sdk#708]
I'm getting odd errors when posting Open Graph objects. I'm successfully staging image with [FBRequestConnection startForUploadStagingResourceWithImage...] and then post open graph object with image id from the previous request.
It used to work just fine, but a week ago we've ran into weird sdk behaviour. It works correctly 5 of 10 times, but then i receive an error
"com.facebook.sdk:HTTPStatusCode" = 500;
    "com.facebook.sdk:ParsedJSONResponseKey" =     (
                {
            body =             {
                error =                 {
                    code = 1;
                    message = "An unknown error has occurred.";
                    type = OAuthException;
                };
            };
            code = 500;
        }
);
I've checked errorCategory with FBErrorUtility and got FBErrorCategoryServer. I'm currently using SDK 3.14.1. Please clarify what can cause this errors, it may be really annoying to users when we release our app.

**Comment by LisaKonysheva** [comment]
I've found out that the problem occurred when i set image to open graph object
object[@"image"] = @[@{@"url": [result objectForKey:@"uri"], @"user_generated" : @"true" }];

If I set "false" value to "user_generated" key, everything works fine without error, but I want to share full image and when i set "true", unknown error occurs. Any suggestions?

Thanks in advance

**Comment by chrisp-fb** [comment]
Can you file a bug report at developers.facebook.com/bugs with more code? You can mark the report confidential. Thanks!

**Comment by berilcetin** [comment]
I have the same issue, I was posting open graph objects with user generated photos without any problem. But approximately two weeks ago it started to give me the same error. Also sometimes it gives me error code #100 Unknown object identifier (something like that). Did you find any solution for this? Or is this really an API related bug?

**Comment by LisaKonysheva** [comment]
berilcetin, i've wrote about this issue at developers.facebook.com/bugs and it turned out an API bug, i hope facebook engineers will solve the issue asap https://developers.facebook.com/bugs/1421483708151135/

**Comment by chrisp-fb** [comment]
I've asked for some more information on that specific bug ticket and we can track the issue there. Thanks!

**Comment by berilcetin** [comment]
I don't know how but I was adding Parse framework manually, than I moved it to podfile, and it worked! I think this had something to do with Parse. So it's working now. Thanks anyway.

**Comment by cythb** [comment]
I have the same issue. Could you post your podfile here? Thanks!

**Comment by cythb** [comment]
```
Hi Krishna, I believe I found the source of the error you're experiencing. Could you delay for a few seconds the actions in between staging the image and publishing the object to the graph? A small delay in between creating the object and publishing the story would also be recommended.

What is happening is a race condition in between these steps. I was reproducing by creating these 3 things in each other's callbacks. By separating them and just waiting a few seconds, my action was successfully created.

Please let me know of your findings.
Alan
```

**Comment by berilcetin** [comment]
Here's my podfile

pod 'FBSDKCoreKit'
pod 'FBSDKShareKit'
pod 'FBSDKLoginKit'
pod 'SDWebImage'
pod 'FlickrKit'
pod 'Parse'
pod 'ParseUI'
pod 'ParseFacebookUtilsV4'

pod 'AWSCore'
pod 'AWSAutoScaling'
pod 'AWSCloudWatch'
pod 'AWSDynamoDB'
pod 'AWSEC2'
pod 'AWSElasticLoadBalancing'
pod 'AWSKinesis'
pod 'AWSS3'
pod 'AWSSES'
pod 'AWSSimpleDB'
pod 'AWSSNS'
pod 'AWSSQS'

**Comment by cythb** [comment]
Thanks you @berllcetln . I temporarily fix this issue by change user_generated to false from true 

```
object[@"image"] = @[@{@"url": [result objectForKey:@"uri"], @"user_generated" : @"false" }];
```

**Comment by berilcetin** [comment]
I've updated the SDK to 4, and it is solved, I can post the user generated
photo, but not by adding it to open graph object but to open graph action.
If I add it to open graph object it still gives me the same error "Could
not resolve object". But adding it to open graph action solved my problem.
