### ISSUE TITLE
v3.23.1 is missing in Cocoapods

### ISSUE THREAD

**Issue by kamoljan** [facebook/facebook-ios-sdk#709]
Hi guys

v3.23.1 is already available in the [Facebook Developers page](https://developers.facebook.com/docs/ios).
However, it is not yet in [Cocoapods](http://cocoapods.org/).

Any plan to update Cocoapods with your latest version?

Best regards
Kamol

**Comment by chrisp-fb** [comment]
Good catch. I've pushed the update to pods trunk and it should show up shortly. Thanks!

**Comment by kamoljan** [comment]
@chrisp-fb thank you!
