### ISSUE TITLE
FBCacheIndex EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by robertodias180** [facebook/facebook-ios-sdk#710]
Got this crash on my app, is it my fault? or is an API bug? 

thanks in advance.

Crashed: Data Cache queue
EXC_BAD_ACCESS KERN_PROTECTION_FAILURE at 0x00000001947d4d80

Thread : Crashed: Data Cache queue
0  ???                            0x00000001947d4d80 
1  APP                 0x0000000100299198 initializeStatement (FBCacheIndex.m:90)
2  APP                0x0000000100299b50 -[FBCacheIndex _fetchCurrentDiskUsage] (FBCacheIndex.m:516)
3  libdispatch.dylib              0x0000000193835994 _dispatch_call_block_and_release + 24
4  libdispatch.dylib              0x0000000193835954 _dispatch_client_callout + 16
5  libdispatch.dylib              0x00000001938400a4 _dispatch_queue_drain + 1448
6  libdispatch.dylib              0x0000000193838a5c _dispatch_queue_invoke + 132
7  libdispatch.dylib              0x0000000193842318 _dispatch_root_queue_drain + 720
8  libdispatch.dylib              0x0000000193843c4c _dispatch_worker_thread3 + 108
9  libsystem_pthread.dylib        0x0000000193a1522c _pthread_wqthread + 816

**Comment by chrisp-fb** [comment]
Hi, we just shipped v4.0 of the SDK where this should not be a problem. If you do see more problems, please file a bug at developers.facebook.com/bugs. Thanks!
