### ISSUE TITLE
FBSession - no way to determine if the reauthorizeHandler has been cleared on session

### ISSUE THREAD

**Issue by SilkyPantsDan** [facebook/facebook-ios-sdk#711]
If reauthorizeWithPermissions is called multiple times before FBSession.reauthorizeHandler is cleared, an exception is raised by the SDK.

 Should there be a way to determine that the active session has a reauthorize call in progress?

FBSession.m Line 1772.

```
    if (self.reauthorizeHandler) {
        // block must be cleared (meaning it has been called back) before a reauthorize can happen again
        [[NSException exceptionWithName:FBInvalidOperationException
                                 reason:@"FBSession: It is not valid to reauthorize while a previous "
          @"reauthorize call has not yet completed."
                               userInfo:nil]
         raise];
    }
```

**Comment by chrisp-fb** [comment]
Thanks for the feedback - We just shipped v4.0 of the SDK where this is no longer an issue as the login programming model has been updated.
