### ISSUE TITLE
FBSDKMessengerShareKit not present.

### ISSUE THREAD

**Issue by jlorich** [facebook/facebook-ios-sdk#712]
It's referenced in documentation and included in the package download from the website, but not included here and therefore not included for cocoapods usage.

**Comment by ejel** [comment]
Same issue here. The SDK downloaded directly from Facebook Developer does include the framework though.

**Comment by chrisp-fb** [comment]
Sorry, FBSDKMessengerShareKit is not available on Github or Cocoapods at this time. For now you'll have to download the pkg and link the .framework directly.

**Comment by rromanchuk** [comment]
this again :(

**Comment by ejel** [comment]
Is there an estimated timeline when it will be available in Github?

**Comment by chrisp-fb** [comment]
I'm happy to say FBSDKMessengerShareKit is now available in its own folder in this repository with today's release, and also is available on Cocoapods (use `pod 'FBSDKMessengerShareKit'`).
