### ISSUE TITLE
Error 304 while login

### ISSUE THREAD

**Issue by iamabhiee** [facebook/facebook-ios-sdk#713]
I have recently upgraded to SDK 4.0

While login using following code 

FBSDKLoginManager *login = [[FBSDKLoginManager alloc] init];
    [login logInWithReadPermissions:@[@"email"] handler:^(FBSDKLoginManagerLoginResult *result, NSError *error) {

}];

I am getting following error

Error Domain=com.facebook.sdk.login Code=304 "The operation couldn’t be completed. (com.facebook.sdk.login error 304.)"

Can anyone help me to figure out what wrong I am doing here?

**Comment by Andr3y-** [comment]
I had exactly the same problem.

After initialising a FBSDKLoginManager, add this line

[login logOut];

This will flush out all the data (and token) Facebook SDK has.

**Comment by carlos90g** [comment]
Thanks @Andr3y- this worked perfectly for me!

**Comment by chrisp-fb** [comment]
Hi,

 Code 304 corresponds to FBSDKLoginUserMismatchErrorCode which implies the request for new permissions was for a different user. For example, if the current user token is for user A, and you request "email" which triggers the app switch to the native Facebook app for authorization. If user B is logged into the Facebook app, you will see this error. The suggested workaround of logging out before each call means you all your login calls will act as if it is a first login and not [perform a re-request for declined permisions](https://developers.facebook.com/docs/facebook-login/login-flow-for-web#re-asking-declined-permissions). Instead, you should just call logout in case of the error and then dispatch another call to start a new login. We're working to improve this experience but it is a rare case.

 To learn more about errors, check out https://developers.facebook.com/docs/ios/errors

**Comment by aubada-taljo** [comment]
@Andr3y- Thank you, it solved the same issue for me :)

**Comment by Nsurajit** [comment]
Thnks ,
After initialising FBSDKLoginManager, add this line

[FBSDKLoginManagerInstance logOut];
problem solved
