### ISSUE TITLE
Get reference of facebook access token

### ISSUE THREAD

**Issue by oddpandadesign** [facebook/facebook-ios-sdk#714]
I have been using Facebook's login functionality to link to AWS Cognito system. To link them you require the String of Facebook's access token. Prior to version 4.0 I used

NSString *facebookToken = FBSession.activeSession.accessTokenData.accessToken;

Since the update this no longer works. I tried

NSString *facebookToken = FBSDKAccessTokenChangeNewKey;

But this also didn't work. Any suggestions? I can't find it in the reference guide or sample projects.

**Comment by toddkrabach** [comment]
FBSession has been removed in v4.0 of the SDK.  If you need access to the access token string, you can get that from

  [FBSDKAccessToken currentAccessToken].tokenString
