### ISSUE TITLE
FBSDK'type'Kit/FBSDK'type'Kit.h file not found, swift cocoapods

### ISSUE THREAD

**Issue by LightD** [facebook/facebook-ios-sdk#716]
I integrated Facebook-iOs-SDK 4.0 with my swift iOs project through cocoapods.. and in my bridging header (which is working because other libraries are working fine), I added `#import <FBSDKCoreKit/FBSDKCoreKit.h>`.. when I compile it says that `FBSDKCoreKit/FBSDKCoreKit.h file not found`.. I also tried with `LoginKit`, same result.. I'm not really sure what's the problem, or if i'm doing something wrong.. but from my point of view, it's not working, so I'm asking here!

**Comment by alexperezpaya** [comment]
Same here :/

**Comment by adamsinger** [comment]
Do you have `use_frameworks!` on in your Podfile? I've found that my build fails when `use_frameworks!` is on, but succeeds when it isn't.

**Comment by tomoueda** [comment]
I have the same issue. Deleting "use_frameworks!" break other dependencies.

**Comment by LightD** [comment]
@adamsinger yes I do have `use_frameworks!` in my Podfile..

**Comment by te-chris** [comment]
I've just run into this too

**Comment by LightD** [comment]
Not Only cocoapods actually.. I've been trying the whole day to get this to work.. I tried installing the frameworks from the website.. and I tried compiling the project.. both didn't work.. when you have a sw2ift project it just doesn't want to work.. 
P.S: Bolts framework is working perfectly.. but whatever FBSDKTypeKit .. that's not working..

**Comment by chrisp-fb** [comment]
Thanks for the feedback, we're looking into it.

**Comment by chrisp-fb** [comment]
I commented on https://github.com/facebook/facebook-ios-sdk/issues/725 which sounds like the same issue. The Facebook SDK is a static library and should not use the `use_frameworks!` flag. If you do have swift framework dependencies, you should be able to traditionally link to the downloadable frameworks instead of using Cocoapods to integrate with the Facebook SDK.

**Comment by chrisp-fb** [comment]
Closing this issue - Note I provided new workaround podspecs in https://github.com/facebook/facebook-ios-sdk/issues/725 that you can use.
