### ISSUE TITLE
FBSDKSharePhoto not showing fallback dialog

### ISSUE THREAD

**Issue by alexandre-g** [facebook/facebook-ios-sdk#717]
FBSDKSharePhoto *photo = [[FBSDKSharePhoto alloc] init];
                                           photo.image = sender.cellImageView.image;
                                           photo.userGenerated = YES;
                                           FBSDKSharePhotoContent *content = [[FBSDKSharePhotoContent alloc] init];
                                           content.photos = @[photo];

                                       [FBSDKShareDialog showFromViewController:self
                                                                    withContent:content
                                                                       delegate:nil];

The above code works when Facebook App is installed on device, but does nothing when it isn't.

From SDK Documentation:
"The Share Dialog switches to the native Facebook for iOS app, then returns control to your app after a post is published. If someone doesn't have Facebook app installed it will automatically falls back to a web-based dialog."

**Comment by toddkrabach** [comment]
Sharing photos (or any other binary uploads) through the web dialog is currently not supported.  The delegate will be messaged if the content cannot be shared, or you can create an instance of FBSDKShareDialog and use the validateWithError: method to check the content first, if desired.
