### ISSUE TITLE
fix broken submodule

### ISSUE THREAD

**Issue by rodrigocollavo** [facebook/facebook-ios-sdk#719]
the submodule at ./vendor/ios-snapshot-test-case @ 4ba2d0c, is broken. The commit is not part of the master anymore.

**Comment by chrisp-fb** [comment]
What error are you seeing? I'm able to see 4ba2d0c just fine within our submodule and when I clone https://github.com/facebook/ios-snapshot-test-case

**Comment by chrisp-fb** [comment]
Feel free to reopen if you have more details.
