### ISSUE TITLE
'../FBSDKMath.h' file not found

### ISSUE THREAD

**Issue by winzig** [facebook/facebook-ios-sdk#722]
Trying to use the 4.x Facebook SDK in Version 6.3 (6D554n), in a Swift project (so Swift 1.2). I have `use_frameworks!` on in my Podfile. 

When I try to build my project, I get this error:

`.../Pods/Facebook-iOS-SDK/FBSDKCoreKit/FBSDKCoreKit/Internal/UI/FBSDKUIUtility.h:23:9: '../FBSDKMath.h' file not found`

Any ideas?

**Comment by ninjudd** [comment]
I'm encountering this same error.

**Comment by ninjudd** [comment]
Actually, I get the issue described in #716 first, then when I click "Validate Project Settings, Update to recommended settings", I get this error.

I am using CocoaPods version `0.36.3` and `use_frameworks!`, which is necessary to use Cartography.

**Comment by ninjudd** [comment]
FYI, I just installed the SDK manually instead of via CocoaPods, and that worked.

**Comment by aie0** [comment]
me too but with different file - "AppEvents/FBSDKAppEvents+Internal.h"

**Comment by chrisp-fb** [comment]
I commented on https://github.com/facebook/facebook-ios-sdk/issues/725 which sounds like mostly the same issue - you shouldn't use the use_frameworks! flag with the Facebook SDK. If you do have swift dependencies, @ninjudd 's suggestion to use the traditional method of linking to the downloaded libraries should work.

**Comment by chrisp-fb** [comment]
Closing in favor of https://github.com/facebook/facebook-ios-sdk/issues/725 (Note I provided some new podspecs in that thread you can use as a workaround)
