### ISSUE TITLE
Possible bug: video upload - FB SDK 4.0.0

### ISSUE THREAD

**Issue by tarokker** [facebook/facebook-ios-sdk#724]
Hi,
I cannot understand if i'm doing something wrong or there is a wrong condition in the SDK.
I'm trying to upload a video with latest (4.0.0) SDK, using the following lines:

```
        FBSDKShareVideo *video = [FBSDKShareVideo videoWithVideoURL:<my local file NSURL>];
        FBSDKShareVideoContent *content = [[FBSDKShareVideoContent alloc] init];
        content.video = video;
        [FBSDKShareDialog showFromViewController:self withContent:content delegate:self];
```
I'm using a local mp4 file saved in the application cache sandbox folder.
The SDK blocks me with the error: 
"Only asset file URLs are allowed for the native dialog."
Going deeper in the SDK sources, I found it matches the condition in the file "FBSDKShareKit/FBSDKShareKit/FBSDKShareDialog.m" (line 551 - function '- (BOOL)_validateShareContentForNative:(NSError **)errorRef' )

I don't understand if this condition is wrong or what:
```
if (((FBSDKShareVideoContent *)shareContent).video.videoURL.isFileURL) {
```

This is the NSURL i'm trying to use:
```
    NSURL *exportURL = [NSURL fileURLWithPathComponents:[NSArray arrayWithObjects:
                               [NSSearchPathForDirectoriesInDomains(NSCachesDirectory, NSUserDomainMask, YES) lastObject],@"final.mp4",
                               nil]];
```

What kind of NSURL does the SDK expect?

By the way, negating the condition worked perfectly.
Is this a bug or am I doing someting wrong?

Thanks in advance.
Regards.

**Comment by tarokker** [comment]
This is the NSURL i'm trying to use:
```
    NSURL *exportURL = [NSURL fileURLWithPathComponents:[NSArray arrayWithObjects:
                               [NSSearchPathForDirectoriesInDomains(NSCachesDirectory, NSUserDomainMask, YES) lastObject],@"final.mp4",
                               nil]];
```

**Comment by toddkrabach** [comment]
Videos must be in the asset library at this point, so the URL must be an asset URL.  You can get a video asset URL from UIImagePickerController, as an example.

You can export your video from your app into the asset library using ALAssetsLibrary writeVideoAtPathToSavedPhotosAlbum:completionBlock:, which will return the asset URL in the completionBlock.

**Comment by tarokker** [comment]
Hi, thanks for your time and kind answer.
I'm just curious: is there a reason for this? (some kind of policy from Apple / Facebook)

**Comment by toddkrabach** [comment]
Media files stored on disk cannot be accessed from one app sandbox to another, so in order for the Facebook app to access the video it needs to be located somewhere that is accessible by both your app and the Facebook app.  We are experimenting with some other options that will allow video sharing without this requirement, so keep an eye out on future releases for additional video sharing features.

**Comment by Francescu** [comment]
AssetLibrary is now deprecated (iOS9).
