### ISSUE TITLE
podspec with Facebook-iOS-SDK dependency fails

### ISSUE THREAD

**Issue by magus** [facebook/facebook-ios-sdk#726]
Ran into an issue today trying to build a simple pob library, the issue repros for the example pod library. Not sure if this is a pod bug.

```sh
pod lib create podtest
```

Add `s.dependency "Facebook-iOS-SDK", "~> 4.0.1"` to the podspec

```sh
pod lib lint
```

```

 -> podtest (0.1.0)
    - WARN  | The summary is not meaningful.
    - WARN  | The description is not meaningful.
    - WARN  | There was a problem validating the URL https://github.com/<GITHUB_USERNAME>/podtest.
    - ERROR | [iOS] Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - NOTE  | [iOS]  Facebook-iOS-SDK/FBSDKCoreKit/FBSDKCoreKit/Internal/FBSDKCoreKit+Internal.h:23:9: fatal error: 'AppEvents/FBSDKAppEvents+Internal.h' file not found
    - ERROR | [iOS] The `source_files` pattern did not match any file.

[!] podtest did not pass validation.
You can use the `--no-clean` option to inspect any issue.
```

> `- NOTE  | [iOS]  Facebook-iOS-SDK/FBSDKCoreKit/FBSDKCoreKit/Internal/FBSDKCoreKit+Internal.h:23:9: fatal error: 'AppEvents/FBSDKAppEvents+Internal.h' file not found`

**Comment by lum7671** [comment]
I have same Issue.
> - NOTE | [iOS] Facebook-iOS-SDK/FBSDKCoreKit/FBSDKCoreKit/Internal/FBSDKCoreKit+Internal.h:23:9: fatal error: 'AppEvents/FBSDKAppEvents+Internal.h' file not found

**Comment by lum7671** [comment]
I try to adding "internal header" on Pods.xcodeprj
but, it's not completed The issue. Pods.xcodeprj is initializing by Pods's update.
 
> Facebook - User Search Header Paths : ${PODS_ROOT}/Facebook-iOS-SDK/FBSDKCoreKit/FBSDKCoreKit/Internal/UI ${PODS_ROOT}/Facebook-iOS-SDK/FBSDKCoreKit/FBSDKCoreKit/Internal

**Comment by chrisp-fb** [comment]
There was some change in behavior with cocoapods 0.36.3 where our podspec is no longer linting. We're working on a fix on that. If you still have 0.35.0 installed, you can try that (i.e., `pod _0.35.0_ ...`)

**Comment by lum7671** [comment]
First, Thank you for rapidly response. :-)
but, The error still occurs.

% pod --version
0.36.3

![Error Image](https://lum7671.files.wordpress.com/2015/04/ec8aa4ed81aceba6b0ec83b7-2015-04-10-ec98a4eca084-10-40-42.png)

**Comment by chrisp-fb** [comment]
Closing in favor of https://github.com/facebook/facebook-ios-sdk/issues/725 - I added new podspecs mentioned in that thread you can use as a workaround until we push them officially in our next release.
