### ISSUE TITLE
FBSDKLogin Documentation??

### ISSUE THREAD

**Issue by sneakyness** [facebook/facebook-ios-sdk#727]
Is it just me or is there nothing here? https://developers.facebook.com/docs/reference/ios/current/class/FBSDKLoginManager/

**Comment by chrisp-fb** [comment]
What browser are you using, and are you logged into Facebook? The content is there. Are you able to see other docs or if you pick a specific version (e.g., https://developers.facebook.com/docs/reference/ios/4.0/class/FBSDKLoginManager/ )?

**Comment by chrisp-fb** [comment]
Closing - if you still see problems, feel free to reopen or file a report to developers.facebook.com/bugs

If you installed the SDK via the .pkg installer, the docset should be installed in your Xcode documentation also.

**Comment by sneakyness** [comment]
Didn't see this, I don't remember seeing anything for a solid 2 weeks. Perhaps the /current/ was broken? 

Related: if you look at classes from 3.x, and click on the "go to current version" link at the top, it just takes you to a broken search page. In a perfect world, it would be nice to see which old classes correspond with the new ones. Ex: https://developers.facebook.com/docs/reference/ios/3.8/class/FBAccessTokenData/

Thanks
