### ISSUE TITLE
Change text (title) of FBSDKLoginButton

### ISSUE THREAD

**Issue by mariopavlovic** [facebook/facebook-ios-sdk#728]
In v3.X there was ability to define resource bundle that overrides localised text in SDK (via `[FBSettings setResourceBundleName:@"FacebookSDKOverrides"];`). I don't see the option in v4.X. Is it removed from SDK, migrated to some other class or is it just not possible anymore?

How can I set custom text in `FBSDKLoginButton`?

**Comment by chrisp-fb** [comment]
You can localize the FacebookSDK.strings file provided in the pkg, https://developers.facebook.com/docs/ios/troubleshooting#localize . I'll call this out better in the upgrade guide.
