### ISSUE TITLE
CoreKit Configuration Build Warning

### ISSUE THREAD

**Issue by calebd** [facebook/facebook-ios-sdk#729]
Including the `CoreKit` subspec causes all CoreKit headers to be added to the project twice. This triggers a build warning in Xcode 6.3. I believe [this line](https://github.com/facebook/facebook-ios-sdk/blob/master/Facebook-iOS-SDK.podspec#L38) should simply be `sp.source_files = "FBSDKCoreKit/FBSDKCoreKit/Internal/FBSDKDynamicFrameworkLoader.m"` since that is the only file affected by the `CoreKit/no-arc` subspec.

**Comment by chrisp-fb** [comment]
Hi. Thanks for the pull request too. Which version of cocoapods are you using? I think some behavior changed in 0.36.3 (possibly noted in https://github.com/CocoaPods/CocoaPods/issues/3246 ) because the podspec no longer lints with 0.36.3 (but lints in 0.35). Have you tried linting and consuming your pull request's change?

**Comment by calebd** [comment]
I couldn't tell if it was CocoaPods 0.36.3 or Facebook iOS SDK 4.0.1 that broke it since I updated both around the same time. I am not using `use_frameworks!`.

The only part of the Facebook iOS SDK that I am using is the `CoreKit` subspec and, after my change, it can be linted without issue.

```
FacebookSDK (master) -> pod spec lint --subspec="Facebook-iOS-SDK/CoreKit"

 -> Facebook-iOS-SDK/CoreKit (4.0.1)

Analyzed 1 podspec.

Facebook-iOS-SDK.podspec passed validation.
```

**Comment by calebd** [comment]
It's fine if this ends up being a CocoaPods issue. I have never used subspecs inside subspecs so I'm not sure what the best solution is. I do know that the proposed change does install the proper files and build without issue.

**Comment by chrisp-fb** [comment]
Ah, it does lint for the subspec but not for the whole spec. We'll hold off on your PR as we'll be making some changes to support the use_frameworks case properly anyway, but I'm glad you have a workaround for yourself.

**Comment by chrisp-fb** [comment]
Closing in favor of https://github.com/facebook/facebook-ios-sdk/issues/725 - We're going to push per kit podspecs in the next release which will resolve this issue. I went ahead and pushed the FBSDKCoreKit podspec for 4.0.1 so you should be able to use that immediately.
