### ISSUE TITLE
weak delegate reference destroyed prematurely in _shareOpenGraphContent

### ISSUE THREAD

**Issue by clowestab** [facebook/facebook-ios-sdk#732]
I am transitioning over to the newest API and encountered an issue whereby although my posts were visible on Facebook, I was not receiving any delegate calls to inform me of the success.

On investigating it would seem that the delegate is no longer set within the FBSDKGraphRequestHandler contained within the stagingHandler block in the _shareOpenGraphContent method of FBSDKShareAPI.m

Now.. I don't have much experience with Objective C but I believe that whilst the delegate is captured within the block, it is not captured within the FBSDKGraphRequestHandler. As it is held as a weak reference and the request is executed asynchronously.. I assume the reference is destroyed.

I have fixed this for now by just saving a reference to the delegate inside of stagingHandler:
id<FBSDKSharingDelegate> del = _delegate;

Could someone confirm this as a bug, and verify my understanding?

Thanks

**Comment by chrisp-fb** [comment]
Can you provide more code details describing your problem. In general, delegates are intentionally weakly referenced to avoid retain cycles. See https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/MemoryMgmt/Articles/mmPractical.html for more information on that topic.

It is a very common pattern to have something like:
Class A owns Class B which has a weak reference to class A as its delegate (i.e., `b.delegate = a`). It is A's responsibility to nil out the delegate reference if it gets deallocated (i.e., in A's `dealloc`, it should have `b.delegate = nil`).

**Comment by clowestab** [comment]
Hi Chris,

I understand the need for the weak reference. My confusion is as to why the delegate is seemly deallocated before it should be.

An example:
```
let content: FBSDKShareOpenGraphContent = FBSDKShareOpenGraphContent()
        content.action = FBSDKShareOpenGraphAction(type: graphModel.actionName, objectURL: NSURL(string: linkUrl), key: graphModel.propertyName)
        content.previewPropertyName = graphModel.propertyName
        
        let share = FBSDKShareAPI.shareWithContent(content, delegate: self)
```

This swift code posts the action to Facebook but the delegate method `didCompleteWithResults` is not called.

This happens because on line 192 of https://github.com/facebook/facebook-ios-sdk/blob/master/FBSDKShareKit/FBSDKShareKit/FBSDKShareAPI.m the method returns as the delegate is nil. 

The issue is as to why the delegate is nil here?
Plausibly something to do with how Swift bridges from Objective-C?

**Comment by toddkrabach** [comment]
In this case, the delegate is your class (self in your code snippet).  FBSDKShareAPI makes potentially multiple network requests before completing and does not hold a strong reference to the delegate, so it is up to you to ensure that it lives beyond the network requests if it is still interested in the result.
