### ISSUE TITLE
FBSDKMessengerURLHandlerCancelShareContext.o doesn't exist within FBSDKMessengerShareKit.a

### ISSUE THREAD

**Issue by SotoiGhost** [facebook/facebook-ios-sdk#733]
Well, I don't know certainly, where to put this issue but…

In the FBSDKMessengerKit.a file within FBSDKMessengerKit.framework that you can download from the official site, it doesn't contain the class `FBSDKMessengerURLHandlerCancelShareContext`. Here is the proof:
![screen shot 2015-04-10 at 3 24 44 pm](https://cloud.githubusercontent.com/assets/5924210/7096911/e6141854-df96-11e4-86d3-06210c4d614b.png)

I searched for `FBSDKMessengerURLHandlerCancel` to see if I could find some symbol for `FBSDKMessengerURLHandlerCancelShareContext`, but it just throw me the `FBSDKMessengerURLHandlerCancelContext.o`:
![screen shot 2015-04-10 at 3 25 38 pm](https://cloud.githubusercontent.com/assets/5924210/7096914/ec2e7a04-df96-11e4-86de-f2c7a5331dfa.png)

**Comment by chrisp-fb** [comment]
Thanks! We're looking into it.

**Comment by chrisp-fb** [comment]
Thanks for the feedback, we'll fix this for the next release. You should be able to use the `FBSDKMessengerURLHandlerCancelContext` class instead (you'll have to explicitly import its header).

**Comment by chrisp-fb** [comment]
This is now fixed with FBSDKMessengerShareKit v1.2.1 which was just released with v4.1.0 of the main SDKs. Thanks!
