### ISSUE TITLE
Crash on -[FBSDKShareUtility buildWebShareContent:methodName:parameters:error:] when building the FBSDKShareOpenGraphAction using the +actionWithType:objectURL:key: convenience method

### ISSUE THREAD

**Issue by matiaspan** [facebook/facebook-ios-sdk#735]
My app attempts to share this way

    FBSDKShareOpenGraphAction *action = [FBSDKShareOpenGraphAction actionWithType:@"edited-type" objectURL:[NSURL URLWithString:associate.shareFullURL] key:@"edited-key"];
    
    FBSDKShareOpenGraphContent *content = [[FBSDKShareOpenGraphContent alloc] init];
    content.action = action;
    content.previewPropertyName = @"edited";

    UIViewController *controller = someController;
    
    FBSDKShareDialog *dialog = [FBSDKShareDialog showFromViewController:controller withContent:content delegate:(id<FBSDKSharingDelegate>)self];

When the SDK tries to serialize the action into JSON the url fails to serialize and makes the resulting string nil, which in turn crashes the app at [FBSDKShareUtility buildWebShareContent:methodName:parameters:error:] + 494

**Comment by toddkrabach** [comment]
this will be resolved in the next release

**Comment by toddkrabach** [comment]
in the meantime, you can create your action with an NSString instead of NSURL:

```
FBSDKShareOpenGraphAction *action = [[FBSDKShareOpenGraphAction alloc] init];
action.actionType = @"edited-type";
[action setString:associate.shareFullURL forKey:@"edited-key"];
```

or, you can even pass it in as if it were an objectID:

```
FBSDKShareOpenGraphAction *action = [FBSDKShareOpenGraphAction actionWithType:@"edited-type"
                                                                     objectID:associate.shareFullURL
                                                                          key:@"edited-key"];
```
