### ISSUE TITLE
Apple review warning when submitting to App Store: "application references non public selectors"

### ISSUE THREAD

**Issue by awidgery** [facebook/facebook-ios-sdk#738]
We've just updated an app to SDK 4.0.1 and submitted, and when we did so we got a warning from Apple that "application references non public selectors".

It doesn't say what selectors.

When the SDK is removed the error disappears, so we're sure it's the FB SDK.

We are using two FB frameworks - FBSDKCore and FBSDKLogin included in the latest FB iOS SDK.

App is currently awaiting review so we don't know if it'll get approved or not - but the warning is worrying. Any ideas why it shows up?

**Comment by Reflejo** [comment]
I wouldn't worry too much about it. It probably means that some method / property matches the name of an internal cocoa method and the static analyzer gets confused.

**Comment by chrisp-fb** [comment]
That's odd, usually it will describe the selector(s) that are problematic. We haven't had any other reports with the SDK and my own app archive pass Xcode (6.3) validation. Feel free to reopen if you get more information.
