### ISSUE TITLE
FacebookSDK not found, linker error (Swift)

### ISSUE THREAD

**Issue by panquish** [facebook/facebook-ios-sdk#740]
Hey guys,
I'm using the latest Facebook SDK in a Swift project. To include the SDK, I did follow the guides in ticket #725.

Now when I build my application on the Simulator everything works fine, but when I try to build on my iPhone I get the following error:
```
ld: framework not found FacebookSDK
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
My Podfile looks like this:
```
platform :ios, '8.0'
use_frameworks!

target 'EasyGo' do
  pod 'FBSDKCoreKit', :git => 'https://github.com/facebook/facebook-ios-sdk.git', :branch => 'dev'
  pod 'FBSDKShareKit', :git => 'https://github.com/facebook/facebook-ios-sdk.git', :branch => 'dev'
  pod 'FBSDKLoginKit', :git => 'https://github.com/facebook/facebook-ios-sdk.git', :branch => 'dev'

  pod 'Alamofire'
  pod 'SwiftyUserDefaults'
  pod 'KeychainAccess'
  pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git', :branch => 'xcode6.3'
  pod 'ObjectMapper'
  pod 'SVPullToRefresh'
  pod 'JSONHelper'
  pod 'Charts', '~> 2.0'
  pod 'OpenBLE', '~> 1.0'
end
```

When I search for FacebookSDK in my project I still find it under "Other Linker Flags". There I can't edit the flags. Only add new ones but I can't delete any linked flags.
I already tried to remove and reinstall all pods, but the error is still coming.

Thanks for your help.

Greetings
Daniel

**Comment by chrisp-fb** [comment]
I'm not able to reproduce any problems using your podfile on a new project (pods 0.37.0.beta.1 ). Maybe there's some pods issue similar to https://github.com/CocoaPods/CocoaPods/issues/1823 . I suggest you try to isolate the variable, or provide more information, and file a report with them, or it sounds like you could just manually remove that linker flag from the pods generated xcconfig file and move on.
