### ISSUE TITLE
How can you trigger a logout via code ?

### ISSUE THREAD

**Issue by chrisribe** [facebook/facebook-ios-sdk#741]
I am trying to figure out how to trigger a logout via code.
Please help.

**Comment by chrisp-fb** [comment]
You can use `-[FBSDKLoginManager logOut]`

**Comment by chrisribe** [comment]
Hi,

Yes I found that in the sdk source while searching but it did nothing for me.
I had to clear the activeSession token infos like this.

[[[FBSDKLoginManager alloc] init] logOut];
[FBSession.activeSession closeAndClearTokenInformation];

Now the FBLoginView button changes state and its text changes back to "Login with Facebook"
Thanks

**Comment by chrisp-fb** [comment]
You don't need to use FBSession at all. v4 of the Facebook SDK (which is comprised of the FBSDK* types) can completely replace v3.x of the SDK. You can learn more at https://developers.facebook.com/docs/ios/upgrading-4.x#3to4

**Comment by chrisribe** [comment]
Well I am using the v4 of the sdk (2015-04-02 pkg) but I am integrating it to an old project, so maybe there is something odd in the code.

Thanks again
