### ISSUE TITLE
Sometimes app crashes on trying to set a nil appID in a dictionary

### ISSUE THREAD

**Issue by alistra** [facebook/facebook-ios-sdk#742]
The app sometimes crashes upon clicking the login button from FBSDK.

The appID was always in the info.plist during that time. In fact it crashed once and then it was working all the next times.

It has to be a bug in the macro, or sometimes the method just returns nil?

A fix would be adding a nil guard.

http://crashes.to/s/b97a8a33e01

**Comment by chrisp-fb** [comment]
Strange. I'm not able to the reproduce the issue; if you continue to see problems can you submit a report to developers.facebook.com/bugs with additional details such as how you are calling the login manager, if you're calling [FBSDKSettings setAppID] anywhere, or if you have unique modifications to your plist file (or any localizations). Thanks.
