### ISSUE TITLE
KNFacebookSharePhoto use imageURL can't share.

### ISSUE THREAD

**Issue by kick9game** [facebook/facebook-ios-sdk#743]
FBSDKShareDialog *shareDialog = [[FBSDKShareDialog alloc] init];
    FBSDKSharePhotoContent *content = [[FBSDKSharePhotoContent alloc] init];
    FBSDKSharePhoto *sharePhoto = [[FBSDKSharePhoto alloc] init];
          sharePhoto.imageURL = [NSURL URLWithString:@"http://shareitexampleapp.parseapp.com/images/viking.png"];
    sharePhoto.userGenerated = NO;
    content.photos = @[sharePhoto];
    shareDialog.shareContent = content;
    [shareDialog show];

It doesn't work.

but when i use  sharePhoto.image = [UIImage imageNamed:@"test.png"];,it works ok.

**Comment by divyaappfusion1** [comment]
Working file at my end         

   FBSDKSharePhoto *photo = [[FBSDKSharePhoto alloc] init];
            photo.image = image;
            photo.userGenerated = YES;
            FBSDKSharePhotoContent *content = [[FBSDKSharePhotoContent alloc] init];
            content.photos = @[photo];
            
            FBSDKShareDialog *shareDialog = [[FBSDKShareDialog alloc]init];
            shareDialog.delegate = self;
            shareDialog.shareContent = content;
            [shareDialog show];

**Comment by kick9game** [comment]
@divyaappfusion1 
can you replace " photo.image = image; " by "photo.imageURL = [NSURL URLWithString:@"http://shareitexampleapp.parseapp.com/images/viking.png"]; " and try it again?
