### ISSUE TITLE
Problem with alignment

### ISSUE THREAD

**Issue by sergioribeiro** [facebook/facebook-ios-sdk#746]
After the last Xamarin Studio update the Facebook Component Elements suddenly started to appear aligned to the right.

**Comment by chrisp-fb** [comment]
Can you file a report to developers.facebook.com/bugs with details like Xamarin version, and possibly screenshots? Thanks.

**Comment by sergioribeiro** [comment]
Hi,

I don’t know why you asked me to file the report there. It seems to me that the problem is in the component or in Xamarin Studio.
But anyway, I filed it under https://developers.facebook.com/bugs/798627966859311/

Thanks,
Sergio

From:  Chris Pan
Reply-To:  facebook/facebook-ios-sdk
Date:  Thursday, April 30, 2015 at 2:29 PM
To:  facebook/facebook-ios-sdk
Cc:  Sergio Schirmer
Subject:  Re: [facebook-ios-sdk] Problem with alignment (#746)


Can you file a report to developers.facebook.com/bugs with details like Xamarin version, and possibly screenshots? Thanks.

**Comment by chrisp-fb** [comment]
> I don’t know why you asked me to file the report there. It seems to me that the problem is in the component or in Xamarin Studio.

I see. I'm not familiar with Xamarin and wasn't sure why you opened this issue either. In general, filing a report to the bugs tool gets it routed to someone who may be better able to help. Anyway, let me know if there's something you think we can do here.
