### ISSUE TITLE
access_token returned from app not valid on server

### ISSUE THREAD

**Issue by sebbean** [facebook/facebook-ios-sdk#754]
I have a rails app using sorcery that has fully functional oauth login: http://zoanapp.herokuapp.com/
oauth pass off and callback successful.

When I send the access token returned from FBSDKLoginButton callback to the rails server for authentication, I receive:
```OAuth2::Error (:
{"error":{"message":"Invalid verification code format.","type":"OAuthException","code":100}}):
  app/controllers/oauths_controller.rb:11:in `callback'```

``` 
  config.facebook.access_permissions = ["email"]
  config.facebook.display            = "page"
  config.facebook.api_version        = "v2.3"
```
matches:
```        
fbLoginButton.readPermissions = [ "email" ]
```

I've been banging my head against the wall for quite a while on this, no clue what the issue is.

**Comment by jumph4x** [comment]
:+1 been working on this for a while, no idea what could possibly be causing this.

**Comment by sebbean** [comment]
:+1:

**Comment by chrisp-fb** [comment]
This doesn't sound like an issue with the iOS SDK. Can you file a report to developers.facebook.com/bugs ? You could also try using the Graph API explorer to test the token https://developers.facebook.com/tools/explorer/ .

**Comment by jumph4x** [comment]
I like the idea of using the graph to test the tokens we get back, thanks!
