### ISSUE TITLE
ld: library not found for -lPods-MyApp-Bolts

### ISSUE THREAD

**Issue by engmsaleh** [facebook/facebook-ios-sdk#756]
I have installed FB SDV v.4.1.0 using Cocoapods and xcode project always fails with the following error
```
ld: library not found for -lPods-WeDoNotes-Bolts
```

Here is my Podfile
```
platform :ios, '7.0'

target 'MyApp' do
pod "FBSDKCoreKit"
pod "FBSDKLoginKit"
pod "FBSDKShareKit"
end
```

**Comment by javatai** [comment]
same for me.

**Comment by chrisp-fb** [comment]
Is this still a problem for you? If so, can you provide more details or an example workspace? I'm not able to reproduce any issues.
