### ISSUE TITLE
Suggestion: Changelog in releases page.

### ISSUE THREAD

**Issue by Ricardo1980** [facebook/facebook-ios-sdk#758]
Hello facebook.
It would be nice if you write the changelog in this website:
https://github.com/facebook/facebook-ios-sdk/releases

So in a nutshell we see all the changes. Specially in this library that changes very often.

Here you have a wonderful example:
https://github.com/ParsePlatform/ParseUI-iOS/releases

Thanks in advance.

**Comment by chrisp-fb** [comment]
Hi, our changelog is located on our developer site https://developers.facebook.com/docs/ios/change-log-4.x .
