### ISSUE TITLE
Invalid Scopes: friends_likes

### ISSUE THREAD

**Issue by Ricardo1980** [facebook/facebook-ios-sdk#760]
Hello!
I started receiving this error in my app:

"Invalid Scopes: friends_likes. This message is only shown to developers. Users of your app will ignore these permissions if present. Please read the documentation for valid permissions at: https://developers.facebook.com/docs/facebook-login/permissions"

My app uses facebook 3.23.2 rather than 4.1 (through cocoapods)
A few weeks I didn't receive it, and I think I didn't change anything in my app.
I don't understand that message and I don't see "friends_likes" in that website.
Any suggestion?
Thanks in advance.

**Comment by chrisp-fb** [comment]
All "friends_*" permissions have been removed as of April 30, 2015. This was announced one year earlier (2014). See https://developers.facebook.com/docs/apps/api-v1-deprecation for more details.

**Comment by Ricardo1980** [comment]
Just a note, I found the details here:
https://developers.facebook.com/docs/apps/faq#migration

Thanks.
