### ISSUE TITLE
FBSession returns with null permissions

### ISSUE THREAD

**Issue by hmobdev** [facebook/facebook-ios-sdk#762]
Hello,
I am developing an iOS application and I am facing problem in which FBSession returns null permissions. It was working in the previous Facebook SDK but when I switched to the latest SDK I am facing this problem.

I am using this method:

- (instancetype)initWithAppID:(NSString *)appID
                  permissions:(NSArray *)permissions
              urlSchemeSuffix:(NSString *)urlSchemeSuffix
           tokenCacheStrategy:(FBSessionTokenCachingStrategy *)tokenCachingStrategy;

I used this method as:

FBSession *session = [[FBSession alloc] initWithAppID:nil
                                              permissions:[NSArray arrayWithObjects:@"user_birthday",@"publish_stream",nil]
                                          urlSchemeSuffix:nil
                                       tokenCacheStrategy:tokenCachingStrategy];

Where I am doing mistake here, Do i need to change something in AppDelegate class?

**Comment by chrisp-fb** [comment]
Which version of the Facebook SDK are you using exactly? The latest major version (v4.x) no longer uses FBSession. See the [the upgrade guide](https://developers.facebook.com/docs/ios/upgrading-4.x#3to4).

If you are still using v3, we'll need more information to help. Can you add more information or attach your project? You can file a report to developers.facebook.com/bugs to get additional support or include confidential source code.
