### ISSUE TITLE
Can't build Facebook sdks 3.23.2 from tag 3.23.2

### ISSUE THREAD

**Issue by peepo3663** [facebook/facebook-ios-sdk#763]
I just clone it in my local but I see error from Xcode

**Comment by peepo3663** [comment]
![screen shot 2558-05-22 at 12 04 00 pm](https://cloud.githubusercontent.com/assets/2336535/7764372/ad3682b0-007a-11e5-96ab-b2bbc93a07bf.png)

**Comment by chrisp-fb** [comment]
Thanks, that's because of a change in Xcode 6.3 to warn you when a property is redeclared. You can add the `@dynamic` keyword as it suggested (e.g., https://gist.github.com/chrisp-fb/221acaf6ef44765ef9d7). If we decide on another update to v3.x this will be fixed then.

**Comment by peepo3663** [comment]
It's great. Keep it up good work.
