### ISSUE TITLE
Make accessTokenCache accessible.

### ISSUE THREAD

**Issue by thejeraldo** [facebook/facebook-ios-sdk#764]
Is there a way to get the ```currentAccessToken``` before calling ```- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions```?

Shouldn't I be allowed to manually check for a cached token on the AppDelegate like:
```FBSDKAccessToken *cachedToken = [[FBSDKSettings accessTokenCache] fetchAccessToken];```?

This is what worked for me before but recently I cannot do it again on my other apps.
http://stackoverflow.com/questions/29434392/ios-facebook-sdk-v4-x-access-token-null-despite-being-logged-in-via-fbsdkloginbu/30315789#30315789

**Comment by chrisp-fb** [comment]
The call to the FBSDKApplicationDelegate needs to be sent first to resolve any cached tokens. Note you don't have to immediately return the FBSDKApplicationDelegate, for example:

    - (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
      // Override point for customization after application launch.
      BOOL r = [[FBSDKApplicationDelegate sharedInstance] application:application didFinishLaunchingWithOptions:launchOptions];

      // do work with FBSDKAccessToken currentAccessToken

      return r;
    }
