### ISSUE TITLE
Using FBSDKLoginButton inside Swift framework: token info is scrubbed inside delegate callback

### ISSUE THREAD

**Issue by julien-c** [facebook/facebook-ios-sdk#765]
I'm building a dynamic framework that requires the Facebook SDK. 

When testing my framework against a demo app built inside the same Xcode project, everything works fine: I'm able to login using Facebook and retrieve a token. 

When using the build version of the framework inside a client app however, the following delegate still gets called:
```swift
func loginButton(loginButton: FBSDKLoginButton!, didCompleteWithResult result: FBSDKLoginManagerLoginResult!, error: NSError!) {
}
```

but `result.isCancelled` is true and `result.token` is `nil` (even though I approve the application).

Any idea why/how to fix this?

Thanks!

**Comment by julien-c** [comment]
Any new insight on this? Thanks!

**Comment by Francescu** [comment]
:+1: +1

**Comment by madlag** [comment]
+ 1 !

**Comment by chrisp-fb** [comment]
That's odd. Can you isolate the problem to a sample app/project to demonstrate the problem exactly? If you'd like, you can attach confidential code when filing reports at developers.facebook.com/bugs

**Comment by julien-c** [comment]
Definitely. I'll publish a sample workspace tomorrow.

**Comment by julien-c** [comment]
Ok @chrisp-fb, here is a testcase demonstrating the issue: https://github.com/julien-c/FBFrameworkClientApp

In the `FBSDKLoginButtonDelegate` callback, `isCancelled` is `true` and `token` is `nil`.

Let me know if we can help in any way!

**Comment by chrisp-fb** [comment]
Thanks for the sample. You also need to connect your app's app delegate to FBSDKApplicationDelegate:

```
  func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool
  {
    return FBSDKApplicationDelegate.sharedInstance().application(application, didFinishLaunchingWithOptions: launchOptions);
  }

  func application(application: UIApplication, openURL url: NSURL, sourceApplication: String?, annotation: AnyObject?) -> Bool
  {
    return FBSDKApplicationDelegate.sharedInstance().application(application, openURL: url, sourceApplication: sourceApplication, annotation: annotation);
  }
```

We describe this in the getting started guide https://developers.facebook.com/docs/ios/getting-started but let me know how we may make this easier for you or if there was some other documentation that was not clear.

**Comment by julien-c** [comment]
Oops, yes sure sorry. Of course we do this in our app. I will update the test case shortly.

**Comment by julien-c** [comment]
Ok, I've updated our testcase. `ClientApp` is our app that's a client of our framework. 

The workaround we've found in our real app is to instantiate the login button from the client (host) app and pass it to the framework. That way it works, however it's not very pretty. 

Let me know if you have any thoughts.

**Comment by chrisp-fb** [comment]
Hm, I'm still not seeing a problem - I just cloned your repo (93f29c220ad74881d0b6169ff6e51f60e8e3d120)  and ran the app and saw a successful login in the console:
```
Coming back from Facebook signin
Error: nil
result: <FBSDKLoginManagerLoginResult: 0x7f9c83d77f90> isCancelled: false token: <FBSDKAccessToken: 0x7f9c83d4a730>
declinedPermissions: [] grantedPermissions: [public_profile]
```
