### ISSUE TITLE
FBSDKShareDialog not showing Web-Based Dialog

### ISSUE THREAD

**Issue by atfermin** [facebook/facebook-ios-sdk#766]
I'm using the 4.2.0 version and noticed that the web-based dialog isn't showing when I try to share a link and the FB app is not installed. It shows the native iOS sheet instead.

Here's my code:

FBSDKShareLinkContent *content = [[FBSDKShareLinkContent alloc] init];
                content.contentURL = LINK HERE;
                content.contentTitle = TITLE HERE;
                content.contentDescription = DESC HERE;
                content.imageURL = IMAGE URL HERE;
                
[FBSDKShareDialog showFromViewController:self withContent:content delegate:nil];

The FB share dialog works fine when the FB app is installed. Am I missing anything?

**Comment by toddkrabach** [comment]
The dialog will automatically pick the most relevant version that is available.  It will choose the FB app if it is installed, iOS share sheet if you are logged in, web dialog as the final fallback.  If you logout of Facebook at the system level you should see the web dialog instead.

**Comment by atfermin** [comment]
Thanks @toddkrabach. Is there any work-around for this? The problem is the iOS share sheet is blank. If you try to share, it does share the link, but without the custom contentTitle & contentDescription set on the FBSDKShareLinkContent.

**Comment by toddkrabach** [comment]
You can also set the mode explicitly and check if the native dialog can show and then fallback to the browser-based dialog mode.

  FBSDKShareDialog *dialog = [[FBSDKShareDialog alloc] init];
  dialog.fromViewController = viewController;
  dialog.shareContent = content;
  dialog.delegate = delegate;
  dialog.mode = FBSDKShareDialogModeNative;
  if (![dialog canShow]) {
    dialog.mode = FBSDKShareDialogModeBrowser;
  }
  [dialog show];

**Comment by atfermin** [comment]
This is exactly what I need. Thanks @toddkrabach!

**Comment by atfermin** [comment]
Sorry @toddkrabach, but the web dialog shares the link only, and not the contentTitle, description & image. Is this the expected behavior?

**Comment by toddkrabach** [comment]
I've filed an internal bug on that.  We will look into it.
