### ISSUE TITLE
App deep links no longer work unless the app is currently running

### ISSUE THREAD

**Issue by chamarapaul** [facebook/facebook-ios-sdk#767]
We're currently running FB SDK 4.2.0, and it seems that since upgrading to 4.x, the code we have inside of application:openURL:sourceApplication:annotation: no longer executes if the app hasn't previously been started.

It appears that this is due to adding:

```objective-c
    return [[FBSDKApplicationDelegate sharedInstance] application:application
                                    didFinishLaunchingWithOptions:launchOptions];
```

to the bottom of application:didFinishLaunchingWithOptions: as per the instructions found here: https://developers.facebook.com/docs/ios/getting-started#startcoding. 

Prior to adding that code, the bottom of application:didFinishLaunchingWithOptions: simply had 'return YES;'. If we revert back to 'return YES;' at the end of application:didFinishLaunchingWithOptions: the code we have inside of application:openURL:sourceApplication:annotation: executes properly regardless of if the app was previously running or not. 

Because of the new FB SDK requirement, that deep links that we have specified for our app are not working unless the app is currently running in the background. Any advice on what we can do to resolve this?

Steps to reproduce:

1. Kill app
2. Type deep link into safari (ex: xyz://go/to/here)
3. App is opened, but user is on the main screen not the deep link
4. Go back to safari and revisit link
5. App is opened, and user is taken to deep link

**Comment by chrisp-fb** [comment]
You do not have to return the result of the FBSDKApplicationDelegate call if you additionally have custom deep link handling logic. FBSDKApplicationDelegate respects app delegate contracts such that it will return YES only if the URL was handled by the Facebook SDK (for example, if it was a FB login URL). In your case, if you're already handling xyz:// then you can return YES from your app delegate.

Our samples/docs are for simpler apps which are not processing their own deep links, but let me know if there is specific documentation you think would be improved by adding more detail. Thanks!

**Comment by chamarapaul** [comment]
Thanks so much for the info. Just wanted to make sure we're not missing out on any critical FB functionality by not returning the result of FBSDKApplicationDelegate.
