### ISSUE TITLE
FBSDKLoginButton's documentation: explicitly mention the fact that there's no need to addTarget

### ISSUE THREAD

**Issue by arielelkin** [facebook/facebook-ios-sdk#769]
It's currently not clear from [`FBSDKLoginButton`'s header file](https://github.com/facebook/facebook-ios-sdk/blob/master/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginButton.h#L49) that the button responds to taps by initiating log in.

See this: 
http://stackoverflow.com/questions/30643122/ios-parse-facebook-login-error-308-fbsdkloginbadchallengestring

**Comment by chrisp-fb** [comment]
Thanks, we'll update the comment.

**Comment by chrisp-fb** [comment]
Fixed in 4.3.0, thanks!

**Comment by arielelkin** [comment]
thank you.
