### ISSUE TITLE
FBSDKAccessToken+refreshCurrentAccessToken creates a token if no current token existed

### ISSUE THREAD

**Issue by widescape** [facebook/facebook-ios-sdk#770]
When calling `[FBSDKAccessToken refreshCurrentAccessToken]` while `[FBSDKAccessToken currentAccessToken] == nil`, a new `FBSDKAccessToken` will be created with `nil` values. This breaks the login behavior.

**Comment by chrisp-fb** [comment]
Good catch, we'll fix this in the next release to properly send an error to the callback. In the meantime, you can certainly guard against the nil currentAccessToken prior to make the refresh call.

**Comment by chrisp-fb** [comment]
This is fixed in 4.3.0, thanks!
