### ISSUE TITLE
Non Public Selectors (setResult)

### ISSUE THREAD

**Issue by Drusy** [facebook/facebook-ios-sdk#771]
Once I include FBSDKCoreKit in my project, I have the following errors from the Xcode validation process: 

> The app references non-public selectors in xxxx setResult:

This method seems to be called here : `FBSDKCoreKit/FBSDKCoreKit/FBSDKAppLinkResolver.m`

Regards

**Comment by chrisp-fb** [comment]
This is a false positive and should not cause any app rejection as `setResult:` is defined in Bolts. You should be be able to make the warning go away by:
1. linking Bolts.framework (required for FBSDKAppLinkResolver)
2. including the Bolts.h umbrella header and referencing `[BFTaskCompletionSource class]` which seems to help the linker identify the selector properly.

**Comment by Drusy** [comment]
Well, thank you for your quick answer ! 
I close this one, I hope it would help someone else who will care about this warning.
