### ISSUE TITLE
FBSDKLoginButton crash when used in UIPopover on iOS 7

### ISSUE THREAD

**Issue by hffmnn** [facebook/facebook-ios-sdk#772]
When using a `FBSDKLoginButton` in a `UIPopoverController` on an iPad with iOS 7 the application crashes. The app seems to hang in a loop when calculating the `intrinsicContentSize` of the button. To show the problem, I updated the scrumptious example code: https://github.com/rheinfabrik/facebook-ios-sdk/commit/def1ac22794bd1a1a62ade62d7bd8469b5c43cf1. Run it with iPad Simulator, iOS 7.1 to see the crash.

**Comment by chrisp-fb** [comment]
Thanks, we're looking into it.

**Comment by chrisp-fb** [comment]
We have a fix that will go out in the next release.

**Comment by chrisp-fb** [comment]
This is resolved in 4.3.0, thanks!
