### ISSUE TITLE
FBSDKMessageDialog shows for seconds only

### ISSUE THREAD

**Issue by atfermin** [facebook/facebook-ios-sdk#774]
Hi, I'm invoking the dialog via the convenience method as stated on the documentation:

[FBSDKMessageDialog showWithContent:content delegate:nil];

This just lets me "peek" at the Messenger app; it returns me back to my app after like 2 seconds.

**Comment by chrisp-fb** [comment]
Can you assign a delegate and see what information is returned in the error object, and describe how you constructed your `content` instance? The symptom your describing typically only occurs if there was a problem with the content.

**Comment by atfermin** [comment]
This is how I formed my content:

FBSDKShareLinkContent *content = [[FBSDKShareLinkContent alloc] init];
content.contentURL = LINK_URL;
content.contentTitle = CONTENT_TITLE;
content.contentDescription = CONTENT_DESCRIPTION;
content.imageURL = IMAGE_URL;

Same content is working with FBSDKShareDialog. Well, somehow. If you share it, FB app installed, the content never stops loading:

![screen shot 2015-06-18 at 10 44 39 am](https://cloud.githubusercontent.com/assets/6512090/8223168/42bcca7e-15a7-11e5-8ef8-b4d942d615a6.png)

But if you post it, the content shows without problems.

Without the FB app, the web dialog throws an error:

![screen shot 2015-06-18 at 10 47 39 am](https://cloud.githubusercontent.com/assets/6512090/8223185/80264c6e-15a7-11e5-8138-4f5753c7b26c.png)


I assigned a delegate to the FBSDKMessageDialog and this is the error it's throwing:
The operation couldn’t be completed. (com.facebook.Facebook.platform error 103.)

**Comment by chrisp-fb** [comment]
What is the actual data you're trying to share. Was there an inner error or other values in the userInfo dictionary of the NSError?

**Comment by atfermin** [comment]
Geez thanks for pointing that out. Apparently the website it was pointing to had a major glitch. It's working now. Thanks a lot!

**Comment by chrisp-fb** [comment]
Great!
