### ISSUE TITLE
Share and Login buttons to be merged in Swift

### ISSUE THREAD

**Issue by ilirvg** [facebook/facebook-ios-sdk#776]
Hi there,

How can I change what happens when the Share button is clicked. More exactly I need to have a share button on my app and not a log in, so if I have not login and I click share the login view will be shown and than the link will be shared. But how can I merge these two buttons on one in Swift.

Here is a link with some more details of my question
http://stackoverflow.com/questions/30976507/facebook-sdk-4-1-for-swift-single-button-to-be-used-for-share-and-login/30977487#30977487

Thank you in advance,

Best,
Ilir

**Comment by chrisp-fb** [comment]
You'll want to create your own UIButton instance to perform that logic yourself. You can use `FBSDKLoginManager` to perform the login. To perform the sharing, you can one of the implementations of `FBSDKSharing`.

By the way, in case you didn't know the `FBSDKShareButton` uses the `FBSDKShareDialog` which does not require login (it will perform an app switch to the Facebook app or Safari) which is often a better user experience.

Another option you could consider is to use both buttons and hide them (or swap them out) depending on if the user has logged in.
