### ISSUE TITLE
Cant set neither contentDescription nor contentTitle on FBSDKShareLinkContent

### ISSUE THREAD

**Issue by catalincraciun** [facebook/facebook-ios-sdk#777]
Hello,

I am trying to set a share form with an initial text, but setting the contentDescription or contentTitle does nothing. Having urls or images works but these two just don't seem to work

* Here is the code I have used for this
![facebookcode](https://cloud.githubusercontent.com/assets/5362999/8288162/152b80ea-191d-11e5-95c7-273e98a6fc41.png)
* Here is the resulted view controller
![image1](https://cloud.githubusercontent.com/assets/5362999/8288253/9e69feea-191d-11e5-8b07-1d3440529235.PNG)

Thanks in advance
-------------------------

**Comment by chrisp-fb** [comment]
I'm getting 503s when trying to view those links. Can you upload them somewhere else?

**Comment by catalincraciun** [comment]
Here they are:

1. http://www.filedropper.com/9e69feea-191d-11e5-8b07-1d3440529235
2. http://www.filedropper.com/152b80ea-191d-11e5-95c7-273e98a6fc41

Sorry for the cheap filedropper

**Comment by chrisp-fb** [comment]
This is by design, you must also set the `contentURL` property. The title and description are applied to the link (see the header comments on those properties).

**Comment by catalincraciun** [comment]
Thank you, isn't any way to set an initial text for the Facebook post and not the URL? I understand that contentDescription and contentTitle is related to the URL.
