### ISSUE TITLE
og.likes action results in "likes an object" instead of "likes an [og:type]"

### ISSUE THREAD

**Issue by Nuke-** [facebook/facebook-ios-sdk#778]
When using open graph og.likes through the native share dialog the og:type seems to be ignored because in the feed of the facebook user it is displays as "an object".
And when a predefined object is used (one that is available through the object browser) the type is correctly displayed as "likes a movie".
When using video.watches and video.wants_to_watch the type is used correctly.
It is only when og.likes is used that the type doesn't seem to be used.

I'm using SDK 4.2.0

Example code.
You need to change the value for fb:app_id and showFromViewController.

    - (void)share
    {
        FBSDKShareOpenGraphAction *action = [[FBSDKShareOpenGraphAction alloc] init];
        NSMutableDictionary *params = [NSMutableDictionary dictionary];
        [params setValue:self.facebookId forKey:@"fb:app_id"];
        [params setValue:@"Cold Mountain" forKey:@"og:title"];
        [params setValue:@"This star-studded tale set during the Civil War tells of a young soldier (Jude Law) who despite his injury struggles to get home to his beloved (Nicole Kidman). In his absence his wife has struck up a friendship with a scrappy drifter (Renee Zellweger)." forKey:@"og:description"];
    
    
        [params setValue:@"video.other" forKey:@"og:type"];
        action.actionType = @"og.likes";
    
    
        FBSDKShareOpenGraphObject *object = [FBSDKShareOpenGraphObject objectWithProperties:params];
        [action setObject:object forKey:@"video"];
        [action setObject:object forKey:@"object"];
        // Predifined object
        // [action setString:@"804303226334963" forKey:@"object"];
        FBSDKShareOpenGraphContent *content = [[FBSDKShareOpenGraphContent alloc] init];
        content.action = action;
        content.previewPropertyName = @"video";
        [FBSDKSettings setLoggingBehavior:
         [NSSet setWithObject:FBSDKLoggingBehaviorGraphAPIDebugInfo]];
    
        FBSDKShareDialog *dialog = [FBSDKShareDialog
                                    showFromViewController:ZWApplicationManager.sharedInstance.representationManager.mainViewController
                                    withContent:content
                                    delegate:self];
        dialog.mode = FBSDKShareDialogModeNative;
    #ifdef DEBUG
        dialog.shouldFailOnDataError = YES;
    #endif
        NSLog( @"### running FB sdk version: %@", [FBSDKSettings sdkVersion] );
        NSError *error;
        [dialog validateWithError:&error];
        NSLog(@"validateWithError: error: %@", error);
        [dialog show];
    }

**Comment by chrisp-fb** [comment]
Thanks, we're looking into it. This does look like a bug in the share dialog (if you use FBSDKShareAPI the og type is respected).  If you can, please file a report to developers.facebook.com/bugs so we can better track the issue.
