### ISSUE TITLE
[FBSDKShareDialogModeShareSheet] does not use contentTitle and contentDescription

### ISSUE THREAD

**Issue by tolentinokas** [facebook/facebook-ios-sdk#780]
Hi, just wanted to ask a question regarding Facebook sharing in iOS.

Here is my code that shares something to Facebook using mode = ShareSheet. When I share the content, the post is not using the contentTitle, contentDescription, and imageURL that I supplied. Am I missing something that needs to be populated? Thank you!

// Share content
FBSDKShareLinkContent *content = [[FBSDKShareLinkContent alloc] init];
content.contentURL = url;
content.contentTitle = @"ContentTitle";
content.contentDescription = @"ContentDesccription";

// Share dialog - Share Sheet
FBSDKShareDialog *dialog = [[FBSDKShareDialog alloc] init]; dialog.fromViewController = controller;
dialog.shareContent = content;
dialog.mode = FBSDKShareDialogModeShareSheet;
dialog.delegate = self;
[dialog show];

Thank you for your help! :)

Note: This only happens when mode is FBSDKShareDialogModeShareSheet.

This is the one shared through FBSDKShareDialogModeNative:
![screen shot 2015-06-25 at 3 20 49 pm](https://cloud.githubusercontent.com/assets/10443631/8349299/42498a4e-1b4e-11e5-9cf6-ace05977dc1b.png)

And this is the one shared through FBSDKShareDialogShareSheet:
![screen shot 2015-06-25 at 3 21 07 pm](https://cloud.githubusercontent.com/assets/10443631/8349362/af47d3da-1b4e-11e5-979b-90a6c8f74882.png)

**Comment by mingflifb** [comment]
This unfortunately is a limitation of the share sheet. It uses SLComposeViewController (Apple's social framework), which only takes a url, and doesn't allow other parameters like title or description. If you have access to the server for these web pages, you can add og:title and og:description meta tags to include that data.

**Comment by tolentinokas** [comment]
Hi @mingflifb , but the SLComposeViewController take in title and image, right?

/ Sets the initial text to be posted. Returns NO if the sheet has already been
// presented to the user. On iOS 6.x, this returns NO if the specified text
// will not fit within the character space currently available; on iOS 7.0 and
// later, you may supply text with a length greater than the service supports,
// and the sheet will allow the user to edit it accordingly.
- (BOOL)setInitialText:(NSString *)text;

// Adds an image to the post. Returns NO if the additional image will not fit
// within the character space currently available, or if the sheet has already
// been presented to the user.
- (BOOL)addImage:(UIImage *)image;

// Adds a URL to the post. Returns NO if the additional URL will not fit
// within the character space currently available, or if the sheet has already
// been presented to the user.
- (BOOL)addURL:(NSURL *)url;

**Comment by mingflifb** [comment]
setInitialText is supposed to be the message (not the title for the link), and addImage is for image uploads, not the image thumbnail associated with the shared link, it's also an UIImage instead of a url. Since they have different semantic meanings and different data types, we chose not to overload them with the ShareContent data.

**Comment by tolentinokas** [comment]
Now I understand. Thank you so much @mingflifb  for clarifying. :+1: :smiley:
