### ISSUE TITLE
FBSDKShareDialog (native) don't invokes delegate didCancel when user tap on Cancel button

### ISSUE THREAD

**Issue by NachoNachev** [facebook/facebook-ios-sdk#781]
If there is FB App on device it appears when sharing link. In both cases (when post content or cancel post) after my app returns to foreground the share dialog always calls the complete delegate method **sharer:didCompleteWithResults:** .
If there isn't FB App on the device then iOS FB share dialog appears. When Cancel on this dialog is pressed then **sharerDidCancel:** delegate method is invoked.

Here is an example code:
```objective-c
    FBSDKShareLinkContent *content = [[FBSDKShareLinkContent alloc] init];
    content.contentURL = [NSURL URLWithString:@"http://www.google.com"];
    content.contentDescription = @"Check out this awesome site!";
    [FBSDKShareDialog showFromViewController:self
                                 withContent:content
                                    delegate:self];
```
My delegate methods:
```objective-c
    #pragma mark - FBSDKSharingDelegate
    
    - (void)sharer:(id<FBSDKSharing>)sharer didCompleteWithResults:(NSDictionary *)results {
        NSLog(@"FB Share complete");
    }
    
    - (void)sharer:(id<FBSDKSharing>)sharer didFailWithError:(NSError *)error {
        NSLog(@"FB Share failed");
    }
    
    - (void)sharerDidCancel:(id<FBSDKSharing>)sharer {
        NSLog(@"FB Share Canceled");
    }
```

**Comment by SotoiGhost** [comment]
I made a quick sample to reproduce the error. Here is the sample:
https://www.dropbox.com/s/t7yi8hxp6a2bp2e/FacebookTest.zip?dl=0

Steps to reproduce the bug:
- [IMPORTANT] Make sure that you haven't granted any permissions to your app. If yes, from your FB account, go to Settings/Apps/Logged in with Facebook/Show All and remove your app.
- Add your FB App ID into the plist file and AppDelegate.m
- Run the test
- Tap the “Share” button and cancel the request
  - On Device with Native Share Dialog: The `sharer:didCompleteWithResults:` message is called
  - On Simulator with Safari Share Dialog: The `sharer:didCompleteWithResults:` message is called
- Log in with Facebook and grant permissions
- Tap the “Share” button again and cancel the request
  - On device with Native Share Dialog: The `sharerDidCancel:` message is called
  - On Simulator with Safari Share Dialog: The `sharer:didCompleteWithResults:` message is called (nothing change)

So, you must grant permissions before, to make the Share Dialog process work correctly (at least on device).

**Comment by mingflifb** [comment]
The Native Share Dialog experience you're seeing is by design, and is documented here: https://developers.facebook.com/docs/ios/troubleshooting#onsuccess

The Safari dialog experience may be a bug, and we'll look at fixing that from the server side.
