### ISSUE TITLE
Current access token in iOS 7

### ISSUE THREAD

**Issue by brightsider** [facebook/facebook-ios-sdk#782]
In iOS 7 [FBSDKAccessToken currentAccessToken] always return nil.

**Comment by chrisp-fb** [comment]
Did you follow all the steps in the [Getting Started Guide](https://developers.facebook.com/docs/ios/getting-started) (such as connecting the FBSDKApplicationDelegate)?

If so, can you provide additional details on what you're trying to do? I'm able to get a currentAccessToken after login using the samples shipped in the SDK. Feel free to reopen if you can consistently reproduce the issue or provide a sample.
