### ISSUE TITLE
Throw exception in +[FBSDKInternalUtility validateURLSchemes]

### ISSUE THREAD

**Issue by BenjaminSarkisyan** [facebook/facebook-ios-sdk#783]
Hello.

I login in, using this code:
```
FBSDKLoginManager *login = [FBSDKLoginManager new];
login.loginBehavior = FBSDKLoginBehaviorWeb;

[login logInWithReadPermissions:permissions handler:^(FBSDKLoginManagerLoginResult *result, NSError *error) {
   
}];
```

and in method `-[FBSDKLoginManage logInParametersWithPermissions:]` called method `+[FBSDKInternalUtility validateURLSchemes]`and he throw exception, because i don't set url scheme.

But, why should i set url scheme, if i not used `loginBehavior == FBSDKLoginBehaviorNative` or `loginBehavior == FBSDKLoginBehaviorBrowser`.

This is normal behavior or this is bug?

**Comment by chrisp-fb** [comment]
This is normal behavior. While you're technically correct that the FBSDKLoginBehaviorWeb would not explicitly require it, the scheme configuration is also used by other parts of the SDK (such as for the share dialogs) or for other Facebook features (such as deep linking into your app from notifications). Thanks.
